### ISSUE TITLE
TINT2-THEME::NOT-INSTALLED

### ISSUE THREAD

**Issue by gnosticscrounger** [deviantfero/wpgtk#10]
For some reason, it refuses to install the tint2 theme, returning the above error even though I select yes. What gives?

**Comment by deviantfero** [comment]
Right now i'm not at home but you could copy it manually, it's under the themes folder in the repo, that's a temporary fix, still make sure you have the folder in ~/.config/tint2, if you do i'd like to see a screenshot as it is the forst time i've seen this issue, also are you intalling from AUR or just cloning?
