### ISSUE TITLE
Suggestion: Urxvt Transparency Fix

### ISSUE THREAD

**Issue by YOUR-WORST-TACO** [deviantfero/wpgtk#101]
Hello deviantfero,
This is one of my favorite tools for making my distro look purty so having to reopen all my terminals to get transparency back is painful, however I think I have found a solution.

After a bit of ripping and tearing I found that the -a flag for pywal allows you to set transparency from 0-100, I tested this by editing your color.py

color.py (line 14)
```
def get_pywall_dict(filename):
    pywal.util.Color.alpha_num = 80 # <-- my inserted code
    image = pywal.image.get(join(config.WALL_DIR, filename))
    return pywal.colors.get(image,
                            backend=config.wpgtk.get('backend', 'wal'),
                            cache_dir=config.WALL_DIR)
```

I will probably find a way to reference the .Xresources file and check for transparency options and then properly handle transparency for urxvt, unless of course this is something you would be willing to implement.

Either way, this should fix urxvt transparency upon updating sequences on all terminals.

**Comment by YOUR-WORST-TACO** [comment]
One quick comment, pywal.util.Color.alpha_num must be a string value, otherwise it will break pywal

**Comment by deviantfero** [comment]
hi, I've been really busy lately, so I haven't been able to reply, I'll get around this, thanks for opening the issue, I'll mark it as an improvement, if you're able to make a PR i'd be happy to take a look.

**Comment by YOUR-WORST-TACO** [comment]
I will probably do some work on it right now, I've got nothing better to do.

**Comment by deviantfero** [comment]
thanks, it's greatly appreciated, I've been too busy to do the fix myself.

-- att. Fernando Vasquez --

**Comment by YOUR-WORST-TACO** [comment]
Alright, I have it working, gonna run some tests and clean it up and then submit it.

**Comment by YOUR-WORST-TACO** [comment]
I have submitted a pull request.

**Comment by deviantfero** [comment]
follow #104 for further progress.

**Comment by deviantfero** [comment]
You can now set transparency with the `--alpha` flag, or specifying the desired alpha in your config file, I will close this issue, to retain transparency accross terminals add `(cat ~/.config/wpg/sequences)` to your shell configuration file.
