### ISSUE TITLE
restoring wpg colors on login (bspwm)

### ISSUE THREAD

**Issue by cj360** [deviantfero/wpgtk#107]
I saw issue #100 so I added 
`~/.config/wpg/wp_init.sh &`to bspwmrc and 
`(cat ~/.config/wpg/sequences &)` to ~/.bashrc. But the colors on login dont match the ones appiled from wpg prior to logging out, they're flat and mostly black. I can set the same colors & wallpaper from wpg again so I guess I just have the wrong configs/files being called on log in?

**Comment by deviantfero** [comment]
where are you getting the wrong colors? I personally use `bspwm` and I don't have an issue with this, could I get a screenshot? btw posting my `bspwmrc`

```
#!/bin/sh

# startup
export SXHKD_SHELL="sh"
bash "$HOME/Code/scripts/polybar.sh" &
setxkbmap -option caps:escape &
pgrep sxhkd      || sxhkd &
pgrep urxvtd     || urxvtd &
pgrep emacs      || emacs --daemon &
pgrep dockd      || dockd --daemon &
pgrep volumeicon || volumeicon &
pgrep compton    || compton &
bash "$HOME/.config/wpg/wp_init.sh" &

# global settings
bspc config borderless_monocle true
bspc config single_monocle true
bspc config gapless_monocle true
bspc config border_width 3
bspc config window_gap   0
bspc config top_padding  21
bspc config pointer_follows_focus		false
bspc config focus_follows_pointer		true
bspc config pointer_follows_monitor     true
bspc config remove_unplugged_monitors	true
bspc config remove_disabled_monitors	true
bspc config ignore_ewhm_focus			true
bash "$HOME/.config/bspwm/bspwm_colors.sh" &

# rules
bspc rule -r "*:*"
bspc rule -a URxvt:scratchpad sticky=on state=floating
bspc rule -a Wpg:wpg state=floating
bspc rule -a Polyconf:* state=floating
bspc rule -a Zathura:zathura state=tiled
bspc rule -a Google-chrome desktop=^1
bspc rule -a DBeaver desktop=focused:^3
bspc rule -a Thunar:thunar state=floating rectangle=800x600+0+0 center=true

# desktop / monitor
for monitor in $(bspc query -M); do
    bspc monitor $monitor -d I II III IV V
done

exit 0;
```

**Comment by cj360** [comment]
I think I'm being foolish as my polybar & bspwm are still set to read colors from pywal's output to xresources so I think its just user error actually... (whoops)

**Comment by deviantfero** [comment]
`polybar` should work, but `wpgtk` also takes into account the user defined `.Xresources`, are you defining some colors there? that might be a cause for polybar not picking up the colors.

as for `bspwmrc` if you want to keep using the "pywal" way, you should just add this to the top of your `bspwmrc`:

```
source "$HOME/.config/wpg/formats/colors.sh"
```

If you want to do it as I do it, let's call it the `wpgtk` way, you should use templates, I include a default bspwm template (which only affects the colors), you can install it by executing:

```sh
wpg-install.sh -b

# do this to get an idea of available templates
wpg-install.sh -h
```
this will create a separate "template" which you can open from wpg to edit the keywords you want replaced.

**Comment by cj360** [comment]
I think I understand know, thank you for the explanation.
