### ISSUE TITLE
Sorting Dropdown Entries

### ISSUE THREAD

**Issue by MiltFra** [deviantfero/wpgtk#108]
Title.
It bothers me so much that I have to spend 10 seconds to find an image in the dropdown menu. I don't know is there's any pattern at the moment, but to me it's certainly not obvious.
I don't think it's going to be hard either so I hope I'll see that soon!

Sincerely
Franz Miltz

**Comment by deviantfero** [comment]
Hi, the new release should fix this issue, please upgrade and confirm that it works as intended!

**Comment by MiltFra** [comment]
Yeah, it works as intended!
Thanks alot!
