### ISSUE TITLE
xrdb ressource files not created

### ISSUE THREAD

**Issue by prysme01** [deviantfero/wpgtk#11]
Hello, 

Fresh installation using yaourt 
Here is the stacktrace

['neilkremer_0.jpg', 'markbridger_3.jpg', 'mikereyfman_0.jpg', 'mariomoreno_0.jpg', 'vitaliprokopenko_0.jpg', 'pauloflop_5.jpg', 'stefanoronchi_0.jpg', 'vitaliprokopenko_1.jpg', 'markbridger_0.jpg', 'neilkremer_1.jpg', 'wallpaper-2695345.jpg', 'michelbricteux_1.jpg', 'pauloflop_4.jpg', 'markbridger_1.jpg', 'stefanoronchi_2.jpg', 'markbridger_6.jpg', 'vitaliprokopenko_2.jpg', 'neilkremer_2.jpg', 'markbridger_5.jpg', 'charlesdavey_0.jpg', 'mariomoreno_2.jpg', 'wallpaper-2695345_modified.jpg', 'pauloflop_1.jpg', 'johannesvandonge_0.jpg', 'pauloflop_2.jpg', 'mariomoreno_7.jpg', 'mariomoreno_4.jpg', 'olegzhukov_1.jpg', 'mariomoreno_6.jpg', 'mariomoreno_3.jpg', 'pauloflop_3.jpg', 'mikereyfman_1.jpg', 'mikereyfman_2.jpg', 'mariomoreno_8.jpg', 'mariomoreno_1.jpg', 'waltersoestbergen_0.jpg', 'stefanoronchi_3.jpg', 'mikereyfman_6.jpg', 'johannesvandonge_2.jpg', 'michelbricteux_3.jpg', 'michelbricteux_2.jpg', 'cheap_free_wallpaper_hw49w.jpg', 'background.jpg', 'mikereyfman_5.jpg', 'michelbricteux_0.jpg', 'mikereyfman_4.jpg', 'pauloflop_0.jpg', 'markbridger_4.jpg', 'johannesvandonge_1.jpg', 'markbridger_2.jpg', 'olegzhukov_0.jpg', 'mikereyfman_3.jpg', 'mariomoreno_5.jpg', 'stefanoronchi_1.jpg']
Traceback (most recent call last):
  File "/usr/local/bin/src/wpg.py", line 182, in colorscheme_box_change
    self.pixbuf_sample = GdkPixbuf.Pixbuf.new_from_file_at_size( samplepath, width=500, height=500 )
GLib.Error: g-file-error-quark: Failed to open file '/home/prysme/.wallpapers/.neilkremer_0.jpg.sample.png': Aucun fichier ou dossier de ce type (4)
Set
:: Set /home/prysme/.wallpapers//neilkremer_0.jpg as background
ln: impossible d'accéder à '/home/prysme/.wallpapers/.neilkremer_0.jpg.colors': Aucun fichier ou dossier de ce type
xrdb: No such file or directory
xrdb: can't open file '/home/prysme/.wallpapers/.neilkremer_0.jpg.Xres'
::  is not a recognised directive
xrdb: No such file or directory
xrdb: can't open file '/home/prysme/.wallpapers/.neilkremer_0.jpg.Xres'
[Errno 2] Aucun fichier ou dossier de ce type: '/home/prysme/.wallpapers/.neilkremer_0.jpg.Xres'
(2, 'Aucun fichier ou dossier de ce type')
/home/prysme/.wallpapers/.neilkremer_0.jpg.Xres
FG: 4a828f
BG: 28464c
CHANGING::OPENBOX
NO OPENBOX INSTALL!
CHANGING::TINT2
CHANGING::GTK
CHANGING::ICONS
CURRENT GLYPH: 178984
SUCCESS

Thanks for your help

**Comment by deviantfero** [comment]
I'm not home right now but it seems that this is an issue caused by adding
your wallpapers manually to the ~/.wallpapers folder, to fix this add your
images with the add button, it doesn't matter of they are already in that
folder doing this will generate the files that it says it's missing...

I will provide a quicker way to add all your wallpapers once i get home.

**Comment by prysme01** [comment]
Thanks for your reply, you are right, I've added manually the wallpaper into .wallpaper directory.

**Comment by deviantfero** [comment]
also btw you could run this if you wish to add all those wallpapers in one command, warning though, it's gonna generate all the color palletes, so it might take a little while, still

```
cd ./to/your/wallpaper/dir && ls | grep -E "\..*$" | xargs -d ' ' wpcscript add 
```
