### ISSUE TITLE
wallpaper variable

### ISSUE THREAD

**Issue by kleshas** [deviantfero/wpgtk#113]
By request:

Can we get the wallpaper variable (as specified in ~/.config/wpg/formats/colors.css) use the full path name of the image, rather than just the image name?

**Comment by deviantfero** [comment]
thanks for submitting this, yes I'll take care of this as soon as I get the chance

**Comment by deviantfero** [comment]
this has been taken care of, but I'd like to get confirmation, please update to release `5.8.5`

**Comment by kleshas** [comment]
I don't think it's working.  I have confirmed I updated to 5.8.5 ("sudo pip install ." says 5.8.5), but the colors.css in ~/.config/wpg/formats/colors folder still only has
--wallpaper: url("704146.jpg");

**Comment by deviantfero** [comment]
You might need to re-add the images, could you try if it works with a newly added image?

**Comment by kleshas** [comment]
My bad - that works.  I should've thought of it.

**Comment by deviantfero** [comment]
I will close this issue, enjoy!
