### ISSUE TITLE
polybar not autostarting with template

### ISSUE THREAD

**Issue by reizero1** [deviantfero/wpgtk#115]
Hello, thank you for your lovely program. I'm having a little issue with polybar not starting with i3, and I'm 90% sure it has to do with these lines ( ~/.config/polybar/config): "background = ${xrdb:color8}" \ "foreground = ${xrdb:color15}" \ "foreground-alt = ${xrdb:color15}". If I change these lines, then polybar will start with i3. Restarting i3 after logging in will start polybar with the correct colors. In my i3 config, I have: "exec_always --no-startup-id $HOME/.config/polybar/launch.sh" after "exec --no-startup-id ~/.config/wpg/wp_init.sh". So I'm not sure what to do.

**Comment by deviantfero** [comment]
I was about to mention that you need fallback values, I'd recommend using a
template to do something like:

"xrdb:color8:<COLOR8>"

-- att. Fernando Vasquez --
