### ISSUE TITLE
Crashes if backend fails

### ISSUE THREAD

**Issue by dustinlacewell** [deviantfero/wpgtk#118]
![1920x1200_px_abstract_andy_gilmore_geometry_monochrome_pattern_symmetry-777698](https://user-images.githubusercontent.com/53952/49734689-bc326980-fc4a-11e8-9c9b-6c0afbb98a78.jpg)

Using an image with not many colors causes the backend to fail to generate a theme:

```
[inf] image         Using image 1920x1200_px_abstract_Andy_Gilmore_geometry_monochrome_pattern_Symmetry-777698.jpg.
[inf] colors        Generating a colorscheme.
[inf] colors        Using wal backend.
[err] wal           Imagemagick couldn't generate a palette.
[err] wal           Try a different image or backend.
```
Then wpg crashes.

**Comment by deviantfero** [comment]
as a temporary fix, you could try a different backend, but this is something that I have in mind for the next release, if the backend fails, just default to one of the pre-built colorschemes

**Comment by deviantfero** [comment]
this is no longer the case in version `5.8.5`
