### ISSUE TITLE
Unable to install from AUR

### ISSUE THREAD

**Issue by aouerfelli** [deviantfero/wpgtk#120]
When using a package manager (I'm using yay) to install this from the AUR, I get the error:

`Parsing SRCINFO (1/1): wpgtk-git failed to parse wpgtk-git: Line 23: key "pkgbase" can not occur after pkgbase or pkgname: pkgbase = wpgtk-git`

It seems like other people are having this issue as well, because the latest comment on the [AUR page](https://aur.archlinux.org/packages/wpgtk-git) describes this exact issue.

**Comment by aouerfelli** [comment]
Looks like it's been fixed. Thanks!

**Comment by deviantfero** [comment]
yep, thanks for the heads up!
