### ISSUE TITLE
Typos in the Wiki

### ISSUE THREAD

**Issue by lachlantula** [deviantfero/wpgtk#121]
There are several typos in the Wiki that should be corrected to avoid confusion:

- ['Restore on Startup'](https://github.com/deviantfero/wpgtk/wiki/Colorschemes#restore-on-startup) should suggest running the file `~/.config/wpg/wp_init.sh`, instead of `$HOME/.config/wpg/wp-init.sh`; for me, the latter did not exist.
- [Configuration](https://github.com/deviantfero/wpgtk/wiki/Configuration) uses the incorrect 'whether' after `set_wallpaper = true`.

These were just two I came across while browsing; if you want me to check if there are more, I am willing. :)

**Comment by deviantfero** [comment]
Hi, thanks for your help with this typos, I've fixed them and if you could find more I'd appreciate it, please let me know if you can't contribute to the docs
