### ISSUE TITLE
Wallpaper not applied from wp_init.sh when invalid tokens in file name

### ISSUE THREAD

**Issue by aouerfelli** [deviantfero/wpgtk#122]
Pretty much what the title says. Since the image file name is not quoted in `wp_init.sh`, the script will fail with a syntax error. Here's an example:
```bash
#!/usr/bin/env bash
wpg -rs Looking_Up_(Final).png Looking_Up_(Final).png
```
When changed to:
```bash
#!/usr/bin/env bash
wpg -rs "Looking_Up_(Final).png" "Looking_Up_(Final).png"
```
it works fine.

**Comment by deviantfero** [comment]
hi, thanks for this find, I'll fix this ASAP

**Comment by deviantfero** [comment]
try `5.8.6`!

**Comment by aouerfelli** [comment]
Thanks!
