### ISSUE TITLE
Light themes could be improved

### ISSUE THREAD

**Issue by furrycatherder** [deviantfero/wpgtk#126]
Many of the light themes I've tried to generate required adjusting because colors like (terminal) green and yellow were basically identical to the background color.

Red, green, and yellow are frequently used to convey status information, making the light themes mostly unusable by default.

Could you programmatically reduce the lightness/brightness of these colors to get something more consistently readable? We could do something like set a target contrast and apply RK methods for the general case?

**Comment by deviantfero** [comment]
Are you already using the auto adjust feature? I'll wirte a more detailed
reply when I get the chance but I agree that de could use some improvement,
the auto adjust feature will produce more readable colorschemes without
much effort, I might add an option to do this automatically

**Comment by furrycatherder** [comment]
That's correct, I'm specifically talking about the auto-adjusted light themes. The light colors probably just need to have their lightness values inverted.

**Comment by deviantfero** [comment]
Hi, I'm afraid I'm gonna have to close this issue, I'm able to get consistently good results as it is right now, and any adjustment I make leaves me unsatisfied, there are a few points to this:

- Any changes I make don't apply to each and every color scheme you can think of, some will just look bad
- I want changes between dark and light themes to be easily reversible, altering the first 8 colors defeats this purpose.
- The purpose of `wpgtk` is not being stuck with defaults, you can easily get nice results by adjusting the theme yourself, you have granular control over the color scheme.
- I'm able to constantly get nice results by just auto-adjusting and moving contrast a little, pics attached:

![test1](https://i.imgur.com/xdE2BLb.png)
![test2](https://i.imgur.com/3mA1IJv.png)

thanks for writing this issue, if you have any other request I'll happily look into it.
