### ISSUE TITLE
Auto adjust automatically, regenerate color scheme from gui

### ISSUE THREAD

**Issue by jasperro** [deviantfero/wpgtk#127]
The auto adjust feature is very good, but it would be handy if the auto adjust could be set to run automatically (with a switch in the gui). I refresh my wallpaper collection sometimes and need to run auto-adjust on all of them. The standard colors are always bad, why should it not auto-adjust automatically?

I would also really like to have an option to regenerate the color scheme from the gui (when you mess up contrast and such), instead of removing the color scheme manually.

**Comment by deviantfero** [comment]
I will add this features to the next release, check on #125 for status

**Comment by deviantfero** [comment]
wpgtk 6.0.0 is live!
