### ISSUE TITLE
A cli option to only generate the gtk theme

### ISSUE THREAD

**Issue by Fuzzbox999** [deviantfero/wpgtk#128]
Hi,
I use shortcuts in ranger to manage my themes. They call pywal and several scripts to change i3 or Windowmaker, dmenu, dunst, terms etc... colors. I used to run pywal with the oomox -g option.
I'd like being able to do the same with wpgtk.
If I use "wpg -a file.jpg && wpg -n -s file.jpg" with only the gtk/icon templates installed, the gtk theme is generated, but my term colors temporarily change too, and I have to reload pywal colors with the wal -R command. Could there be an option to only generate the gtk and icon theme ?
I may switch completely to wpgtk, but the --light and --backend commands do not seem to work for now (they work from the gui, not from cli).

**Comment by deviantfero** [comment]
`--backend` should work out of the box in the current version, I'm working on adding --light support when used with `-s` to behave like `pywal`

**Comment by Fuzzbox999** [comment]
Thanx for your answer.
In fact, --backend works, but whatever backend is specified behind the --backend option, wpg uses the one wich is selected in the wpg gui.

**Comment by deviantfero** [comment]
I've just checked and I can't reproduce, when I give the `--backend` option to `wpgtk` it uses the correct backend, this is reflected even in the GUI

**Comment by Fuzzbox999** [comment]
Maybe I use it the wrong way ?
I use wpg --backend colorz -a file.jpg
If I'm wrong, sorry to lose your time.
Otherwise, if wal is selected and saved in the gui, wal will be used instead of colorz to generate the theme. see https://imgur.com/gallery/w2LzuwW

**Comment by Fuzzbox999** [comment]
Ok. I get it. wpg --backend colorz starts the wpg gui with the colorz backend loaded.
I thought it was supposed to be used in a cli command.

**Comment by deviantfero** [comment]
Use it along with -s to set a theme with that backend

**Comment by Fuzzbox999** [comment]
Ok. Thx. It works if I select the backend I want in the wpg gui before running wpg --backend -s file.jpg.
No way to pass the backend name directly from the cli without opening the gui ?
Something like wpg -a file.jpg && wpg --backend schemer2 -s file.jpg ?

**Comment by deviantfero** [comment]
You can also specify it in your config file under .config/wpg/wpg.conf

**Comment by Fuzzbox999** [comment]
Ok. That gives me a way to do it on the fly with a sed script applied to wpg.conf.
Thanx for your time.

**Comment by deviantfero** [comment]
you should use it like this:

```sh
# if you don't wish to edit the theme afterwards
wpg --backend colorz -s ~/path/to/some/file.jpg

#if you wish to edit the theme afterwards from the GUI
wpg --backend colorz -a ~/path/to/some/file.jpg && wpg --backend colorz -s file.jpg
```

still I recommend you stick to one sole backend, since having a collection with multiple backends is not very much supported, I guess you can make it work, but I've never really focused on that
