### ISSUE TITLE
Lighten/darken color 8?

### ISSUE THREAD

**Issue by furrycatherder** [deviantfero/wpgtk#129]
fish and zsh (by way of zsh-autosuggestions) use color8 to display their command suggestions. Currently, color 8 has poor contrast against the background color, requiring some manual tweaking.

Here's the auto-adjusted theme:
![2019-01-24-102801_614x332_scrot](https://user-images.githubusercontent.com/36235154/51692756-33d21300-1fc3-11e9-9f8e-053bc8cee919.png)

This is after manually bumping color8's lightness:
![2019-01-24-103041_614x332_scrot](https://user-images.githubusercontent.com/36235154/51692774-3a608a80-1fc3-11e9-83ee-3f514999b62b.png)

**Comment by furrycatherder** [comment]
The same issue exists with light themes, so we should reduce the lightness there.

**Comment by furrycatherder** [comment]
@deviantfero Can I close this?

**Comment by deviantfero** [comment]
Yeah, have you seen some better results?
