### ISSUE TITLE
Installer doesn't install xsltproc on Debian

### ISSUE THREAD

**Issue by jlnxr** [deviantfero/wpgtk#13]
The installer is supposed to take care of dependencies itself on Debian, Ubuntu and Arch, but on Debian the installer does not install xsltproc and the application will not install without it. After installing xsltproc manually it installs and functions properly.

**Comment by deviantfero** [comment]
is that the name of the package?

**Comment by jlnxr** [comment]
Yep, that's the one. You have it in the installation session under dependencies (sudo apt-get install feh python3-gi python-gobject python-pip python-imaging xsltproc && pip install Pillow) but where as the rest of those packages are automatically installed by the installer, xsltproc isn't.

**Comment by deviantfero** [comment]
it's done, could you please confirm that it works? so i can close this issue, thanks for your help!
