### ISSUE TITLE
Chromium tabs border

### ISSUE THREAD

**Issue by charconstpointer** [deviantfero/wpgtk#131]
so tabs on chromium have this weird light border color, could you please somehow fix this?
the only solution for now that i know of is to change system appearance to for example Matcha-aliz and then to FlatColor, but i have to repeat the process each time i run chromium

![20190131-233913_551x44_screenshot](https://user-images.githubusercontent.com/35968924/52090475-c5d4af80-25b1-11e9-8166-f0604151a2fc.png)

**Comment by deviantfero** [comment]
hi, I will look into this, but I can't promise anything, anyway, the proper place for this issue would be:
https://github.com/deviantfero/wpgtk-templates

**Comment by JackyFWong** [comment]
I use Chromium as well, and this issue has stumped me. One of my themes has no border, but my primary theme has a border. Unless I'm blind, the first has no border, and the second has one.
![image](https://user-images.githubusercontent.com/32987161/56531165-8cad3b00-6521-11e9-9b9a-ec9d74cd381c.png)
![image](https://user-images.githubusercontent.com/32987161/56531239-afd7ea80-6521-11e9-843a-467416305350.png)

I think Chromium uses GTK 2.0 when you select to use the GTK+ theme in the settings menu (I can't find where Chromium pulls data from GTK 3.0 or 3.2). Here are my colors in my `~/.themes/FlatColor/gtk-2.0/gtkrc`, following the order of the screenshots above.

```
gtk-color-scheme = "bg_color:#17344a
color0:#0c1924
color1:#be3422
color2:#2a3940
color3:#d0a99a
color4:#324448
color5:#8c282b
color6:#a83922
color7:#904d30
color8:#17344a
color9:#ea341b
color10:#304b59
color11:#e1c3a8
color12:#365c66
color13:#c3272b
color14:#e7411d
color15:#e77d4e
text_color:#e77d4e
selected_bg_color:#b39c86
selected_fg_color:#e77d4e
tooltip_bg_color:#17344a
tooltip_fg_color:#e77d4e
titlebar_bg_color:#17344a
titlebar_fg_color:#e77d4e
menu_bg_color:#17344a
menu_fg_color:#e77d4e
link_color:#b39c86"
```

```
gtk-color-scheme = "bg_color:#34343a
color0:#1d1d20
color1:#a66684
color2:#69637d
color3:#6981a7
color4:#4274a9
color5:#ba79ad
color6:#79a1bf
color7:#bedbf5
color8:#34343a
color9:#e16fa5
color10:#796da9
color11:#739ee3
color12:#4391e2
color13:#fe85e4
color14:#85cdff
color15:#f1ffff
text_color:#f1ffff
selected_bg_color:#5c7eb5
selected_fg_color:#f1ffff
tooltip_bg_color:#34343a
tooltip_fg_color:#f1ffff
titlebar_bg_color:#34343a
titlebar_fg_color:#f1ffff
menu_bg_color:#34343a
menu_fg_color:#f1ffff
link_color:#5c7eb5"
```

The `.base` file looks like this:
```
gtk-color-scheme = "bg_color:#<COLOR8>
color0:#<COLOR0>
color1:#<COLOR1>
color2:#<COLOR2>
color3:#<COLOR3>
color4:#<COLOR4>
color5:#<COLOR5>
color6:#<COLOR6>
color7:#<COLOR7>
color8:#<COLOR8>
color9:#<COLOR9>
color10:#<COLOR10>
color11:#<COLOR11>
color12:#<COLOR12>
color13:#<COLOR13>
color14:#<COLOR14>
color15:#<COLOR15>
text_color:#<COLOR15>
selected_bg_color:#<COLORACT>
selected_fg_color:#<COLOR15>
tooltip_bg_color:#<COLOR8>
tooltip_fg_color:#<COLOR15>
titlebar_bg_color:#<COLOR8>
titlebar_fg_color:#<COLOR15>
menu_bg_color:#<COLOR8>
menu_fg_color:#<COLOR15>
link_color:#<COLORACT>"
```

Another thing, I used GIMP to try to find the color of the border in the second color scheme. I got `#616164`. However, that color is nowhere to be found in the `gtkrc` file of the corresponding color scheme.

I will continue to look into this. In the meantime, maybe try changing the wallpaper or the color scheme?

**Comment by deviantfero** [comment]
for now I've achieved this, I plan to keep working on this. take a look

![image](https://i.imgur.com/2YrN6ER.png)
![image2](https://i.imgur.com/I28lf6q.png)
