### ISSUE TITLE
Less intrusive way of keeping templates

### ISSUE THREAD

**Issue by aleprovencio** [deviantfero/wpgtk#132]
Hello,
I'm coming from `pywal` and used to like the fact that its templates were only used to generate colors, so the config file (ie: `.config/rofi/config`) should only have a line including the generated color file (ie: `rofi.theme: ~/.cache/wal/colors-rofi-dark.rasi`).

IMHO, this seems a better way to keep my dotfiles, but maybe you have a reason for not making `wpgtk` that way.

**Comment by deviantfero** [comment]
To support things that can't include external files easily, such as i3 or
the iconset, it is not intrusive at all if you build your own templates,
which is definetly an option.

**Comment by aleprovencio** [comment]
Yeah I see your point. I understand that apps which can't support sourcing other files would benefit from that, but `i3` config is still able to set its colors from `Xresources`. The logic is, the config file stays where it is and gets the colors from somewhere else; whereas on `wpgtk`'s way all the confs go on template file itself, which is what "bothers" me.

Is there something we can do in order to go over `pywal`'s direction or is it the trade-off we have to take in order to address particular advantages of `wpgtk` over `pywal`?

**Comment by deviantfero** [comment]
You can still use pywal's template system in wpgtk, just place it under `.config/wal/templates`, and all of those templates are then exported onto `.config/wpg/formats`, from there you can use them as you normally would, symlink them as you like, include them in whatever files you want, in fact by default every available template on pywal is exported to that directory, so if you prefer to use pywal's way there's nothing stopping you from doing it, while leveraging the advantages of wpgtk (color scheme editing, GTK+ support, icon set support).

I wont change the template system in `wpgtk`, it does the linking for you and that's the point of it.

But if you're interested in changes to the template system you might be pleased to know that while the intrusion stays, the format is changing to be just like pywal's, with the advantage of user defined keywords (that you already have in wpgtk's templates), you can see progress here: #125

**Comment by aleprovencio** [comment]
Thanks a lot for you through explanation, that was really clarifying!

I guess I previously understood the `wpgtk`'s template system, but what felt strange was the fact that updates on config file that do not even have anything to do with colors (i.e. a new `for_window` rule on `i3`), should still be done on the template instead of the config file itself. It's just a different way of working and keeping your dots. 

I did not know that I could use `wpgtk` and `pywal` together that way, this integration just got me in.

BTW your app is awesome, thanks a lot for your work.

You can close the issue if you want to.

**Comment by deviantfero** [comment]
Thanks for commenting yes, there are `default` templates that I provide which include some other defaults that I use in my machine, but you're not forced to use them, they're just defaults that I find convenient, glad you enjoy it

keep an eye for updates and customize away!
