### ISSUE TITLE
Termite colors not being applied 

### ISSUE THREAD

**Issue by JackyFWong** [deviantfero/wpgtk#133]
Hello, I apologize in advance if I'm missing something obvious.
I'm using Termite and I'm trying to set the colors for it via wpgtk. I've already done [this](https://github.com/deviantfero/wpgtk/wiki/Colorschemes#restore-on-terminals) but that flashes the old colors I had with pywal before I switched to wpgtk.

I've added a template for termite, and I think it's being applied correctly, as the hex values in the wpgtk GUI are the same as that in my termite .config.

Is it possible to avoid the flashing of colors when I open a new terminal?

**Comment by deviantfero** [comment]
I've not used termite in a long time, if you are loading the colors onto a configuration file via wpgtk's templates I can think of two things that might be wrong:

1. you still have (cat ~/.cache/sequences &) around there in your .[shell]rc
2. because you're using a `wpgtk` template, you might not need `(cat ~/.config/wpg/sequences &)` at all.

please let me know if you were missing any of these considerations or if the problem lies elsewhere

**Comment by JackyFWong** [comment]
I did have the `cat ~/.cache/sequences &)` in my .zshrc, I completely glossed over that. However, now the color Termite flashes is a light gray one (not the old colors from `pywal`), regardless if I change the wallpaper via `wpgtk`.

If I remove `(cat ~/.config/wpg/sequences &)` from my .zshrc, the color does not flash back to what `wpgtk` set (it stays gray). I'll keep looking; my dotfiles are a mess, which is probably why this is happening.

**Comment by JackyFWong** [comment]
I just tried removing the `termite` template and keeping the `(cat ~/.config/wpg/sequences &)`, but `termite` still flashes colors.

I have a question: where does `wpgtk` edit the colors for, say `termite`? I've included a screenshot of my `wpgtk` colors and my `~/.config/termite/config` but the colors are not the same. You can see, however, that the colors for the `termite` and `wpgtk` are "correct" (aside from the flashing still occurring when opening `termite`).
![screenshot_2019-02-05_10-06-14](https://user-images.githubusercontent.com/32987161/52282273-0cb60280-292e-11e9-8260-865e02e62518.png)

**Comment by deviantfero** [comment]
if you're still having that issue, you can try to add `~/.config/termite/config` as a template to `wpgtk` using the UI tab `Templates`, or the command: `wpg -xa ~/.config/termite/config`, then you can go to the `Templates` tab where you can add keywords like the ones detailed here:

https://github.com/deviantfero/wpgtk/wiki/Templates

this will replace the keywords that you place and automatically copy them over to the original location each time you change your colorscheme, try that and maybe you can improve the situation.

**Comment by JackyFWong** [comment]
I think I've figured it out. My `termite` config has a line where I set the background color: `background = rgba(63, 63, 63, 0.8)`. Removing this from my template, my terminal window is set correctly immediately, I'm assuming because of `(cat ~/.config/wpg/sequences &)`.

Now, I used the `background = rgba(63, 63, 63, 0.8)` in order to set a transparency effect. Is there any way I can turn, for example, `<COLOR0>` to RGB values so I can continue to have transparency, or is that something I have to configure elsewhere?

**Comment by deviantfero** [comment]
hi @JackyFWong , sorry for taking so long, the new update does allow you to do that, check #125 for more details.

tho you will have to update your template files, they're the same as pywal now, so you could do `{color8.rgba}`, adjusting your alpha in the configuration tab of `wpgtk` for the desired value.

I'll keep this issue open just in case, please let me know if it worked

**Comment by JackyFWong** [comment]
Hi, I recently had time to update `wpgtk` and the templates. It works great now! Fantastic update.

**Comment by deviantfero** [comment]
glad to hear you liked it!
