### ISSUE TITLE
i3wm always late

### ISSUE THREAD

**Issue by Araly** [deviantfero/wpgtk#134]
I have a few commands I use everytime I start (and restart) i3wm.

`wpg -a ~/Pictures/wallpapers/*`
`wpg -A $(wpg -l)`
`wpg -m`

That changes the colors in a lot of places, termite, gtk, rofi, i3wm. But for some reason i3wm is always behind. I suspect it's because it's the only one using Xresources.

So I think everything gets updated, except i3wm that reads the old Xresources on the restart, before wpg has any chance of changing it. So the flow would be

- i3wm reads and imports Xresources colors
- wpg changes wallpaper and colorscheme and exports to Xresources
- gtk, termite, rofi ... are reloaded, or fetch the new colors

Do you think there is a way to but the first item there as the last item, or any other way ?

Or should I go with having seperate commands to restart i3wm and change the colorscheme ?

**Comment by deviantfero** [comment]
hi there, are you using the template I provide? or are you just using the `.Xresources`?
what version of `wpgtk` are you on?

**Comment by deviantfero** [comment]
done, please update to version `6.0.1`, you might have to update your templates if you're coming from a version lower than `6.0.0` tho

**Comment by Araly** [comment]
I was on AUR version of wpgtk, 5.8.7. I removed that and worked on the pip version instead.

I'm using the icon, gtk and rofi templates. I tried using the i3wm template but it nuked all my config, so I rolledback on an backup of the `~/.config/i3/config` file, and looked at how it worked. It set colors from resources, and resources happened to be .Xresources, which seemed to be handled by wpgtk. but it didn't, for some reason, so I removed that file just to see what happens and it worked, but in the "i3 always late" kind of way.

First test, calling the
`wpg -a ~/Pictures/wallpapers/*`
`wpg -A $(wpg -l)`
`wpg -m`
commands change the terminal colors and i3, but not rofi, gtk and icons. After running
`wpg-install.sh -igr`
those now work too. I didn't try the i3wm template as it now works well. Here's the output for a usual `wpg -m` command:
```
$ wpg -m
[i] image         Using image AMTswNh.png.
[i] theme         Set theme to _home_araly__config_wpg_wallpapers_AMTswNh_png_dark_wal__1.1.0.json.
[i] colors        Found cached colorscheme.
[i] sequences     Set terminal colors.
[i] export        Exported all files.
[i] export        Exported all user files.
[i] color         wrote: icon-step1
[i] color         wrote: gtk2
[i] color         wrote: gtk3.0
[i] color         wrote: gtk3.20
[i] color         wrote: rofi
xrdb: No such file or directory
xrdb: can't open file '/home/araly/.Xresources'
[i] wallpaper     Set the new wallpaper.
xrdb: No such file or directory
xrdb: can't open file '/home/araly/.Xresources'

```

It complains about ~/.Xresources not existing, and I can confirm it doesn't exist. Everything seems to work quite well though at first glance.

Thanks for the quick fix, I didn't expect it to be so quick ^^

**Comment by deviantfero** [comment]
hi @Araly, sorry for the inconvenience the new version caused you, I've also included the flag `--update` to update old `.base` files that you might have, you can read more about it on the wiki in the template section, regarding the `.Xresources`, you could just create an empty file, it's just a way for you to override colors without touching `wpgtk`, this is mostly for consoles and programs that draw from `xrdb` though.
