### ISSUE TITLE
Using Rofi with WPGTK spits out errors

### ISSUE THREAD

**Issue by igniscyan** [deviantfero/wpgtk#135]
`The following errors were detected while starting Rofi:
Error while parsing theme:
*{ background: {color0}; } 
`

and this repeats for 12 more lines of errors,all similar and relating to color. 

I am getting this error after using wpg_install.sh -r to install the default rofi config that is supposed to work with WPGTK

**Comment by igniscyan** [comment]
Follow up: I figured out the issue with Rofi, and I feel like this confusion was caused primarily by how templates are explained in the docs right now. I'd be willing to write a more thorough/concise guide on how templates work if I'd be permitted. I have a few questions still (changes being overwritten if not saved to the template, keywords, etc), but once I figure those out I definitely think the wiki on templates could be a little more thorough and provide more explicit examples.

**Comment by veekdot** [comment]
How did you even get wpgtk to work with .rasi files? I have trouble even making .rasi.base templates to apply the changes to the .rasi files #137

**Comment by deviantfero** [comment]
by all means please help me out with that, I'm definetly not that good with writing, if anyone has a better idea of how to document it, even if referencing `pywal`'s own docs (because they share the same format) it would be great.

**Comment by igniscyan** [comment]
Sorry, never saw that you replied! Is it okay if I still write a better guide to templates?

**Comment by igniscyan** [comment]
> by all means please help me out with that, I'm definetly not that good with writing, if anyone has a better idea of how to document it, even if referencing `pywal`'s own docs (because they share the same format) it would be great.

Sorry, I never saw you replied to this! How do I go about making contributions to the Wiki? I see I can clone it locally, but not exactly sure how/if I can create PRs for it.

**Comment by deviantfero** [comment]
I have set wiki as editable for anyone, please use this for good :+1:
