### ISSUE TITLE
Option to blur wallpaper

### ISSUE THREAD

**Issue by mattyrc** [deviantfero/wpgtk#139]
I think it would be nice to have an option to blur the wallpaper after the theme has been set. Currently I am running a simple bash script that i've created that uses ImageMagic to copy and blur the theme image and then nitrogen to set the converted wallpaper. Although the script works fine, It would be neat to be able to do this from wpg with a flag and/or a gui toggle option.

Also just wanted to say thanks for wpg!

**Comment by deviantfero** [comment]
hi, glad you enjoy it, for the time being this is out of scope for `wpgtk`, the software does provide the convenience of being able to call scripts after a wallpaper has been set, so how you use that is up to you
