### ISSUE TITLE
rofi theme not updating

### ISSUE THREAD

**Issue by CodeAndGin** [deviantfero/wpgtk#141]
So i have rofi's theme set to the one wal creates at "~/.cache/wal/colors-rofi-dark.rasi" when I run wal. I would have thought that because this used wal as the backend it would update this theme when ran, but rofi seems to stick to its colours.

Now I don't really mind having to run this and then wal to get both gtk and rofi matching, because it works, I'm just curious why the theme doesn't get updated.

**Comment by deviantfero** [comment]
It does, but it's under a different folder, try ~/.config/wpg/formats, it's
inside that folder I believe, please let me know of it's not working

**Comment by CodeAndGin** [comment]
Ah, cool, it works perfectly now, cheers. Dunno why i didn't think to look under the wpg folders.

**Comment by niksingh710** [comment]
I am trying to create a template for rofi but wpg does not generate any file 
i created file with name `test.base` 
```
* {
    bg:    {background};
}
```
wbg is not generating any template for files having syntax like this.
any solution for this?

**Comment by niksingh710** [comment]
nvm had to wrap with {{}}
