### ISSUE TITLE
wpg -s breaks GNOME's looks on HiDPI (2K) screen

### ISSUE THREAD

**Issue by cobalamin** [deviantfero/wpgtk#143]
I just tried this cool tool out for the first time :) For some reason – and I'm not sure it's due to my 2K screen, but it looks like a hidpi problem – it really breaks the text and titlebar sizes in GNOME, in multiple ways. I'm using Arch.

This is what e.g. the Tweaks window looks before setting:
![Tweaks at first](https://user-images.githubusercontent.com/669103/55280781-4bfb4100-532a-11e9-93eb-4b9ab02ac2c4.png)

Setting once does nothing to existing windows for some reason:
![Setting once does nothing](https://user-images.githubusercontent.com/669103/55280780-4bfb4100-532a-11e9-88e9-9381a68263bf.png)

Setting twice does this (same resolution in the screenshot!):
![Setting twice does something but it's wrong](https://user-images.githubusercontent.com/669103/55280779-4bfb4100-532a-11e9-9c46-26e7eb4ce305.png)

Highlighting further problems, e.g. see Firefox's title bar:
![Highlighting the problems](https://user-images.githubusercontent.com/669103/55280778-4b62aa80-532a-11e9-88ae-9d650ceaca0a.png)

**Comment by deviantfero** [comment]
Hi there, glad to see you're enjoying `wpgtk` and I'm sorry about the inconveniences, I'm guessing this has something to do with the way I do live reload of GTK+ themes, so I would ask of you that you disable GTK+ live reload from the UI (in the Options tab), and try to set a wallpaper, let me know if it's still throwing off your desktop dpi.

**Comment by cobalamin** [comment]
Nope, it doesn't after deactivating. Seems like that is indeed the culprit. :)

Sorry if I missed something in the wiki, but how can I manually (without live-reloading) generate and set the GTK scheme it's trying to set?

**Comment by deviantfero** [comment]
Yeah, maybe it's not in the wiki, but one way to manually reload the theme is to set it to another theme and then set it back to FlatColor, this is due to the fact that we use `xsettingsd` to reload the theme, and it might be conflicting with gnome's own `gnome-settings-daemon`, you can also just re-open the programs individually and they should show the new colors.

**Comment by deviantfero** [comment]
Did you manage to achieve a satisfactory setup? how are you dealing with reloading the theme? 
If you haven't yet, you might find some help here #112, in this issue it is detailed how to do it with the gnome-settings-daemon directly, maybe that won't give you an issue, please re-open this issue if you still have an issue using `wpgtk`
