### ISSUE TITLE
wpg --backend [BACKEND] Help Not Explicit Enough

### ISSUE THREAD

**Issue by Mootikins** [deviantfero/wpgtk#144]
Trying to move to wpgtk now that pywal no longer supports oomox, and my general setup uses ranger's custom commands to make setting wallpapers as easy as a few keystrokes. My bindings are as follows:

```
map gww shell wal -i %s
map gwlw shell wal -i %s -l
map gwc shell wal -i %s --backend colorthief
map gwlc shell wal -i %s --backend colorthief -l
map gwz shell wal -i %s --backend colorz
map gwlz shell wal -i %s --backend colorz -l
map gws shell wal -i %s --backend schemer2
map gwls shell wal -i %s --backend schemer2 -l
map gwh shell wal -i %s --backend haishoku
map gwlh shell wal -i %s --backend haishoku -l
```

I've been trying to get this to work with wpgtk, but the `--backend` flag seems to do nothing. Running `wpg --backend [backend]` on its own also just opens the gui, which is not what I want.

The documentation should be more explicit on how to use this, since the current help text on it is not giving the information I think it should.

**Comment by deviantfero** [comment]
the --backend flag is waiting for another flags to actually take action, what you do when you provide no other flag is simply override the backend set in the config file and open the UI.

you need to combine this flag with the rest of the other flags just as you do with `wal`, so let's say you want to set a wallpaper and generate it's color scheme with `haishoku`, you would actually do:

```
wpg --backend haishoku -s %s

# or maybe a light theme
wpg --backend haishoku -s %s --light
```

where %s is the path to an image I suppose

keep in mind however, that using `wpgtk` this way, you're not taking advantage of the feature to be able to edit color schemes, re-arrange them and such, to do that you would need to add the image first with `wpg -a /path/to/image`, so while the use case you're presenting is able to be done correctly in `wpgtk`, it is not the main idea for it to be used like that.

**Comment by Mootikins** [comment]
When I try to do it like you described, if the image is not present in the GUI, it just says the image has not been found. I try adding it with `wpg --backend [backend] -a [filename]` and it just uses my default regardless of the backend flag. Then if I try to set it with a specific backend (`wpg --backend [backend] -s [filename]`) it just applies the colorscheme generated by the default backend.

**Comment by Mootikins** [comment]
I have gotten the functionality I wanted to work, but it is kind of roundabout since the `--backend` flag is not performing as expected.

I am opting instead to just run `sed` on the config file, replacing my default backend with the one I want to use for the single ranger command, then replacing it again when I have generated the colorscheme.

I will leave the issue open until the `--backend` flag works as described.

**Comment by deviantfero** [comment]
will submit a fix soon, thanks for reporting

**Comment by deviantfero** [comment]
this has been solved in the newest `6.0.4` release, please test and let me know if it worked for you.

**Comment by Mootikins** [comment]
Getting error:
```
Traceback (most recent call last):
  File "/usr/bin/wpg", line 11, in <module>
    load_entry_point('wpgtk==6.0.4', 'console_scripts', 'wpg')()
  File "/usr/lib/python3.7/site-packages/wpgtk/__main__.py", line 303, in main
    process_args(args)
  File "/usr/lib/python3.7/site-packages/wpgtk/__main__.py", line 186, in process_args
    themer.set_theme(args.s[0], args.s[0], args.r)
  File "/usr/lib/python3.7/site-packages/wpgtk/data/themer.py", line 39, in set_theme
    pywal.sequences.send(colors, WPG_DIR, vte_fix=use_vte)
TypeError: send() got an unexpected keyword argument 'vte_fix'
```

**Comment by deviantfero** [comment]
oh, yeah I forgot to upload to `pip`, thanks for the heads up, seems like this is being caused by an outdated pywal, please update and let me know if it works

**Comment by Mootikins** [comment]
Tried to update pywal, both from `pip` as well as a fresh clone of the repo, to no avail.

**Comment by deviantfero** [comment]
weird I can't seem to reproduce it, could you please tell me the command you're trying to run? and what do you mean by `edit it` every time you update, currently the setting is stored in your settings `.config/wpg/wpg.conf`, there you can enable and disable the vte fix, but I can't seem to reproduce your isue

**Comment by Mootikins** [comment]
That seems to be the issue, returns `3.1.0`.

**Comment by deviantfero** [comment]
yep, this is usually common when you install a package with more than one package manager, or if you have more than one environment, thanks for sticking out till the end, hope you enjoy `wpgtk`
