### ISSUE TITLE
Make it possible to keep both light and dark themes

### ISSUE THREAD

**Issue by alizeegagnon** [deviantfero/wpgtk#145]
Currently, switching from light theme to dark theme and restarting the app overwrites all the light schemes in wpg/schemes/ . If we want to keep a custom light scheme for a wallpaper while having a dark scheme for another wallpaper, we need to back up the custom scheme ourselves. I feel  this is an issue, since I had no warning that my custom scheme was getting deleted, and I spent a bit of time on it.

**Comment by alizeegagnon** [comment]
After looking more carefully, I think the problem was caused by moving my wallpaper's locations, trying to open them and failing, and then updating the symbolic links.

**Comment by deviantfero** [comment]
yep I tried to reproduce but couldn't, did you open an issue about getting my wallpapers?, I cant seem to find it, anyway, your best bet are my reddit posts in /r/unixporn, I'll share some albums here:

https://imgur.com/a/uQeyhsJ
https://imgur.com/a/2W1mQjN

I almost always tend to keep the same wallpapers, so there are some repeats here and there, if you have no issue with `wpgtk` anymore feel free to close this issue.
