### ISSUE TITLE
Add .desktop file for dmenu / rofi.

### ISSUE THREAD

**Issue by ellisgeek** [deviantfero/wpgtk#147]
It would be great to have a .desktop file for wpgtk so that it can easily be launched from gnome or from dmenu / rofi drun.

**Comment by ellisgeek** [comment]
Here is a .desktop file and updated PKGBUILD that I put together for wpgtk.
https://gist.github.com/ellisgeek/d0ec9b5bc0693a44930c7a2748c023d3

**Comment by deviantfero** [comment]
this has been added in `6.0.6`
