### ISSUE TITLE
Murrine GTK Engine should be a dependency for FlatColor

### ISSUE THREAD

**Issue by kingkobra87** [deviantfero/wpgtk#148]
It might be easy to overlook since Murrine is so common, but I noticed the issue today after doing a fresh install of Arch Linux. Long story short, FlatColor wasn't looking very flat, so I analyzed the code to find references of which GTK engine was being used. Installing the `gtk-engine-murrine` package fixed the issue.

**Comment by deviantfero** [comment]
Hi, I will add it as an optional dependency to the AUR package and the documentation, but not as hard dependency, since it's not really breaking the functionality of `wpgtk`
