### ISSUE TITLE
Thunar's colours & icons do not change

### ISSUE THREAD

**Issue by dhsdshdhk** [deviantfero/wpgtk#149]
I'm using the FlatColor GTK theme and flat icons, but the GTK colours are stuck in a purple scheme, which was the first image I tried. I have tried a bunch other images, and they change the terminal colour as expected, but don't change the GTK theme. Icons also do not change immediately, only after some minutes.
Any ideas?

**Comment by deviantfero** [comment]
How did you install the GTK theme?

**Comment by dhsdshdhk** [comment]
I downloaded the wpgtk-templates repository and put FlatColor in ~/.themes and flattrcolor in ~/.icons, and selected them with Lxappearance.

**Comment by deviantfero** [comment]
Use wpg-install.sh to do it, this is installed automatically with wpgtk

Use wpg-install.sh -h for more info and read the templates section of the
wiki

**Comment by dhsdshdhk** [comment]
That fixed it!
While we're here, there's another other minor issue. When I use sudo wpg -a image.png && sudo wpg -s image.png to add and set that image, it doesn't work the first time, only the second time.

What could be causing it?

> ➜  wallpapers-master sudo wpg -a Watersport.png && sudo wpg -s Watersport.png 
> [i] image         Using image Watersport.png.
> [i] colors        Generating a colorscheme.
> [i] colors        Using wal backend.
> [i] colors        Generation complete.
> Traceback (most recent call last):
>   File "/usr/local/bin/wpg", line 9, in <module>
>     load_entry_point('wpgtk==6.0.5', 'console_scripts', 'wpg')()
>   File "/usr/local/lib/python3.5/dist-packages/wpgtk/__main__.py", line 302, in main
>     process_args(args)
>   File "/usr/local/lib/python3.5/dist-packages/wpgtk/__main__.py", line 218, in process_args
>     add_action(glob.glob(x)[0])
>   File "/usr/local/lib/python3.5/dist-packages/wpgtk/data/themer.py", line 25, in create_theme
>     return color.get_color_list(filename)
>   File "/usr/local/lib/python3.5/dist-packages/wpgtk/data/color.py", line 51, in get_color_list
>     color_list = auto_adjust_colors(color_list)
>   File "/usr/local/lib/python3.5/dist-packages/wpgtk/data/color.py", line 149, in auto_adjust_colors
>     clist = smart_sort(clist)
>   File "/usr/local/lib/python3.5/dist-packages/wpgtk/data/color.py", line 128, in smart_sort
>     current_cd = sorted_by_color[i][0]
> IndexError: list index out of range
> ➜  wallpapers-master sudo wpg -a Watersport.png && sudo wpg -s Watersport.png
> [i] image         Using image Watersport.png.
> [i] theme         Set theme to _home_anna__config_wpg_wallpapers_Watersport_png_dark_wal__1.1.0.json.
> [i] colors        Found cached colorscheme.
> [i] image         Using image Watersport.png.
> [i] theme         Set theme to _home_anna__config_wpg_wallpapers_Watersport_png_dark_wal__1.1.0.json.
> [i] colors        Found cached colorscheme.
> [i] sequences     Set terminal colors.
> [i] export        Exported all files.
> [i] export        Exported all user files.
> [i] color         wrote: icon-step1
> [i] color         wrote: gtk2
> [i] color         wrote: gtk3.20
> [i] color         wrote: gtk3.0
> [i] wallpaper     Set the new wallpaper.
> 
>

**Comment by deviantfero** [comment]
Don't use sudo, try without sudo and I'll try to reproduce

**Comment by dhsdshdhk** [comment]
It doesn't work without sudo.
PermissionError: [Errno 13] Permission denied: '/mnt/Wallpapers/5cm per second.png' -> '/home/anna/.config/wpg/wallpapers/.tmp.link'

**Comment by deviantfero** [comment]
Why are your wallpapers under /mnt? Try placing your images in your home
dir and adding them from there, you do not have appropriate permissions on
/mnt/Wallpapers

**Comment by dhsdshdhk** [comment]
I get the same error anywhere.

PermissionError: [Errno 13] Permission denied: '/home/anna/Desktop/1555571360261.jpg' -> '/home/anna/.config/wpg/wallpapers/.tmp.link'

**Comment by deviantfero** [comment]
There's something wrong with your permissions, as a quick dirty fix just do

chown anna:users -R /home/anna/.config
chown Anna:users -R /home/anna/Wallpapers

Also get the output of ls -la /home/anna

Is anna your user?

**Comment by dhsdshdhk** [comment]
Yes it is. Also, that worked, thanks!!
