### ISSUE TITLE
blueberry gtk buttons visibility issue

### ISSUE THREAD

**Issue by cj360** [deviantfero/wpgtk#15]
With wpg's gtk theme & openbox border applied the blueberry package/program (https://www.archlinux.org/packages/community/any/blueberry) the on/off buttons are impossible to tell which state they're in. Screengrab :http://i.imgur.com/vGBga2h.png
And I'm on arch linux btw.

**Comment by deviantfero** [comment]
hi, thanks for reporting this, i've been looking for someone to help me out with the gtk3 theme for some while now, but i'll get right to it, so exepct a new update in the comming weeks

**Comment by deviantfero** [comment]
hi, good news, that issue has been fixed in this commit, so please re-install from aur, or clone from github, and you're set, please post a screenshot to see if it worked

**Comment by cj360** [comment]
Oh snap that was quick! http://imgur.com/CQ7kn0H
