### ISSUE TITLE
No "focus" color in FlatColor theme for dialogs

### ISSUE THREAD

**Issue by impankratov** [deviantfero/wpgtk#150]
Taken from vscode, when you try to close the editor tab with unsaved changes:

![2019-05-02-171721_556x164_scrot](https://user-images.githubusercontent.com/6479407/57074731-3056d200-6cfe-11e9-94a3-8e7c2ef4d16a.png)

There's no way to tell which button is focused.
Is there a way to fix this?

**Comment by deviantfero** [comment]
yep, I need to edit the GTK+ theme to have a `button:focus` I'll leave this open till I fix it

**Comment by impankratov** [comment]
@deviantfero I would help with this, but I don't have any experience with gtk themes. If I understood correctly, something needs to be changed here - https://github.com/deviantfero/wpgtk-templates/tree/master/FlatColor right?

**Comment by deviantfero** [comment]
this has been fixed in (this PR)[https://github.com/deviantfero/wpgtk-templates/pull/8], please re-install the GTK theme with `wpg-install.sh` to see the changes
