### ISSUE TITLE
key does not exist

### ISSUE THREAD

**Issue by GeoDerp** [deviantfero/wpgtk#152]
## Disclaimer 
Alright, just a disclaimer that I haven't touched wpgtk in a while *(and only just got back on it)* so these errors may be completely my fault.

## Error 
```shell
[e] color       '\n#       dwt enabled\n#       tap enabled\n#       natural_scroll enabled\n#       middle_emulation enabled\n#   ' in /home/geo/.config/wpg/templates/config_sway_config - key does not exist
[e] color         '\n    border' in /home/geo/.config/wpg/templates/config_waybar_style.css - key does not exist
[e] color         '\n    "layer"' in /home/geo/.config/wpg/templates/config_waybar_config - key does not exist
```
Pretty much it won't change the colours in the config file at all. 

## Details
**OS**: Fedora 30
**WM**: sway 
**wpgtk Version**: current version: 6.0.6
**Template Files**: Custom 

## Other Notes 
**Get this on startup:** (but I believe that's a new warning, so possibly not related):
```shell
(wpg:27760): dbind-WARNING **: 23:37:50.846: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```
**output when changing wallpaper: **
```shell
[i] wallpaper     Set the new wallpaper.
[i] files         created backup /home/geo/.config/waybar/config.bak
[i] files         added config_waybar_config.base @ /home/geo/.config/waybar/config
[i] files         created backup /home/geo/.config/waybar/style.css.bak
[i] files         added config_waybar_style.css.base @ /home/geo/.config/waybar/style.css
[i] image         Using image MIT-Inhibitor-Model_Credit_MIT-News.jpeg.
[i] theme         Set theme to _home_geo__config_wpg_wallpapers_MIT-Inhibitor-Model_Credit_MIT-News_jpeg_dark_wal__1.1.0.json.
[i] colors        Found cached colorscheme.
[i] image         Using image MIT-Inhibitor-Model_Credit_MIT-News.jpeg.
[i] theme         Set theme to _home_geo__config_wpg_wallpapers_MIT-Inhibitor-Model_Credit_MIT-News_jpeg_dark_wal__1.1.0.json.
[i] colors        Found cached colorscheme.
[i] sequences     Set terminal colors.
[i] export        Exported all files.
[i] export        Exported all user files.
[e] color         icons - base file does not exists
[e] color         '\n#       dwt enabled\n#       tap enabled\n#       natural_scroll enabled\n#       middle_emulation enabled\n#   ' in /home/geo/.config/wpg/templates/config_sway_config - key does not exist
[e] color         '\n    border' in /home/geo/.config/wpg/templates/config_waybar_style.css - key does not exist
[e] color         '\n    "layer"' in /home/geo/.config/wpg/templates/config_waybar_config - key does not exist
[i] color         wrote: gtk3.0
[i] color         wrote: gtk2
[i] color         wrote: gtk3.20
```

## Files (https://paste.opensuse.org)
[config_sway_config](https://paste.opensuse.org/18859797)
[config_sway_config.base](https://paste.opensuse.org/6023485)
[config_waybar_config](https://paste.opensuse.org/40063099)
[config_waybar_config.base](https://paste.opensuse.org/88393615)

Thanks :)

**Comment by deviantfero** [comment]
hey @GeoDerp, glad you're back on `wpgtk`, and thanks for writing such a detailed report on this error you're getting.

since you are returning from a long absence, I think the issue is that you've not updated your templates appropriately, now you can read more on this here: https://github.com/deviantfero/wpgtk/pull/125 and here in the wiki: https://github.com/deviantfero/wpgtk/wiki/Templates#default-keywords

I've taken a look at your base files, and it seems all you need to do is to escape intentional braces with double braces `{ turns into {{ and } turns into }}`, as explained in both links I pasted here, please let me know if you need any help after you apply that fix to your base files, remember, you  just have to escape those braces which are intentional, please let me know how it goes.

**Comment by GeoDerp** [comment]
Thank you so much for the quick response. Sorry about my not so quick response. But thanks to you it WORKS !!!!! I used you linked files to understand what you meant with the {} and realise I used the double braces wrong (did it the other way around XD). THANKS, SO MUCH

**Comment by Sycorlax** [comment]
Hey there,

I'm experiencing a similar issue as described up. my base configuration file: [link](https://paste.opensuse.org/pastes/299b26fa4438).  and I'm unsure why it's not functioning correctly. The error message I'm getting is:

```
[e] color '\n\tmodi' in /home/guts/.config/wpg/templates/launchers_type-6_style-5.rasi - key does not exist
```

I've already checked the configuration, but I can't identify the problem. Any suggestions or insights would be greatly appreciated!
