### ISSUE TITLE
Reset button not working when wallpaper directory is symlinked, wallpaper deleted

### ISSUE THREAD

**Issue by jasperro** [deviantfero/wpgtk#155]
I have my wpg wallpapers configured that I have symlinked my wallpaper directory (~/Afbeeldingen/Achtergronden) to ~/.config/wpg/wallpapers. When I set the wallpaper it works fine, but if I then reset the wallpaper the log reads:
`[e] image         No valid image file found.
[i] theme         Set theme to tempus_warp.json.
[i] export        Exported json.` and my wallpaper is deleted. The wallpaper is symlinked to itself so a symlink loop is made. ~/.config/wpg/wallpapers/mariomoreno_1.jpg -> ~/Afbeeldingen/Achtergronden/mariomoreno_1.jpg -> ~/.config/wpg/wallpapers/mariomoreno_1.jpg

wpgtk version: `6.0.7`

**Comment by jasperro** [comment]
It looks like this is also the case even when the directory isn't symlinked. wpgtk symlinks the wallpaper to itself on reset, thus deleting it.

**Comment by deviantfero** [comment]
let me check on this, I've done resets to wallpapers before without files being deleted, I'll check it out, thaks for reporting

**Comment by deviantfero** [comment]
I've pushed the fix to master in https://github.com/deviantfero/wpgtk/commit/ca6f4108629935860a4c538c047ab7736f1cfc3c, could you test cloning from master and doing your workflow? that commit should do it, when I get your confirmation I'll release a new tag so you can install via pip or AUR.

basically I no longer re-add the file, I simply recreate the colorscheme

**Comment by jasperro** [comment]
It works perfectly now, thank you very much!
