### ISSUE TITLE
Css issues

### ISSUE THREAD

**Issue by koopa1338** [deviantfero/wpgtk#156]
Hey guys,
Im using wpgtk 6.0.8 with pywal 3.3.0 but the template system does have issues with css apperently :

[i] image         Using image halo.jpg.
[i] theme         Set theme to _home_koopa__config_wpg_wallpapers_halo_jpg_dark_wal__1.1.0.json.
[i] colors        Found cached colorscheme.
[i] sequences     Set terminal colors.
[i] export        Exported all files.
[i] export        Exported all user files.
[e] color         icons - base file does not exists
[i] color         wrote: config_kitty_diff.conf
[i] color         wrote: config_kitty_kitty.conf
[e] color         '\n\t--bgdark' in /home/koopa/.config/wpg/templates/dotfiles_startpage_style.css - key does not exist
[e] color         '\n  transition-duration' in /home/koopa/.config/wpg/templates/gnome-shell.gnome-shell.css - key does not exist
[e] color         /home/koopa/.config/wpg/templates/dunstrc - base file does not exist
[i] color         wrote: gtk3.0
[i] color         wrote: gtk2
[i] color         wrote: home_koopa_Xresources
[i] color         wrote: gtk3.20
[i] color         wrote: rofi
[i] wallpaper     Set the new wallpaper.

**Comment by deviantfero** [comment]
have you used double braces to escape regular braces in your template? see #152 for reference

**Comment by koopa1338** [comment]
Yes forgot some braces to escape...
