### ISSUE TITLE
gtk2/qt colors doesn't work with gtk theme files in .local/share/themes

### ISSUE THREAD

**Issue by dbeley** [deviantfero/wpgtk#157]
Hello,

It seems commit 1ba4ac34f4e8de589e07479cd47d6d3edd8b921e has broken the gtk2 and the qt (with QT_QPA_PLATFORMTHEME set to "gtk2") colors. 

On a fresh archlinux install, after launching `wpg -a PICTURE` and `wpg-install.sh -g` :

- lxappearance-gtk3 shows the colors for the FlatColor gtk theme
- lxappearance (gtk2 version) doesn't show the colors for the FlatColor gtk theme
- qt apps (Nextcloud or KeepassXC) use the FlatColor decoration, but the colors stays gray

(The issue only shows up on a fresh wpgtk install, as wpg-install.sh doesn't delete the ~/.themes folder if a prior version of the script has been launched.)

Making a symbolic link from `~/.local/share/themes` to `~/.themes `resolves the problem.

**Comment by deviantfero** [comment]
so this is a backwards compatibility issue rather than an actual bug right?, if you deleted the GTK2 theme from `~/.themes` and re-installed it, there would be no issue either, no?

**Comment by dbeley** [comment]
The issue appeared on a fresh install (so without any prior installation of wpg-install.sh and no `.themes` folder), so it seems the gtk2/qt theme can only be applied (at least with my configuration) if the FlatColor is in `.themes` and not in `.local/share/themes`.

I just made an issue in case someone has the same problem in the future, as the solution is pretty straightforward.

**Comment by deviantfero** [comment]
@dbeley, I've updated the install script to add this symlinks for gtk2 and openbox as `obconf` does not respect the standard either.
