### ISSUE TITLE
dunst reload issue

### ISSUE THREAD

**Issue by joshuah345** [deviantfero/wpgtk#158]
wpg has templates for all sorts of things including dunst, but everytime i set new colors, dunst gets killed and isnt relaunched by wpg. (i have no templates for dunst)

**Comment by deviantfero** [comment]
`notify-send` should reload dunst whenever it is called, what is your notification daemon?

**Comment by joshuah345** [comment]
isnt dunst the notification daemon?

and i know dunst doesn't get relaunched because i dont get a startup notification (i have it enabled in the dunst config)

**Comment by deviantfero** [comment]
https://github.com/dunst-project/dunst/issues/63

I don't think there's much I can do in this case, maybe I can add a switch to wpg to stop killing dunst, but it seems that you can alleviate this by using notify-send as this issue indicates

**Comment by GnikDroy** [comment]
> `notify-send` should reload dunst whenever it is called, what is your notification daemon?

The arch wiki seems to suggest to not rely upon the autostart behavior.
<https://wiki.archlinux.org/index.php/Dunst>
![scrot](https://user-images.githubusercontent.com/30725674/82317489-0e55ed80-99ee-11ea-84a4-fa2241c393a1.png)

**Comment by rahatzamancse** [comment]
As for now, what I am doing is using a post script with `dunst &` and adding it to wpgtk command in the settings.

**Comment by deviantfero** [comment]
I could relaunch dunst from wpgtk, I will probably do that
