### ISSUE TITLE
second instance of wpg launches after setting colors

### ISSUE THREAD

**Issue by joshuah345** [deviantfero/wpgtk#159]
whenever i set colors, a second instance of wpg launches within 60 seconds. the only difference is that the `set wallpaper` option is disabled in the new instance.

im using wpg 6.0.8 (from pip)

**Comment by deviantfero** [comment]
could you tell me how do you launch `wpg`?

**Comment by joshuah345** [comment]
i just use the command ``wpg`` or i just use rofi to do the same thing

**Comment by deviantfero** [comment]
try to launch from terminal and post the log here

**Comment by joshuah345** [comment]
``[i] theme_picker  current wallpaper: bloom2.jpg
[i] image         Using image [1;37mbloom2.jpg[0m.
[i] theme         Set theme to [1;37m_home_joshua__config_wpg_wallpapers_bloom2_jpg_dark_wal__1.1.0.json[0m.
[i] colors        Found cached colorscheme.
[i] image         Using image [1;37mbloom2.jpg[0m.
[i] theme         Set theme to [1;37m_home_joshua__config_wpg_wallpapers_bloom2_jpg_dark_wal__1.1.0.json[0m.
[i] colors        Found cached colorscheme.
[i] sequences     Set terminal colors.
[i] export        Exported all files.
[i] export        Exported all user files.
[e] color         icons - base file does not exists
[i] color         wrote: .Xresources
[i] color         wrote: tint2rc
[i] wallpaper     Set the new wallpaper.
[i] image         Using image [1;37mspacerecordsnwt.png[0m.
[i] theme         Set theme to [1;37m_home_joshua__config_wpg_wallpapers_spacerecordsnwt_png_dark_wal__1.1.0.json[0m.
[i] colors        Found cached colorscheme.
[i] image         Using image [1;37mspacerecordsnwt.png[0m.
[i] theme         Set theme to [1;37m_home_joshua__config_wpg_wallpapers_spacerecordsnwt_png_dark_wal__1.1.0.json[0m.
[i] colors        Found cached colorscheme.
[i] sequences     Set terminal colors.
[i] export        Exported all files.
[i] export        Exported all user files.
[e] color         icons - base file does not exists
[i] color         wrote: .Xresources
[i] color         wrote: tint2rc
[i] wallpaper     Set the new wallpaper.
[i] image         Using image [1;37mwp2672819.jpg[0m.
[i] theme         Set theme to [1;37m_home_joshua__config_wpg_wallpapers_wp2672819_jpg_dark_wal__1.1.0.json[0m.
[i] colors        Found cached colorscheme.
[i] image         Using image [1;37mwp2672819.jpg[0m.
[i] theme         Set theme to [1;37m_home_joshua__config_wpg_wallpapers_wp2672819_jpg_dark_wal__1.1.0.json[0m.
[i] colors        Found cached colorscheme.
[i] sequences     Set terminal colors.
[i] export        Exported all files.
[i] export        Exported all user files.
[e] color         icons - base file does not exists
[i] color         wrote: .Xresources
[i] color         wrote: tint2rc
[i] wallpaper     Set the new wallpaper.``
