### ISSUE TITLE
Everything is working except the terminal color scheme

### ISSUE THREAD

**Issue by androvix** [deviantfero/wpgtk#16]
I'm running on a fresh 64bit Ubuntu Mate 16.04 install. All of the things have changed except the terminal color schemes even when I use xterm.

**Comment by deviantfero** [comment]
Hi there, do you have any colors predefined in your current .Xresources?

**Comment by androvix** [comment]
Yeah I have the default for my system

**Comment by deviantfero** [comment]
could you please show it to me, you should have no colors predefined in your Xresources file. I predefine my background so it doesn't change with each colorscheme but that's about it.

**Comment by androvix** [comment]
Cant get to my machine but I havent touched anything relating to the xresources

**Comment by deviantfero** [comment]
I can't pinpoint the issue until i see your .Xresources, when you get home please do 
```sh
cat ~/.Xresources
```
your system may have predifined colors for your terminal, and this gets in the way of wpg.

**Comment by androvix** [comment]
When I run that command I get No such file or directory

**Comment by deviantfero** [comment]
could you run wpg in a terminal and show me the output when you click on "set" ?

**Comment by androvix** [comment]
:: not installed by AUR
:: Setting greenandclean.jpg as background
:: Done
BASE BRIGHTNESS: 151.5
FG: 62a052
BG: 3e6434
CHANGED::OPENBOX
NO OPENBOX INSTALL!
CHANGED::TINT2
CHANGED::GTK2
CHANGED::GTK3
CHANGED::GTK3.20
5b8b6e
CHANGED::ICONS
CURRENT GLYPH: 24352a
NO OPTIONAL FILES DETECTED::NOT CHANGED
SUCCESS
Done.

**Comment by deviantfero** [comment]
Hi thanks to the new update and `wal` integration into `wpgtk` you can simply run `(wpg -t &)` to reload the colorscheme into your terminal at startup of each terminal session, the advantage to this is that it supports most modern terminal emulators.
