### ISSUE TITLE
Rogue highlight colour in GTK theme

### ISSUE THREAD

**Issue by Hazza4569** [deviantfero/wpgtk#163]
With FlatColor applied my GTK applications use colours from my colour schemes as set with wpgtk, which is absolutely brilliant because I hated how difficult it was to get custom colour schemes in GTK.

However, no matter what theme I set, there is a lime green highlight colour in all of my GTK apps. This colour appears on the currently selected folder or file in nautilus, as the background cover of the ui element below the mouse in wpg, and as a thin line above the current tab in firefox. It's pretty much the dominant colour in my GTK apps besides the background, and it's not even a colour included in my theme.

I tried reinstalling FlatColor with wpg-install.sh, and even before applying my own theme the lime green colour is still there. I've tried looking through the gtk theme base files for hard coded colours and found a few greenish colours, but I tried setting them all to red and unfortunately nothing changed. Any idea where this colour is coming from?

**Comment by deviantfero** [comment]
could you post a screenshot? sorry I've not been responding lately I've been swamped with work

**Comment by cspack77** [comment]
I ran into this myself and discovered that the active/inactive color setting was set to random.
