### ISSUE TITLE
Terminal colours not persistent in URxvt

### ISSUE THREAD

**Issue by Moltenkore** [deviantfero/wpgtk#165]
When I set or restore a theme when URxvt is open, the theme and transparency applies fine however, if I go to open a new terminal the colour scheme is reset back to default for that terminal.

To sum up that explanation a bit clearer:
- Open URxvt or have a few windows open already
- Run wpg to apply theme
- Theme applies to all open URxvt windows
- Open new window, that window doesn't have the theme set

I'm running Manjaro I3 edition and I noticed that xsettingsd isn't installed by default, however it didn't seem to make much difference after installing and running it on startup.

**Comment by deviantfero** [comment]
Hi, do you have any colors defined in your `.Xresources`?

**Comment by Moltenkore** [comment]
Aha, that was the issue. I removed the colours from ``.Xresources`` and now it's fixed.
