### ISSUE TITLE
gnome-terminal cursor color same as text (foreground)?

### ISSUE THREAD

**Issue by bilaal-s** [deviantfero/wpgtk#166]
Hello! Thanks for this awesome tool, I can't go back to not using it!

I have a problem where the terminal cursor color is the same as the text as seen here:
![Screenshot from 2019-09-10 14-53-30](https://user-images.githubusercontent.com/25149538/64619953-e338ea00-d3da-11e9-9b8c-d8a9caf509f5.png)
I am not sure if the screenshot picked it up correctly because it fades the cursor when taking the screenshot but trust me, the foreground color of the text and the text itself are the same color making it impossible to see what is under the cursor.

Any help would be appreciated!

**Comment by deviantfero** [comment]
Hi there @bilaal-s, thanks for opening this issue, though I'm afraid you might have to change this from the gnome-terminal's settings, you can use the colors tab in there to set a custom `foreground` for your cursor.

I already tried this on my computer so I know it works, please let me know if it worked for you, try not to set the cursor text to pure white, try a grey-tone or something like that

**Comment by bilaal-s** [comment]
@deviantfero Awesome, that has worked thanks!
