### ISSUE TITLE
wpgtk not updating pywal formats

### ISSUE THREAD

**Issue by mehalter** [deviantfero/wpgtk#167]
I have some scripts that rely on the files in `~/.config/wpg/formats`, but when I change my theme using `wpg -s` these files aren't getting regenerated with the new scheme's colors. Am I missing a flag to regenerate these files?

**Comment by deviantfero** [comment]
what version of `wpgtk` are you using? I don't remember the exact release, but to preserve compatibility with scripts that use files from `pywal` I decided to place `pywal` formats in their original folder, that is: `~/.cache/wal`

there you should see all pywal formats updated with the colors that wpgtk provides.
