### ISSUE TITLE
Setting to only use 256color colors in themes

### ISSUE THREAD

**Issue by n1ck3** [deviantfero/wpgtk#172]
Hi,

I would like to see a setting which saves the themes with 256color approximations of the hex colors when using auto adjust.

The reason for this is that I want color consistency across my workflow. At the moment, I am facing these issues:
1. I am using urxvt + tmux and for some reason my tmux status line strangely approximates the colors to 256color ones. However I am able to see all the colors in their full glory by running: `wpg --preview`.
2. Sometimes I don't even run X and I want my tty + tmux to look nice and as similar as possible to the X experience.

Cheers!

**Comment by deviantfero** [comment]
that's what I work with most of the time, urxvt and tmux, I don't see an issue with them, are you running tmux in 256 color mode?

**Comment by deviantfero** [comment]
I will close this issue, please re-open if you keep having issues with the colors
