### ISSUE TITLE
Terminal Colors and CLI Applications

### ISSUE THREAD

**Issue by jruaaa** [deviantfero/wpgtk#178]
My terminal colors are not staying the same after I exit a CLI applications. Is there a bash script I can run to refresh the colors after I exit nano or ranger? A couple other questions: is there a way I can add commands to the wpgtk deploy and is there a way I can trigger a template update? My templates aren't updating my polybar i.e. http://i.imgur.com/BkqKIKs.png and my template and config are here: https://github.com/jruaaa/wpgtk-dotfiles/tree/master/wpg/templates. I've set colors many times but not sure if it's my fault.

**Comment by deviantfero** [comment]
Could I get the output of wpg when you run it and apply a theme from the terminal?, I see nothing wrong with your templates at a glance, what terminal are you using?

**Comment by jruaaa** [comment]
I’m using gnome terminal and my compositor is picom. I’ll try and do the things you asked when I get home

**Comment by jruaaa** [comment]
http://i.imgur.com/155naBd.png is what happens when I set the scheme from the term

**Comment by deviantfero** [comment]
I see the issue now, there's something wrong in your polybar template, replace line `238`, it has
```
label-warn-background = ${xrdb:color2}
```
replace with
```
label-warn-background = ${{xrdb:color2}}
```

**Comment by deviantfero** [comment]
and as Dylan said here: https://github.com/dylanaraps/pywal/issues/126, not much we can do about the issue of resetting colors, add an alias to ranger and nano, like this:

```
ranger && (cat ~/.cache/wal/sequences)
```
