### ISSUE TITLE
Create a zsh prompt that changes colors with wpgtk

### ISSUE THREAD

**Issue by cjstock** [deviantfero/wpgtk#179]
Right now my zsh prompt changes colors with wpgtk as it should.

I want to create a custom zsh prompt that keeps this functionality.

I added the following to my .zshrc:
`PS1="%F{$color9}%B%n%F{$color2}@%F{$color1}%m%F{$color2}:%F{$color14}%~%F{$color9}
==>}%F{$color15}%b "`

It grabs the proper colors and looks the way I want, but it no longer updates automatically when I change my theme. Instead, I have to source my .zshrc to see the changes.

How can I create a custom prompt while maintaining the dynamic wpgtk functionality?

**Comment by deviantfero** [comment]
are you using the colors in the terminal too? or do you want them just in the prompt?

**Comment by cjstock** [comment]
I see! That makes sense. Thanks for the help.
