### ISSUE TITLE
GTK+ Chromium Menus not affected by background color

### ISSUE THREAD

**Issue by jsonsystems** [deviantfero/wpgtk#182]
current version: 6.0.13
OS: ubuntu bionic beaver 

The highlight/hover color is correct (green), but the background of the menu remains unthemed (grey). It should the same colour as the menu **bar** (blue font, black background)

![2020-03-08-135220_1910x1070_scrot](https://user-images.githubusercontent.com/1623996/76164115-14089a80-6144-11ea-9c83-b0ddb362ed2b.png)

![2020-03-08-135448_1910x1070_scrot](https://user-images.githubusercontent.com/1623996/76164146-63e76180-6144-11ea-9f54-dc530a59bd4c.png)

**Comment by eyadsibai** [comment]
facing same issue

**Comment by eyadsibai** [comment]
the issue I have is related to the white menu in the picture shared. Why is it white if the theme suppose to be dark

**Comment by deviantfero** [comment]
This is because `vscode` uses Electron, and electron uses the same base as chromium for drawing is UI, so it's not plain and simple GTK, there are special theme classes in a GTK theme to affect these, and there's no documentation on them.

**Comment by jackwootton** [comment]
I also experience similar behaviour with `gnome-tweaks`. The `wpgtk` program adheres to the gtk theme generated by `wpgtk`, but `gnome-tweaks` does not.

![2020-03-09-210310_1759x997_scrot](https://user-images.githubusercontent.com/1623996/76257334-67184580-6249-11ea-9ced-be41471e24c0.png)

Using `wpgtk` to `Set` the theme then correctly styles `gnome-tweaks`.

![2020-03-09-210428_1810x943_scrot](https://user-images.githubusercontent.com/1623996/76257416-93cc5d00-6249-11ea-88a1-836d59cbba46.png)

However, closing `gnome-tweaks` and then reopening, and the theme has gone.

![2020-03-09-210447_1675x987_scrot](https://user-images.githubusercontent.com/1623996/76257449-9f1f8880-6249-11ea-914e-9e3ab86c6664.png)

**Comment by jackwootton** [comment]
Looks like `gnome-tweaks` , `lxappearance`, and `wpg` aren't really working together. `gnome-tweaks` is pretty much ignored. `lxpapperance` is overriding everything.

**Comment by jackwootton** [comment]
It seems Electron already draws menus according to the current GTK+ theme? https://github.com/electron/electron/issues/1065

**Comment by deviantfero** [comment]
You're suposed to only use one of those I think I personally only use `lxappearance`, I'm guessing `lxappearance` does things in a way that they override the `gnome-tweaks` settings

I'll give it a go with the selectors in that source file, thank you!

**Comment by eyadsibai** [comment]
amazing!!! thx

**Comment by jackwootton** [comment]
@deviantfero Thanks being so quick on this and reminding me not to overwrite non-gtk templates :)

WRT `gnome-tweaks` , `lxappearance`, and `gnome control center` - I stuck with `lxappearance` sincee it has zero gnome dependencies, so it's ideal when running i3 without any gnome components or gnome-flashback.
