### ISSUE TITLE
`Set` changes colors unnecessarily

### ISSUE THREAD

**Issue by jsonsystems** [deviantfero/wpgtk#185]
1. Open `wpgtk`
2. Go to the "Options" tab and toggle-off "Use smart sort" and "Always auto adjust"
3. Click the "Save" button
3. Go to the "Wallpapers" tab
3. Click the "Set" button multiple times

Actual result
-  Desktop colors change to use a different (random?) sequence
-  The "Colors" tab remains unchanged.

Expected
- Desktop colors shouldn't change

**Comment by deviantfero** [comment]
have you set the active/inactive color to anything but `Random`? the colorscheme remains the same, but the active/inactive colors change to provide more variety, you can also choose one:

![image1](https://i.imgur.com/TFN6btz.png)
![image2](https://i.imgur.com/X7o1rBZ.png)

**Comment by jsonsystems** [comment]
That was it. ty!
