### ISSUE TITLE
Permission denied when adding a new template

### ISSUE THREAD

**Issue by ninguem26** [deviantfero/wpgtk#188]
I'm trying to add a template to use spicetify with wpgtk, however, every template I try to add results in a permission denied error. I don't understand what's going on, since my user is the owner of the installation and the files I'm trying to add. Any idea what's going on?

![image](https://user-images.githubusercontent.com/13886547/79073881-5ed77e00-7cbf-11ea-9e58-82e8c8384169.png)

**Comment by kleshas** [comment]
I have what is probably the same issue when trying to edit the dunstrc.base template - permission denied.  I assume i should be editing that file in ./wpg/templates.

**Comment by deviantfero** [comment]
Yes, you should edit the .base files

**Comment by deviantfero** [comment]
Could I see an ls -l on that directory

**Comment by kleshas** [comment]
![Selection_001](https://user-images.githubusercontent.com/10134682/80854200-fd823b00-8bea-11ea-8368-459f01b23951.png)

**Comment by deviantfero** [comment]
How are you editing this file? The permissions seem to be correct

**Comment by kleshas** [comment]
I edit using subl3 (sublime-text-dev) editor.

**Comment by deviantfero** [comment]
that's weird, maybe try with `chmod 666 -R .` on that dir? I see no reason for this happening to you
@ninguem26 could you do the same ls -l for me on that `~/.config/spicetify/Themes/wal`, the only permissions you need are to make a symbolic link, what do you get if you just try to run

`ln -s ~/.config/spicetify/Themes/wal/color.ini ~/randomlink`

**Comment by deviantfero** [comment]
closing bc innactivity
