### ISSUE TITLE
wpgtk continues to update even though it is latest version already

### ISSUE THREAD

**Issue by cj360** [deviantfero/wpgtk#19]
On my pc, running pacaur -Syu updates all aur installed packages but wpgtk always reports as having an update so it re-runs when I check for updates for aur packages. Someone else has posted the same behavior with yaourt as well on the aur package page for wpgtk.

**Comment by deviantfero** [comment]
Hi there, i'm sorry I haven't appointed this issue, I will report back with any updates in the next week or so.

**Comment by deviantfero** [comment]
It should work now, it will update one more time, but that would be it, it should no longer appear unless I commit something to the master branch. thanks!
