### ISSUE TITLE
no FlatColor theme and no i3 theme

### ISSUE THREAD

**Issue by Araly** [deviantfero/wpgtk#190]
Hello,

when I run `wpg-install.sh -g` I get 
```
Cloning into '/home/araly/wpgtk-templates'...
remote: Enumerating objects: 27, done.
remote: Counting objects: 100% (27/27), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 3057 (delta 4), reused 22 (delta 4), pack-reused 3030
Receiving objects: 100% (3057/3057), 1.69 MiB | 126.00 KiB/s, done.
Resolving deltas: 100% (1934/1934), done.
Installing gtk themes
ln: failed to create symbolic link '/home/araly/.themes/FlatColor': No such file or directory
:: gtk3.0 theme done
:: gtk3.20 theme done
:: FlatColor gtk themes install done.
```
and the FlatColor stays ugly in lxappearance

I also don't get the colors in i3, here's my config: https://gitlab.com/araly/dotfiles/-/blob/master/.config/i3/config

Let me know if there's something I can try to do to help understand why

**Comment by Araly** [comment]
I installed the aur/gtk-theme-flat-color-git package, and now flatcolor works.
I'm still trying to understand how the Xresources work though

**Comment by deviantfero** [comment]
`wpgtk` uses pywal to do this, so the file generated by wpgtk is stored in `.cache/wal/colors.Xresources`, `wpgtk` uses `$HOME/.Xresources` as an extra method to override any colors that you don't want that appear in the file generated, so you need to clear your Xresources of any colors defined there as they might be overriding the ones provided by `.cache/wal/colors.Xresources`

**Comment by Araly** [comment]
so, I'm not sure how I did anything, but at some point it managed to work. I messed with the .Xresources file, got confused with configuration files, and now it works. I'll close this issue, hopefully it was just a weird one off thing, or just me doing something stupid
