### ISSUE TITLE
exclude background color from saturation and brightness changes optionally

### ISSUE THREAD

**Issue by Araly** [deviantfero/wpgtk#191]
Is there a way to alter saturation and brightness of a scheme but not the background ? I bring saturation up by 0.2 and brightness by 50, but this brings the background color up to, and it makes it less contrasty

**Comment by deviantfero** [comment]
you can use the GUI to do this, you can fine tune each colors' brightness and saturation individually

![image](https://i.imgur.com/G9UPcW3.png)

**Comment by Araly** [comment]
sorry, I'll rephrase it. Is there a way to do that same thing, not in the GUI ? I have a lot of wallpapers that I run wpgtk on, and I do all my changes and stuff in a script. Doing what you say in the GUI would be too much effort. If not, I'll just keep doing what I've been doing and not have anything special about the background color
