### ISSUE TITLE
Are there any backups?

### ISSUE THREAD

**Issue by SanketDG** [deviantfero/wpgtk#192]
Took some time to setup i3 and polybar starting from scratch. I remember installing this tool earlier and thought I could give this a try, and it replaces all of my config files without creating backups.

```
➜ wpg --version
current version: 4.9.3
```

I understand this is totally my fault to run the tools without taking backups and without updating `wpgtk` but is there a way (if at all) to restore these files?

**Comment by deviantfero** [comment]
It does make backups, check the .config/i3 folder, there should be a .bak
file with the original config, the install tool also warns you, sorry about
that inconvenience

You don't need to use the config file I provide via the install tool, you
can add your own via the custom template feature, read the wiki for more
info on that

Let me know how it goes

**Comment by SanketDG** [comment]
> t does make backups, check the ~/.config/i3 folder, there should be a .bak file with the original config, the install tool also warns you, sorry about that inconvenience, same for polybar, the backup should be along side the new configuration file under ~/.config/polybar/

There is nothing under those directories.

```
➜ tree .config/i3/
.config/i3/
└── config

0 directories, 1 file

~
➜ tree .config/polybar
.config/polybar
├── config
├── config2
└── launch.sh
```



> You don't need to use the config file I provide via the install tool, you can add your own via the custom template feature, read the wiki for more info on that

Yup, shouldn't have used the software blindly, but atleast this gives me the chance to re-learn things and setup everything from scratch again!

I will close this, thanks for making this awesome piece of software :)
