### ISSUE TITLE
Error on some wallpaper for GTK template

### ISSUE THREAD

**Issue by fsckr** [deviantfero/wpgtk#195]
Everything else works on most of my wallpaper but on some I get errors and the only thing that doesn't change are my folders in thunar.  I do have my icon set to Flattcolor.  Here is the output in the terminal when I get the error.

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/wpgtk/gui/theme_picker.py", line 154, in on_set_clicked
    themer.set_theme(filename, colorscheme_file)
  File "/usr/lib/python3.8/site-packages/wpgtk/data/themer.py", line 42, in set_theme
    pywal.export.every(colors, FORMAT_DIR)
  File "/usr/lib/python3.8/site-packages/pywal/export.py", line 68, in every
    template(colors, file.path, join(output_dir, file.name))
  File "/usr/lib/python3.8/site-packages/pywal/export.py", line 15, in template
    template_data = "".join(template_data).format(**colors)
KeyError: 'width'
```

**Comment by deviantfero** [comment]
weird, what's your pywal version `wal -v` and `wpg --version` should do the trick, also share that wallpaper if possible, I'd like to reproduce

**Comment by fsckr** [comment]
wal is version 3.3.0 and wpg is version 6.1.0.  Here is one of the wallpapers that it errors on.  It actually errors on a majority of the wallpapers. https://drive.google.com/file/d/1bHJlcDdVG0zUoo4ejJM1hb5Hi3CN66or/view?usp=sharing
Let me know if there is anything else you need me to provide.  Have a great day!

**Comment by deviantfero** [comment]
```
7:26:45 t440p ~ % wpg -a Pictures/wallpapers/Tron.png 
[i] image         Using image Tron.png.
[i] colors        Generating a colorscheme.
[i] colors        Using wal backend.
[i] colors        Generation complete.
[i] export        Exported json.
```

I had no problems with it, what backend are you using to generate colorschemes? I think therein lies the issue

**Comment by fsckr** [comment]
Hmm by backend are you referring to what is used to open up jpg, png and etc?

**Comment by fsckr** [comment]
Wel i think you are referring to like am i using feh?  I read your github page again.  I do everything from the command line and I have a script that changes the wallpaper and colors by a key bind.  so if I am using the command line to do this what backend would I be using?

**Comment by deviantfero** [comment]
no, I mean the backend you're using to generate colorschemes, as in `wal` or `colorz`, I'm not getting errors with that image either.

but I think I know what's the issue now, I think one of your templates is wrong, it's complaining that you have a `width` key somewhere in a template, are braces `{}` escaped in your templates? only valid keywords should have single braces. this is covered here: [templates](https://github.com/deviantfero/wpgtk/wiki/Templates)

**Comment by fsckr** [comment]
Hmmm i have removed all templates and reinstalled them.  Only ones I am using are the GTK and Rofi.  I still have the same issue and the backend I am using would be wal because I use wal -i to set the wallpaper in a small bash script.  I think use wpg -s with the same wallpaper to set the gtk colorscheme.  It was working perfectly fine until recently.  Here is the small script I made:

#!/bin/bash
wp_path=/home/rich/NAS/Wallpaper/
image=$(ls $wp_path | grep -E '(jpg|png)$' | sort -R | tail -1)
wpg -s $wp_path/$image
wal -i $wp_path/$image
#echo 'export $wp_path/$image' >> ~/.bashrc
sleep 3
~/alacritty-color-export/script.sh ~/.config/alacritty/alacritty.yml

**Comment by deviantfero** [comment]
you're supposed to add an image to wpg and then set that image, like this:

```
wpg -a $wp_path/$image && wpg -s $image
```

wpg will internaly do everything wal does, even exporting file formats from wal into the same folder that wal does, so that should be no issue, what's happening here is that you're not adding the wallpaper to wpg's wallpaper list, thus wpg is not saving the color scheme and when it tries to process the templates it will try grabbing the data from the file it would generate by adding the wallpaper.

I'm not sure why you're using pywal along side wpg, you should only use one, but I think that changing that third line in the script by the one I'm giving you should "fix" this issue you're having.

normally you would run `wpg -a /full/path/to/image.png` only once with the full path and then just `wpg -s image.png`, either way there's nothing wrong with adding the same image more than once, wpg simply finds an already generated colorscheme in your files and uses that.

**Comment by fsckr** [comment]
Just wanted to thank you for your time.  I finally figured out what it was.  My dunstrc file I was messing with.  after removing the dunstrc file everything worked as it did.  My apologies for any inconvenience.

Rich

**Comment by deviantfero** [comment]
nah don't worry, glad it was the template and not the use-case, I'll close this issue, thanks for using wpgtk
