### ISSUE TITLE
wpgtk only sets some themes the first run, then none

### ISSUE THREAD

**Issue by dospunk** [deviantfero/wpgtk#198]
I'm using Ubuntu Budgie 20.04, and when I run wpg and set my wallpaper the first time it sets the terminal and panel themes properly but not the windows. If I try to set the wallpaper again, or set a new wallpaper, everything gets set to the default theme (though I believe some of the terminal colors are set correctly). No errors are being shown.

I'm on version 6.1.3

**Comment by deviantfero** [comment]
Are you using the `FlatColor` GTK theme? if not I recommend you turn off the auto-reload GTK feature

**Comment by dospunk** [comment]
Does it only work with `FlatColor`?

**Comment by deviantfero** [comment]
Yeah, for now it only works with FlatColor, that might change in the
future, but you do need to modify a theme in order to change it's colors,
so for now
only FlatColor is supported, you might want to look at jasperro's
wpgtk-templates repo for an alternative that's a bit more "modern"

    -- Fernando Vásquez

**Comment by dospunk** [comment]
Alright, it worked with FlatColor except it didn't properly set the background. In the desktop settings it shows the background image as set, but on the desktop I just see a flat color.

**Comment by deviantfero** [comment]
what did you previously used to set your wallpaper?

**Comment by dospunk** [comment]
Just the normal Budgie Desktop Settings

**Comment by deviantfero** [comment]
ok, you might want  to open this issue in `pywal` instead, since I'm using pywal to set the wallpaper in the background, sorry for the late reply, this is the relevant code snippet from pywal in `wallpaper.py`

```python
        util.disown(["gsettings", "set",
                     "org.gnome.desktop.background",
                     "picture-uri", "file://" + urllib.parse.quote(img)])
```

**Comment by dospunk** [comment]
Alright, thanks!

**Comment by mgrarsalan** [comment]
I have a similar problem here. I use Ubuntu 20.04 LTS and when I use wpg (GUI) to set the wallpapers, Windows and terminal are set to color scheme but when i exit the windows and re-enter them again everything is back to default ubuntu theme.  It seems that wpg doesn't save the settings. I use flat color in application setting in Tweaks and I also tried turning auto-reload GTK feature off

**Comment by rahatzamancse** [comment]
This should be fixed by [this PR](https://github.com/deviantfero/wpgtk/pull/202) #202

**Comment by deviantfero** [comment]
Try with the new `6.2.2` release, good luck, let me know if it's still giving you the same issue

**Comment by Cyberdr3am** [comment]
Hi,

I think I have the same problem.
Indeed, when I will use the program to generate new colors the gtk theme will not be reloaded.
So I will end up with an all white theme for the gtk theme.
I have to go to the settings of xfce4 to reload the theme manually.
I have tested with lxappearance and it is exactly the same.
I am using the latest version available on AUR.
Manjaro Distribution
XFCE4 and I3.
Thanks for your future help.
