### ISSUE TITLE
Setting theme too many times breaks things

### ISSUE THREAD

**Issue by sashaaaaaaaaa** [deviantfero/wpgtk#199]
If you set themes too many times in a row, the titlebars disappear and you can't click on things. So then I have to restart X. Using XFCE 4.12.

**Comment by deviantfero** [comment]
It would be useful to have a console output PR the script you're using to
call wpgtk many times in a row

**Comment by deviantfero** [comment]
I'm assuming you managed to resolve this issue, re-open this issue if that isn't the case
