### ISSUE TITLE
wpgtk fails to apply theme

### ISSUE THREAD

**Issue by alanxyz** [deviantfero/wpgtk#200]
I am trying to apply a theme from an image, but I get this error, no matter what.
` ✘ alan@alnux  ~  wpg -a $HOME/Pictures/macOS.jpg && wpg -s $HOME/Pictures/macOS.jpg
[i] image         Using image macOS.jpg.
[i] theme         Set theme to _home_alan__config_wpg_wallpapers_macOS_jpg_dark_wal__1.1.0.json.
[i] colors        Found cached colorscheme.
[i] image         Using image macOS.jpg.
[i] colors        Generating a colorscheme.
[i] colors        Using wal backend.
[i] colors        Generation complete.
[i] sequences     Set terminal colors.
Traceback (most recent call last):
  File "/usr/bin/wpg", line 33, in <module>
    sys.exit(load_entry_point('wpgtk==6.1.3', 'console_scripts', 'wpg')())
  File "/usr/lib/python3.8/site-packages/wpgtk/__main__.py", line 312, in main
    process_args(args)
  File "/usr/lib/python3.8/site-packages/wpgtk/__main__.py", line 190, in process_args
    themer.set_theme(args.s[0], args.s[0], args.r)
  File "/usr/lib/python3.8/site-packages/wpgtk/data/themer.py", line 42, in set_theme
    pywal.export.every(colors, FORMAT_DIR)
  File "/usr/lib/python3.8/site-packages/pywal/export.py", line 68, in every
    template(colors, file.path, join(output_dir, file.name))
  File "/usr/lib/python3.8/site-packages/pywal/export.py", line 15, in template
    template_data = "".join(template_data).format(**colors)
KeyError: 'foreground);\n\turgent-background'
`
Sorry if this is a repost or anything like that, have never used Github before.
It also doesn't seem to change any color scheme.

**Comment by rahatzamancse** [comment]
The error message is self-explanatory. You have error in a template file.
Please go through all your template file to check if there are any syntax errors. Note that, if you are using older version, template syntax has hugely changed on v6.0.

**Comment by deviantfero** [comment]
you need to replace every `{` for `{{` and `}` for `}}`, unless they're meant to be variables replaced by wpgtk, you can read more on that in the template section of the wiki

**Comment by alanxyz** [comment]
Thank you, @rahatzamancse and @deviantfero for the replies! I will definitely read through the wiki again. Sorry for the inconvenience.
