### ISSUE TITLE
XQueryColor support?

### ISSUE THREAD

**Issue by imtbl** [deviantfero/wpgtk#201]
Some programs like https://github.com/conformal/spectrwm needs their colors defined in XQueryColor format: https://www.x.org/releases/X11R7.5/doc/man/man3/XParseColor.3.html

Example: `bar_font_color[1] = rgb:a0/a0/a0`

The XQueryColor docs state that:

> For backward compatibility, an older syntax for RGB Device is supported, but its continued use is not encouraged. The syntax is an initial sharp sign character followed by a numeric specification, in one of the following formats:

#RGB | (4 bits each)
-- | --
#RRGGBB | (8 bits each)
#RRRGGGBBB | (12 bits each)
#RRRRGGGGBBBB | (16 bits each)

But that doesn't seem to work with spectrwm at least, unless I'm missing something.

**Comment by imtbl** [comment]
Or would this have to be address in pywal itself?

**Comment by deviantfero** [comment]
yes, this issue is better suited for pywal directly
