### ISSUE TITLE
WPG not setting wallpaper without sudo

### ISSUE THREAD

**Issue by cspark-dev** [deviantfero/wpgtk#208]
Love the Wpgtk project, for some reason recently setting wallpapers does not work. I initially found this out on Sparkylinux where wpgtk installed via pip (sudo) did not even set wallpaper with sudo, the same situation occurred with NixOS with their native package. I am now on Arch Linux, where WPGTK sets the wallpaper successfully with sudo privileges only which is better than nothing. In each one, I used their respective version of feh. As of when I'm writing, feh version is 3.5 and wpgtk version on the AUR is r752.64b4523-1. Image magick, python pillow dependencies are installed and I have tried wallpaper setting with feh, with nitrogen instead and both installed at the same time. They are not the cause as they independently work at setting the wallpaper without sudo. In each distribution I was using their respective version of AwesomeWM, Xorg and Lightdm-webkit2-greeter in the repositories.

Without sudo, does not set the wallpaper but does set the Xresources theme : 

```
[i] theme_picker  current wallpaper: photo-1507567995179-7804ccc2ca65.jpeg
[i] image         Using image photo-1507567995179-7804ccc2ca65.jpeg.
[i] theme         Set theme to _home_cspark__config_wpg_wallpapers_photo-1507567995179-7804ccc2ca65_jpeg_dark_wal__1.1.0.json.
[i] colors        Found cached colorscheme.
[i] image         Using image photo-1507567995179-7804ccc2ca65.jpeg.
[i] theme         Set theme to _home_cspark__config_wpg_wallpapers_photo-1507567995179-7804ccc2ca65_jpeg_dark_wal__1.1.0.json.
[i] colors        Found cached colorscheme.
[i] sequences     Set terminal colors.
[i] export        Exported all files.
[i] export        Exported all user files.
[e] color         icons - base file does not exist
xrdb: No such file or directory
xrdb: can't open file '/home/cspark/.Xresources'
[w] reload        No settings daemon found, just refreshing Adwaita theme from gsettings
[i] wallpaper     Set the new wallpaper.
```

The output of sudo wpg, which despite the error actually works/sets the wallpaper compared to without sudo :

```
[sudo] password for cspark: 
[i] theme_picker  current wallpaper: photo-1507567995179-7804ccc2ca65.jpeg
[i] image         Using image photo-1507567995179-7804ccc2ca65.jpeg.
[i] theme         Set theme to _root__config_wpg_wallpapers_photo-1507567995179-7804ccc2ca65_jpeg_dark_wal__1.1.0.json.
[i] colors        Found cached colorscheme.
[i] image         Using image photo-1507567995179-7804ccc2ca65.jpeg.
[i] theme         Set theme to _root__config_wpg_wallpapers_photo-1507567995179-7804ccc2ca65_jpeg_dark_wal__1.1.0.json.
[i] colors        Found cached colorscheme.
[i] sequences     Set terminal colors.
[i] export        Exported all files.
[i] export        Exported all user files.
[e] color         icons - base file does not exist
xrdb: No such file or directory
xrdb: can't open file '/root/.Xresources'
[w] reload        No settings daemon found, just refreshing Adwaita theme from gsettings
[i] wallpaper     Set the new wallpaper.

(process:20146): dconf-WARNING **: 00:25:31.595: failed to commit changes to dconf: Error spawning command line “dbus-launch --autolaunch=835b35be2fac45c28033b93ffbec0744 --binary-syntax --close-stderr”: Child process exited with code 1

(process:20144): dconf-WARNING **: 00:25:31.715: failed to commit changes to dconf: Error spawning command line “dbus-launch --autolaunch=835b35be2fac45c28033b93ffbec0744 --binary-syntax --close-stderr”: Child process exited with code 1
```

**Comment by deviantfero** [comment]
what happens if you just run feh to set the wallpaper without wpgtk?

**Comment by cspark-dev** [comment]
Hi, thanks for the response.

feh works properly on itself, spitting no errors and correctly setting the wallpaper. I have used this in the past with wpgtk as a workaround : 
`feh --verbose --bg-scale ~/.config/awesome/wallpapers/photo-1507567995179-7804ccc2ca65.jpeg `

wpg without sudo successfully updates the xresources however does not set the wallpaper :
```
wpg -s ~/.config/awesome/wallpapers/photo-1507567995179-7804ccc2ca65.jpeg
[i] image         Using image photo-1507567995179-7804ccc2ca65.jpeg.
[i] theme         Set theme to _home_cspark__config_awesome_wallpapers_photo-1507567995179-7804ccc2ca65_jpeg_dark_wal__1.1.0.json.
[i] colors        Found cached colorscheme.
[i] sequences     Set terminal colors.
[i] export        Exported all files.
[i] export        Exported all user files.
[i] color         wrote: icon-step1
[i] color         wrote: gtk2
[i] color         wrote: gtk3.0
[i] color         wrote: gtk3.20
xrdb: No such file or directory
xrdb: can't open file '/home/cspark/.Xresources'
[w] reload        No settings daemon found, just refreshing Adwaita theme from gsettings
[i] wallpaper     Set the new wallpaper.
```

Interestingly enough, wal also does not set the wallpaper. I'm not sure if wallpaper setting via wal or wpgtk are different so is it possible pywal is the problem? This is the command I used, it also properly exports the Xresources but does not set the wallpaper :
```
wal -i ~/.config/awesome/wallpapers/photo-1507567995179-7804ccc2ca65.jpeg
[I] image: Using image photo-1507567995179-7804ccc2ca65.jpeg.
[I] theme: Set theme to _home_cspark__config_awesome_wallpapers_photo-1507567995179-7804ccc2ca65_jpeg_dark_None_None_1.1.0.json.
[I] colors: Found cached colorscheme.
[I] wallpaper: Set the new wallpaper.
[I] sequences: Set terminal colors.

                                
                                

[I] export: Exported all files.
[I] export: Exported all user files.
[I] reload: Reloaded environment.
```

**Comment by deviantfero** [comment]
pywal is used to set a wallpaper in wpgtk internally, so you should open an
issue in that repository instead, let me know if you're able to solve the
issue

    -- Fernando Vásquez

**Comment by cspark-dev** [comment]
AwesomeWM does not support pywal, and AwesomeWM can manage wallpapers on itself which can also be extended with lua if needed. Workaround is to set AwesomeWM to use the wpgtk .current symlink provided as so in the `theme.lua` file :

```
-- Using wpgtk to set the wallpaper
theme.wallpaper = "~/.config/wpg/.current"
```
