### ISSUE TITLE
Suggestion: Tie keywords to schemes

### ISSUE THREAD

**Issue by NimbleClint** [deviantfero/wpgtk#213]
I would like to suggest tying keyword values to individual schemes, rather than having them static. Here's why it might be useful:

I have a multi-monitor setup and I use feh to manage my wallpapers (I use different wallpapers for each monitor). I have a startup script which runs feh, and I can use wpgtk templates with custom keywords to change the wallpapers that feh looks for. However, because those keywords are static, I need to manually change them each time I change the color scheme. If the keywords were indexed to the color scheme, I could set it once and forget it. 

Another example would be fonts: a feature like this would allow the user to change their fonts based on their color schemes.

**Comment by deviantfero** [comment]
This has been previously requested, just an update, I'm working on this

**Comment by deviantfero** [comment]
#222 This is work in progress here, I'm close
