### ISSUE TITLE
automaticness

### ISSUE THREAD

**Issue by orangemn6** [deviantfero/wpgtk#214]
weird title but I was thinking if you could add automatically using the set wallpaper as the image. currently I have a theme changer script, but I have to go through all my files to set it in wpgtk. Thanks!

**Comment by PoSayDone** [comment]
Wpgtk need to be a daemon in this case, I dont't think that is a good idea, just use `wpg -s` command to set a wallpaper except of feh or smth

**Comment by deviantfero** [comment]
I think this is out of scope for the project, I'll close this, in the new `wpgtk 6.2.5` you get access to a lot of functions, so you could potentially script this
