### ISSUE TITLE
Desktop background disappears on reboot.

### ISSUE THREAD

**Issue by CrashyBang** [deviantfero/wpgtk#22]
Themes all remain intact it is just the desktop background which gets removed?

Is there something I need to add to my `autostart` sorry I am new to openbox and have never used `feh`.

Cheers.

**Comment by deviantfero** [comment]
add this line to `~/.config/openbox/autostart`

```sh
bash ~/.wallpapers/wp_init.sh
```

it's in the readme, cheers!
