### ISSUE TITLE
Configure template keyword replacement format

### ISSUE THREAD

**Issue by rlipperts** [deviantfero/wpgtk#221]
While trying to use templating to theme Pycharm with the custom theme of the [material plugin](https://www.material-theme.com/docs/configuration/custom-themes/) I stumbled upon the following problem: Their format requires the colors to be specified without the hashtag (e.g. c9bdb1) while wpgtk replaces them including the hashtag (e.g. #c9bdb1).

Is there already a solution for this? I could work around this by always following up wpg calls with a script that removes the hashtags but if possible i'd like to avoid that approach (also there does not seem to be something similar to pywal's -o option). 

If not i would suggest adding an option to configure the replacement format (maybe also with other color formats or included opacity)

**Comment by deviantfero** [comment]
check the wiki: https://github.com/deviantfero/wpgtk/wiki/Templates#default-keywords
you can use `{color8.strip}` to get the hex without the `#` character
