### ISSUE TITLE
Wpgtk not reloading some config files

### ISSUE THREAD

**Issue by PoSayDone** [deviantfero/wpgtk#223]
I have reinstalled my system, I used my .base files from my dotfiles but now not everything is refreshing. Rofi and spicetify config files don't want to refresh. I've tried to delete the config file, delete the .base file, nothing worked. But now I've tried to make file with another name and that worked, why is that happening?

https://youtu.be/IIjkbv0JL5w

**Comment by deviantfero** [comment]
Thanks for the video, so you're saying that specifically `color.ini` did not work but `colors.ini` did? 
I'll look into this, thanks for the heads up

**Comment by PoSayDone** [comment]
Yeah, I've fixed this by deleting the template file, closing wpgtk, opening wpgtk again, and making the template file again. It's very strange, maybe its caching something
