### ISSUE TITLE
"Settings daemon not found, just refreshing FlatColor Theme from gsettings"

### ISSUE THREAD

**Issue by DonaldKrump** [deviantfero/wpgtk#228]
I've tried running wpgtk on a couple of different distros now, most recently Manjaro Gnome, and while the wallpaper and terminal colors change, the GTK theme remains at default. Subject is the program output regarding the theme. Do I have to point wpgtk at the gnome settings  daemon or something?

**Comment by deviantfero** [comment]
are you using the FlatColor gtk theme?
