### ISSUE TITLE
Optional files error

### ISSUE THREAD

**Issue by CrashyBang** [deviantfero/wpgtk#23]
So I have a `qterminal` theme file: `Custom.colorscheme`

When I try to add it as an optional file I receive the following:

```
ADD::Custom.colorscheme@/home/otis/Developer/dotfiles/.config/qterminal.org/color-schemes/Custom.colorscheme
::MAKING BACKUP CONFIG
::CREATING BASE
ERROR
```

When I open it from my file manager it recognises it as a text file if that means anything?

Sorry this is the last issue I swear!

Cheers.

**Comment by deviantfero** [comment]
could you paste the contents of Custom.colorscheme here?

**Comment by CrashyBang** [comment]
As below:

```
[Background]
Bold=false
Color=44,44,44
Transparency=false

[BackgroundIntense]
Bold=true
Color=44,44,44
Transparency=false

[Color0]
Bold=false
Color=63,63,63
Transparency=false

[Color0Intense]
Bold=true
Color=112,144,128
Transparency=false

[Color1]
Bold=false
Color=112,80,80
Transparency=false

[Color1Intense]
Bold=true
Color=220,163,163
Transparency=false

[Color2]
Bold=false
Color=96,180,138
Transparency=false

[Color2Intense]
Bold=true
Color=114,213,163
Transparency=false

[Color3]
Bold=false
Color=223,175,143
Transparency=false

[Color3Intense]
Bold=true
Color=240,223,175
Transparency=false

[Color4]
Bold=false
Color=154,184,215
Transparency=false

[Color4Intense]
Bold=true
Color=148,191,243
Transparency=false

[Color5]
Bold=false
Color=220,140,195
Transparency=false

[Color5Intense]
Bold=true
Color=236,147,211
Transparency=false

[Color6]
Bold=false
Color=140,208,211
Transparency=false

[Color6Intense]
Bold=true
Color=147,224,227
Transparency=false

[Color7]
Bold=false
Color=220,220,204
Transparency=false

[Color7Intense]
Bold=true
Color=255,255,255
Transparency=false

[Foreground]
Bold=false
Color=220,220,204
Transparency=false

[ForegroundIntense]
Bold=true
Color=220,220,204
Transparency=false

[General]
Description=Dark Pastels
Opacity=1
```

**Comment by deviantfero** [comment]
I'm not sure about what's causing this error, but i can tell you that wpg won't work with that config file, it needs to use Hex to define it's colors!

**Comment by CrashyBang** [comment]
Hey @deviantfero okay thank you :)

**Comment by CrashyBang** [comment]
How hard would it be to add a function that could return the values as rgb? I am open to trying to code it myself if you think it would be worth it?

**Comment by deviantfero** [comment]
I don't think it would be worthy as it would need another set 'flags' so to speak and it would only a few users would benefit as not many config files use RGB to define their colors, i definetly recommend installing another terminal, like termite or urxvt both of which i'm sure, work with wpgtk
