### ISSUE TITLE
GTK theme has inverted background and foreground colors?

### ISSUE THREAD

**Issue by cultab** [deviantfero/wpgtk#230]
![2021-03-08-181553_1600x900_scrot](https://user-images.githubusercontent.com/51170833/110348572-77205c00-803a-11eb-9b11-c2bed2516989.png)

I think the image shows the problem a bit better, where do I even start to debug this?

**Comment by deviantfero** [comment]
color 14 and 15 should be foreground colors these are the colors used for font, what pywal version are you using? do `wal -v`.

**Comment by cultab** [comment]
```
$ wal -v
wal 3.3.0
```

**Comment by deviantfero** [comment]
sorry I did not reply earlier, can you share your theme with me so I can test locally in my computer? you should be able to do it with `wpg -o bluepinkpattern.png out.json`

**Comment by deviantfero** [comment]
this is how it looks in my computer atm:
![1617143484](https://user-images.githubusercontent.com/11150153/113065036-65cbfa80-9175-11eb-9d6a-ef28ca7d717e.png)

could you try re-installing the gtk theme and reaplying the colorscheme? 
`wpg-install.sh -g` should do it

**Comment by cultab** [comment]
Reinstalled the theme with `wpg-install.sh -g`, same thing happened, auto-adjusted the theme, 15 and 7 where some sort of white but still same issue.
![2021-03-31-122055_1600x900_scrot](https://user-images.githubusercontent.com/51170833/113122136-01b04180-921c-11eb-98c8-ac2d2356ef37.png)

Maybe the issue is on the gtk side?

**Comment by deviantfero** [comment]
what version of gtk are you on? sorry I've taken so long to reply

**Comment by cultab** [comment]
from querying my package manager I get:
```
[*] gtk+-2.24.32_4                   GTK+ toolkit (v2)
[*] gtk+-devel-2.24.32_4             GTK+ toolkit (v2) - development files
[*] gtk+3-3.24.28_1                  GTK+ toolkit (v3)
[*] gtk+3-devel-3.24.28_1            GTK+ toolkit (v3) - development files
```
no worries!

**Comment by deviantfero** [comment]
did you manage to solve this? I have not been able to reproduce this issue

**Comment by cultab** [comment]
I had given up on it but since then I've made another install in a new pc and because of your reply I tried it in the new install. It as it should, so I'm guessing something was messed up in my old install.

Since even I can't reproduce it on another pc I think I should close the issue. Thanks for trying to help tho, turns out your software was working fine haha.
