### ISSUE TITLE
About Wpgtk on FreeBSD

### ISSUE THREAD

**Issue by Fuzzbox999** [deviantfero/wpgtk#232]
Hi,

It's not a bug, sorry for the noise.
Just wanna let you know (if you don't, already) that the only thing I had to do to make Wpgtk work perfectly on FreeBSD was to install it using pip, then install gsed (GNU sed) an replace "sed" occurences with "gsed" in wpg-install.sh and in replace_folder_file.sh.base scripts.
I'm quite new to the BSD world, and I've understood that BSD sed does not support inline substitution.
There may be a way to modify these scripts to make them work on both OSes, but I'm not good enough with these tools to find out how.

Thank you for Wpgtk !

**Comment by deviantfero** [comment]
That's a really appreciated comment, and thanks for taking the effort to actually make it work on BSD, I will see if I can find the time to actually make this work on BSD OOTB

**Comment by vaskark** [comment]
OpenBSD, too. The package py-pip (or py3-ip) was all that was needed to build successfully. Wish it were in the repos :)
