### ISSUE TITLE
GTK3 theme not reloading 

### ISSUE THREAD

**Issue by ThatOneCalculator** [deviantfero/wpgtk#234]
As the title says. I have to close all apps using GTK to get the theme to change.

**Comment by ThatOneCalculator** [comment]
Update: I think it has to do with my xsettingsd being misconfigured. Can somebody send their xsettingsd settings?

**Comment by ThatOneCalculator** [comment]
Also, I do get
```
[i] color         wrote: gtk3.0
[i] color         wrote: gtk2
[i] color         wrote: gtk3.20
[w] reload        GTK2 reload support requires Python 2.
[i] reload        reloaded FlatColor from settings.ini using xsettingsd
[i] wallpaper     Set the new wallpaper.```

When running from GUI, but it doesn't work.

**Comment by deviantfero** [comment]
Hi, sorry you're having issues with wpgtk

What version of wpgtk are you using? Do you have Flatcolor set as your GTK
theme? Could you send a screenshot of your desktop environment or give more
details on that?

**Comment by ThatOneCalculator** [comment]
@deviantfero 

Version: 6.2.5
Flatcolor is my GTK theme (look at my comment about `.xsettingsd`)
More details: Arch running on bspwm, the only problem is that the GTK theme doesn't hot reload.

**Comment by ThatOneCalculator** [comment]
@deviantfero you there?

**Comment by deviantfero** [comment]
have you tried installing python2? also, post the contents of `~/.config/gtk-3.0/settings.ini` here, mine are: 
```
[Settings]
gtk-theme-name=FlatColor
gtk-icon-theme-name=flattrcolor
gtk-font-name=Inter Medium 10
gtk-cursor-theme-name=Adwaita
gtk-cursor-theme-size=0
gtk-toolbar-style=GTK_TOOLBAR_BOTH
gtk-toolbar-icon-size=GTK_ICON_SIZE_MENU
gtk-button-images=0
gtk-menu-images=0
gtk-enable-event-sounds=1
gtk-enable-input-feedback-sounds=1
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle=hintfull
gtk-xft-rgba=rgb
```

**Comment by ThatOneCalculator** [comment]
Here's mine:
```
[Settings]
gtk-theme-name=FlatColor
gtk-icon-theme-name=Zafiro
gtk-font-name=Cartograph CF 11
gtk-cursor-theme-name=Adwaita
gtk-cursor-theme-size=0
gtk-toolbar-style=GTK_TOOLBAR_BOTH
gtk-toolbar-icon-size=GTK_ICON_SIZE_LARGE_TOOLBAR
gtk-button-images=0
gtk-menu-images=0
gtk-enable-event-sounds=1
gtk-enable-input-feedback-sounds=1
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle=hintmedium
gtk-xft-rgba=none
```

Python2 wasn't installed, so I installed it but it didn't really make a difference.

**Comment by deviantfero** [comment]
what happens if you change theme and then you execute `xsettingsd -c .xsettingsd`? it should update your GTK theme

**Comment by ThatOneCalculator** [comment]
It acts really weird, I have to do

`killall xsettingsd && xsettingsd -c ~/.xsettingsd & disown` for it to work.

**Comment by deviantfero** [comment]
why is `xsettingsd` running in the first place? it should only be called to set this by `wpgtk`, can you check if you have a service or a script that sets `xsettingsd` in the background somehow?

**Comment by ThatOneCalculator** [comment]
Before this, I don't think anything was launching xsettingd by default

**Comment by deviantfero** [comment]
is the reload GTK+ option set to true?

**Comment by ThatOneCalculator** [comment]
Yes, ofc lol

For now I've just been doing the killall xsettingsd and xsettingsd thing.

**Comment by deviantfero** [comment]
try this, run `xsettingsd` in a console, it should output some log, then set a theme from the UI or another console window, xsettingsd should output something in the original console where you ran it, could you post that here?

**Comment by deviantfero** [comment]
by any chance could you take a video of this behavior? I'm not able to reproduce and funny enough I'm also running arch with bspwm.

**Comment by PoSayDone** [comment]
I also have this problem, but I use a little trick. I made external python script with live reload and its working. 
```
import shutil
import subprocess
import os
import tempfile

"""Runs xsettingsd for a short time to reload gtk3 theme"""
if shutil.which("xsettingsd"):
    fd, path = tempfile.mkstemp()
    try:
        with os.fdopen(fd, 'w+') as tmp:
            tmp.write('Net/ThemeName "FlatColor"\n')
            tmp.close()
            subprocess.Popen.wait(subprocess.Popen(["timeout", "0.2s", "xsettingsd", "-c", path]))
    finally:
            os.remove(path)

```
Just make a .py file with this code, in wpgtk options mark "Run commandand after" and put it in "Command:" in wpgtk like this: "python /path/to/scrpit/reload.py"

**Comment by deviantfero** [comment]
what's the difference between that and the actual code that's in wpgtk? the only difference I can see is that it's not trying to get the theme name from `settings.ini` and maybe the `subprocess.Popen.wait(` call, but that really shouldn't affect anything, @PoSayDone are you sure plain theme reloading already built into wpgtk is not working for you?

does this script still work if you remove the `subprocess.Popen.wait`?

**Comment by atrosekta** [comment]
hi, sorry to write in a closed issue, but i encountered the same problem so i thought i would be nice to let you know.

i fixed it by just adding the `timeout O.2s xsettingsd` line in the `run command after`,
*( my `~/.config/xsettingsd/xsettingsd.conf` contains just `Net/ThemeName "FlatColor"`,
and it work the same if i put the `-c` arg with a path to another file with the same content )*

i'm a bit confused on why this works but not the `wpg`'s code, as they both should do the same lol,

maybe its worth mentioning that i also at first had the same problem of `python2` not being installed *(neither `xsettingsd`)*, after installing it i didn't get that warn anymore, but xsettingsd outputed the same `xsettingsd: 0x4000001 took a selection from us; exiting` line, also i already had python3 installed from pacman, and the python2 package is `python2-bin` from the AUR,
i'm not sure this last paragraph is relevant but maybe it could help finding why it behave like this
