### ISSUE TITLE
Icons not auto-updating

### ISSUE THREAD

**Issue by gibranlp** [deviantfero/wpgtk#240]
i am working on this auto ricing qtile theme, and i have recently discovered wpgtk as a replacement for wal, so far everything works, all gtk apps change the color, wallpapers terminal everything, only the icons in thunar do not auto update, i have to close thunar and open it again to get the new icon colors.

Is there some way i can make this work automatically?

Thanks.

I am using
Qtile
Alacritty 
wpg version 6.2.5

**Comment by deviantfero** [comment]
no, sorry I think there might be a way to do it similar to the way I reload the GTK theme but I haven't looked into it. 
it also happens with `pcmanfm` so it's not file manager exclusive.
