### ISSUE TITLE
custom colours

### ISSUE THREAD

**Issue by kleshas** [deviantfero/wpgtk#242]
Getting back into this app, and I'm having issues.
Here's my process:
Add a picture, set to auto-adjust.  Colors tab - I increase the brightness a bit so the 0 colour (background for most apps) isn't quite so dark (light themes are too bright, before anyone suggests that.  My preference is a slightly brighter dark theme).  Click save.

Go to the wallpapers tab, and have that picture selected in both dropdowns.  The new colour is there in the color palette underneath the picture. Click Set.  The colour does not change in the apps (even after restarting them).  Reload wpgtk and the colours are back to the original auto-adjusted ones.

Same thing with Apply VTE fix - change to enabled.  Save.  Restart wpg and it's back to not enabled.  I've reinstalled wpgtk-git.

lxappearance (gtk2) and gtk3.0 settings.ini are set to flatcolor.

Another issue is qt5 apps.  Restarting them and they have the correct colours.  But I could've sworn they auto-updated yesterday when I first installed wpgtk.  Running sway, QT_QPA_PLATFORMTHEME=gtk2.

Another point of interest - what variable in gtk3.20.base do I edit to remove the outline around the URL bar when flatcolor chosen?

**Comment by deviantfero** [comment]
yes, this is a serious bug, I ran into it just now, I'm going to do a new release with the fix.

**Comment by deviantfero** [comment]
both these problems should be fixed in the new `6.5.1` release, I've left a few improvements as comments in the relevant files for future updates, but you should no longer have these problems, please report back if after updating you're still seeing this.

**Comment by kleshas** [comment]
Seems to work fine.  Thanks :)

Any info re the other two 'issues' I have?

**Comment by deviantfero** [comment]
for the first issue, I would have to look into it, I don't officially support QT, so there's not much I can do there, as I think I can barely manage GTK.

but for your other inquiry, yes, you can edit gtk.css.base, but you can also edit every other file in that folder, just use relevant css variables defined in gtk.css for colors and it should adapt every time you set a theme, for finding out what's the appropiate class to edit you should launch your application prefixed with `GTK_DEBUG=interactive` prefixed to your application name, for example:

```
GTK_DEBUG=interactive thunar
```

**Comment by kleshas** [comment]
Great info re editing.  I didn't know about that interactive variable, that will come in useful for sure.  Thanks.
