### ISSUE TITLE
terminal font colour

### ISSUE THREAD

**Issue by kleshas** [deviantfero/wpgtk#246]
i3-gaps, and sway.
If I use ```(cat ~/.config/wpg/sequences &)``` in .bashrc then the font color in kitty/alacritty stays white (backgrounds change).  I have tried with templates and without.  The templates update properly and the linked conf shows a non-white colour.

If I comment out the sequences line specified above, then the colours change, but only after a restart of the terminal.

Using latest wpgtk-git.
wpg.conf:
```[settings]
set_wallpaper = true
gtk = true
active = 0
light_theme = false
editor = geany
execute_cmd = false
command = urxvt -e echo hi
backend = wal
alpha = 100
smart_sort = true
auto_adjust = true
reload = true
keywords = default
vte = false

[keywords]

```
Tried with VTE fix enabled and disabled.

-------------------
as a secondary, more minor problem - I have the gtk template installed, and run FlatColor as the theme.  Whenever I click on the file manager's (pcmanfm-gtk3 and thunar) modified column (so as to re-order by date), the title row (Name, Description, Size, Modified) doubles in height; it resets after restarting the file manager.  Is this an issue with FlatColor or the gtk3 template?

**Comment by deviantfero** [comment]
for alacritty and kitty you need to create a template for the colors to be written to the configuration file, this is my template:

```
# Configuration for Alacritty, the GPU enhanced terminal emulator.

window:
  padding:
    x: 8
    y: 8
  decorations: none

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: sf mono
  bold:
    family: sf mono
  italic:
    family: sf mono

  # Point size
  size: 10.0

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 0
    y: 0

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increasing `x` moves the glyph to the right,
  # increasing `y` moves the glyph upwards.
  glyph_offset:
    x: 0
    y: 0

# Display the time it takes to redraw each frame.
debug:
  render_timer: false

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

colors:
  primary:
    background: '{color0}'
    foreground: '{color15}'
  cursor:
    text:       '{color0}'
    cursor:     '{color7}'
  normal:
    black:      '{color0}'
    red:        '{color1}'
    green:      '{color2}'
    yellow:     '{color3}'
    blue:       '{color4}'
    magenta:    '{color5}'
    cyan:       '{color6}'
    white:      '{color7}'
  bright:
    black:      '{color8}'
    red:        '{color9}'
    green:      '{color10}'
    yellow:     '{color11}'
    blue:       '{color12}'
    magenta:    '{color13}'
    cyan:       '{color14}'
    white:      '{color15}'

bell:
  animation: EaseOutExpo
  duration: 0

# Cursor style
#
# Values for 'cursor_style':
#   - Block
#   - Underline
#   - Beam
cursor.style: Block

# If this is `true`, the cursor will be rendered as a hollow box when the
# window is not focused.
cursor.unfocused_hollow_cursor: true

# Live config reload (changes require restart)
live_config_reload: true```

**Comment by kleshas** [comment]
Thanks for the config.  I'd got as far as that, but still an issue - the font color changes, but only after a reload of alacritty/kitty.  It never changes if (cat ~/.config/wpg/sequences &) is active (so I leave it commented out).  I tried xsettingsd, but no difference.  Of course, I run sway i.e. so no surprise there.  I

The title row of pcmanfm issue seems to have fixed itself - probably a reinstall / upgrade of something.

So, font colour and background colour DO change with theme change, but only when I exit and restart the terminal, and only when the sequences command is commented out in .bashrc.  This isn't a real big issue, but it would be nice to know why it happens.  Keep up the good work :)

**Comment by deviantfero** [comment]
if you're using allacritty config, don't add the `(cat ~/.config/wpg/sequences)` the config file and the live_config_reload should be enough
