### ISSUE TITLE
Archlinux not seeing anything

### ISSUE THREAD

**Issue by BigfootN** [deviantfero/wpgtk#25]
Hello,

I am trying to use wpgtk under archlinux, but the image (jpeg) I am trying to use is not showing. And I can't even see any colors. when launching `wpg` in command line mode the only thing I can see is :
```
CURRENT WALL: /home/user/.wallpapers/.current
:: installed by AUR
:: Generating /home/user/Images/image.jpeg.colors and /home/user/Images/image.jpeg.Xres in /home/user/.wallpapers
/usr/bin/
/home/user/Images/image.jpeg
:: Done

```

I installed wpg through this [package](https://aur.archlinux.org/packages/wpgtk-git/), so I am using the latest version.

Desktop environment: cinnamon

Thank you very much in advance for your help

**Comment by deviantfero** [comment]
Hi there sorry for the late reply, are you adding it via the gui? Or the
command line?

**Comment by BigfootN** [comment]
I am adding it via the gui

**Comment by deviantfero** [comment]
I think i know what it is, the file filter for the list is not letting it
through, rename it to a .jpg and add it again i will fix this but in the
mean time just add the as .jpg not .jpegs

**Comment by BigfootN** [comment]
Okay, I'll try this thank you for your help

**Comment by BigfootN** [comment]
So I just tried this and it worked, thank you very much 👍
