### ISSUE TITLE
changes at github stopping installation

### ISSUE THREAD

**Issue by kleshas** [deviantfero/wpgtk#258]
via "yay wpgtk-git":

Cloning into bare repository '/home/kleshas/.cache/yay/wpgtk-git/wpgtk'...
fatal: remote error:
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.

I'm assuming this is a config error on your end?
I've installed via downloading the zip and pip.

**Comment by deviantfero** [comment]
Thanks for letting me know I will take a look at this tomorrow

**Comment by deviantfero** [comment]
this has been fixed, if it hasn't feel free to re-open the issue
