### ISSUE TITLE
change theme on gnome

### ISSUE THREAD

**Issue by apoleon33** [deviantfero/wpgtk#259]
What i don't understand quite clearly is how to change the theme/shell of gnome. I ran `wpg-install.sh -g` but i don't understand what to do after, nothing change even after re-setting using the gui.

 - os: garuda linux
 - gnome version : 42

**Comment by apoleon33** [comment]
figured out how to use it for the applications (wasn't that hard lol) but still wondering for the shell itself...

**Comment by niksingh710** [comment]
> figured out how to use it for the applications (wasn't that hard lol) but still wondering for the shell itself...

How you did it?

**Comment by apoleon33** [comment]
> > figured out how to use it for the applications (wasn't that hard lol) but still wondering for the shell itself...
> 
> How you did it?

I launched gnome-tweaks, and over appearance selected "FlatColor" for old applications.
