### ISSUE TITLE
Wpgtk is somehow setting opacity in st

### ISSUE THREAD

**Issue by PoSayDone** [deviantfero/wpgtk#263]
Hi! I'm using st with xresources patch, so it using colors from ~/.cache/wal/colors.Xresources, but when I change my wallpaper, wpg sets different opacity in my st. (Firstly I thought that wpg is setting wrong bg color, but with non-transparent terminal everything works fine

https://user-images.githubusercontent.com/29358657/180853915-029acdc3-d073-4efd-9826-52b7d216c924.mp4

https://user-images.githubusercontent.com/29358657/180853924-5cb69dbf-f425-4374-9e8e-6273967c42f6.mp4

**Comment by deviantfero** [comment]
what do you have set in the opacity section of your `options` tab?

**Comment by PoSayDone** [comment]
I think we could close the issue, cause I'm no longer using st or wpgtk or even xorg.
