### ISSUE TITLE
Gnome theme

### ISSUE THREAD

**Issue by niksingh710** [deviantfero/wpgtk#264]
This could be silly but I am unable to figure out how can i apply the color scheme to other gnome themes (e.g sweet theme but color scheme based on wallpaper)

In [video's](https://youtu.be/QXpMMP8fT0o?t=36) comment you mentioned you are using Thunar. I am unable to get it the way you have it there. Is it really thunar?

**Comment by PoSayDone** [comment]
You need to install FlatColor gtk theme and use only it, cause other themes doesn't support wpgtk colorscheme.

run ```wpg-install.sh -g``` and after installation pick FlatColor theme in your settings.

**Comment by gibranlp** [comment]
i am havng a similar issue i have installed the Flatcolor theme, and actually everything was working fine, but for some reason suddenly stopped working.

I am on Qtile, any troubleshooting or what more  info can i provide?

**Comment by gibranlp** [comment]
When i try to set a wallpaper from wpg i get this
[~] ⮕⮕⮕ wpg
[i] theme_picker  current wallpaper: keyboards.jpg
[i] image         Using image wallhaven-xlgoov.png.
[i] theme         Set theme to _home_gibranlp__config_wpg_wallpapers_wallhaven-xlgoov_png_dark_wal__1.1.0.json.
[i] colors        Found cached colorscheme.
[i] image         Using image wallhaven-xlgoov.png.
[i] theme         Set theme to _home_gibranlp__config_wpg_wallpapers_wallhaven-xlgoov_png_dark_wal__1.1.0.json.
[i] colors        Found cached colorscheme.
[i] sequences     Set terminal colors.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/wpgtk/gui/theme_picker.py", line 159, in on_set_clicked
    themer.set_theme(filename, colorscheme_file)
  File "/usr/lib/python3.10/site-packages/wpgtk/data/themer.py", line 41, in set_theme
    pywal.export.every(colors, FORMAT_DIR)
  File "/usr/lib/python3.10/site-packages/pywal/export.py", line 68, in every
    template(colors, file.path, join(output_dir, file.name))
  File "/usr/lib/python3.10/site-packages/pywal/export.py", line 15, in template
    template_data = "".join(template_data).format(**colors)
KeyError: '\n  margin'`

**Comment by deviantfero** [comment]
@gibranlp seems like one of your templates is badly formatted, remember that if you have `{}` in your template you must escape the brackets by using double brackets, so if you have `{\n margin}` it should become `{{\n bracket}}`.

**Comment by deviantfero** [comment]
@niksingh710 it is Thunar, you must install and set the GTK+ theme though, I'm pretty sure that's covered in the first video tutorial I made back in the day, let me know if you're still having issues with that

**Comment by niksingh710** [comment]
> @niksingh710 it is Thunar, you must install and set the GTK+ theme though, I'm pretty sure that's covered in the first video tutorial I made back in the day, let me know if you're still having issues with that

Using Flat Color does not give it the look that you had in the video.
and I found no other theme template for wpgtk too yet.

**Comment by gibranlp** [comment]
Something is very weird, i have even installed the Flatcolor Theme from https://github.com/jasperro/FlatColor ~/.themes/FlatColor but stillnot working. like i said this was working fine, but suddenly stopped, only for Gtk, any way i can check this or fix it? thanks

**Comment by niksingh710** [comment]
@deviantfero  https://gradienceteam.github.io/

**Comment by PoSayDone** [comment]
> @deviantfero  https://gradienceteam.github.io/

wow, looks nice. would be a great replacement

**Comment by niksingh710** [comment]
> > @deviantfero  https://gradienceteam.github.io/
> 
> wow, looks nice. would be a great replacement 

I didn't mean for replacement I meant we can use the way this tool is integrating colors in a gtk theme.

@deviantfero is it possible to do so ?

**Comment by deviantfero** [comment]
🤔 it could be, but I'm currently swamped with my full time job so I can't really do much about it, btw I am still using the Flat color theme on an Arch Linux with the latest GTK and I haven't had an issue

**Comment by niksingh710** [comment]
> thinking it could be, but I'm currently swamped with my full time job so I can't really do much about it, btw I am still using the Flat color theme on an Arch Linux with the latest GTK and I haven't had an issue

same m using now gtk4 applications not using FlatColor like nautilus.

**Comment by deviantfero** [comment]
it shouldn't be too complicated to port the existing GTK theme to GTK4, I'll give it a spin this week

**Comment by niksingh710** [comment]
> it shouldn't be too complicated to port the existing GTK theme to GTK4 if node names haven't changed too much, I'll give it a spin this week.

I found a template from wal cache dir for oomix theme.
and wrote a wrapper script that gets color from wpg and places it in there and generates a oomix theme

https://github.com/themix-project/oomox-gtk-theme

but they had also not yet implemented gtk4 theme.


one question :- is there any way to remove `#` from replaced string 
like `{color0}` gets replaced with `#aabbcc` I want `aabbcc` for foot terminal only.

**Comment by deviantfero** [comment]
I've added a new theme to `wpgtk` in version `6.5.6`, here's a screenshot from `gtk-widgets`.

![image](https://user-images.githubusercontent.com/11150153/217024581-f011b0d6-91fe-4d81-975e-6e6b548dd311.png)
![image](https://user-images.githubusercontent.com/11150153/217024696-01b67323-e5a6-491f-945e-3a095ebc814f.png)

This theme is based on a GTK3 theme called linea nord. It is way easier to maintain and it has compatibility with GTK 4

**Comment by deviantfero** [comment]
@niksingh710 yes, you can use `{color0.strip}`. more on the wiki

https://github.com/deviantfero/wpgtk/wiki/Templates#default-keywords

**Comment by niksingh710** [comment]
> you can install this theme with `wpg-install.sh -G`, for now I'm still preserving FlatColor, but I think I will deprecate it soon.

The theme looks fantastic.
but in my testing, it is not applied on nautilus `version 43.2`

**Comment by deviantfero** [comment]
it's because it's a GTK4 application most likely, the theme works for GTK4 try to set your GTK4 theme to `linea-nord-color` and try opening nautilus again.

![image](https://user-images.githubusercontent.com/11150153/217124979-40840294-eaff-45f1-892d-a14f059ae3bd.png)

this is GTK4 working with the theme, Nautilus seems to have a few glitches, I've dedicated a few minutes to try and fix them, but I just manage to improve the appearance a little bit

**Comment by niksingh710** [comment]
> it's because it's a GTK4 application most likely, the theme works for GTK4 try to set your GTK4 theme to `linea-nord-color` and try opening nautilus again.
> 
> ![image](https://user-images.githubusercontent.com/11150153/217124979-40840294-eaff-45f1-892d-a14f059ae3bd.png)
> 
> this is GTK4 working with the theme, Nautilus seems to have a few glitches, I've dedicated a few minutes to try and fix them, but I just manage to improve the appearance a little bit

Yeah my bad, hadn't updated the GTK_THEME variable.
Now the theme is applied to gtk4 applications too.
just one glitch I noticed, around the borders.
![image](https://user-images.githubusercontent.com/60490474/217158034-4129a8a1-b28a-41e9-b7ea-2d0a70388187.png)

**Comment by niksingh710** [comment]
somehow oomox generates qt theme too for consistency.
is that be possible?

**Comment by deviantfero** [comment]
I'm not sure, I have to look into that.

**Comment by niksingh710** [comment]
I tried to find any qt theme that works with pywal but failed to get so.
but then also now we have linea for gnome with gtk4.
i think now I should be closing this issue.

do you think I should create another issue to keep track for qt theme?

**Comment by niksingh710** [comment]
Here is a [Qt](https://gist.github.com/niksingh710/0a5c7ec302b3a88b5d7fdcb1aa952a2c) template for qt5ct that will theme qt applications.

**Comment by niksingh710** [comment]
@dylanaraps 
I want one small help buddy
![image](https://user-images.githubusercontent.com/60490474/224991175-92e15460-c6e1-4baa-b6bf-7e9f085a8075.png)

This is what gtk-4 applications look like in my system for linea-nord-theme

using the command ` GTK_THEME="linea-nord-color" GTK_DEBUG=interactive nautilus` I got the interactive window and inside that window in the CSS section if I put 
```css
window {
	margin: 0px;
}
```
then it fixes the issue.

i tried changing that in dark.css In linea nord theme but doesn't seem to work.

can you please tell me where to put that to get that working? as it is working fine in interactive CSS

**Comment by niksingh710** [comment]
@deviantfero 
For some reason now linea-nord is not working for gtk4 applications.
