### ISSUE TITLE
can't resize GUI window

### ISSUE THREAD

**Issue by Soliprem** [deviantfero/wpgtk#267]
Can't resize the main window below this size (see picture)
![image](https://user-images.githubusercontent.com/73885403/190190073-aa6a480c-5c5c-4d91-9a46-093914ae0a74.png)

**Comment by deviantfero** [comment]
nice polybar/status bar, yeah I did not contemplate users changing the size of the window in any way, if you're on a tiling WM use floating window, I will mark this as a new feature but it is very low priority for me

**Comment by Soliprem** [comment]
thanks! Both for the bar (it's waybar) compliment and for the reaching out!
