### ISSUE TITLE
GTK 4 Support

### ISSUE THREAD

**Issue by Prayag2** [deviantfero/wpgtk#275]
It works really well with GTK 3 applications. Since, GTK 4 has been released, more and more applications are starting to adopt it. Please add support for GTK 4 as well!

**Comment by deviantfero** [comment]
Hi there, I recently added a new compatible  theme to the `wpg-install.sh`
script.

Just cal `wpg-install.sh -G` to install the new `linea-nord-color` theme
which has GTK4 support

**Comment by Prayag2** [comment]
Will it work for apps using libadwaita like easyeffects?

**Comment by Prayag2** [comment]
Thanks!
