### ISSUE TITLE
overriding my i3 config

### ISSUE THREAD

**Issue by ramonbrooks456** [deviantfero/wpgtk#280]
Hi

whenever i run 

`wpg -s walpapers`

it is overiding my i3 file. I dont want that. ant way to stop this?

**Comment by twllnbrck** [comment]
You have to configure i3 in your wpgtk template file wich is usually `$HOME/.config/wpg/templates/i3.base`.
This is copied over to a file in the template dir which is symlinked to your original i3 config.

Otherwise your config file is overwritten everytime you run `wpg`

**Comment by deviantfero** [comment]
you can also not add your i3 file to bpswm, you can remove it from the `Templates` tab in the UI.
