### ISSUE TITLE
GTK 4.0?

### ISSUE THREAD

**Issue by cprn** [deviantfero/wpgtk#281]
Hi. I was using `wpg` with great success to theme (among other apps) `transmission-gtk` but since version 4 they switched to GTK 4 and ignore GTK 3 & 2 themes. Is there a way to make `wpg` generate GTK 4 theme somehow as well?

**Comment by deviantfero** [comment]
I have integrated a new theme that does work on gtk4, update wpgtk and run
the installer helper with

wpg-install.sh -h

**Comment by cprn** [comment]
Yup, `GTK_THEME=linea-nord-color transmission-gtk` worked awesome, thank you very much!
