### ISSUE TITLE
Some images won't generate a coloscheme

### ISSUE THREAD

**Issue by Soliprem** [deviantfero/wpgtk#283]
The title says it all. Some files, no matter the backend (I tried both wal and haishoku) just won't work. I will attach one of said files. 
![sage_green](https://github.com/deviantfero/wpgtk/assets/73885403/7813f490-38e1-47d2-a19f-0d5a3315a811)

**Comment by kleshas** [comment]
That's a very simple pic in terms of variation of colours.  I've always had issues with pics like that.  Are more complicated pics OK?

**Comment by Soliprem** [comment]
yes, that looks like it might be the issue, as apparently the error messages seem to convey some sense of missing colors. Is there any work around?

**Comment by kleshas** [comment]
I've not found a workaround beyond entering manual colours.  You could colour drop the main colours in the pick, enter them in https://coolors.co to generate matching colours to enter back into wpgtk I guess.

**Comment by Soliprem** [comment]
since it's more of a backend issue than a wpgtk issue, I'll be closing the issue. Workaround from @kleshas  works fine if you really care about the single wallpaper
