### ISSUE TITLE
Wpgtk doesn't generate colorschemes

### ISSUE THREAD

**Issue by Alfatango12** [deviantfero/wpgtk#284]
Hi! So I'm on arch linux and I installed wpgtk-git from the aur. When I enter the command `wpg -a /path/to/wallpaper` it returns me that error: 

`Traceback (most recent call last):
  File "/usr/bin/wpg", line 33, in <module>
    sys.exit(load_entry_point('wpgtk==6.5.7', 'console_scripts', 'wpg')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/wpgtk/__main__.py", line 305, in main
    process_args(args)
  File "/usr/lib/python3.11/site-packages/wpgtk/__main__.py", line 222, in process_args
    add_action(glob.glob(x)[0])
  File "/usr/lib/python3.11/site-packages/wpgtk/data/themer.py", line 24, in create_theme
    return color.get_color_list(filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/wpgtk/data/color.py", line 36, in get_color_list
    is_new = not os.path.isfile(files.get_cache_path(filename))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/wpgtk/data/files.py", line 58, in get_cache_path
    filename = cache_fname(filepath, backend, False, WPG_DIR)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cache_fname() missing 1 required positional argument: 'cache_dir'`

I've seen error related to multiple `wal` installed on the system but `whereis wal` returns `wal: /usr/bin/wal` so it isn't the problem. I've tried with multiple wallpapers and I also use wal to generates colors for other applications. Also I'm using hyprland (if it can be useful) 
Any idea on how to fix it? Thanks in advance!

**Comment by deviantfero** [comment]
I was not able to reproduce, what version of pywal do you have installed? you need to be using the latest versioned released of pywal, not the git verison.

**Comment by hownioni** [comment]
Are you by any chance using pywal-16-colors? because I'm having the same trouble. I still couldn't get it to work but basically the function `cache_fname(img, backend, cols16, light, cache_dir)` asks for an extra "cols16" argument; `filename = cache_fname(filepath, backend, False, WPG_DIR)` only gives in the light argument, thus shifting the rest around and making it be missing the WPG_DIR file.

I changed the lines of code inside /usr/lib/python3.11/site-packages/wpgtk/files.py but the thing is now every time I run the command "Set" it gives out an index error

**Comment by M3CHR0M4NC3R** [comment]
Also unable to set a wallpaper, using the wpgtk aur package
```shell
[sam@thinkpad-air ~]$ wpg -a Pictures/wallpapers/MacOS\ wallpapers/OSX\ Sonoma\ Light.jpg 
Traceback (most recent call last):
  File "/usr/bin/wpg", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/wpgtk/__main__.py", line 305, in main
    process_args(args)
  File "/usr/lib/python3.11/site-packages/wpgtk/__main__.py", line 222, in process_args
    add_action(glob.glob(x)[0])
  File "/usr/lib/python3.11/site-packages/wpgtk/data/themer.py", line 24, in create_theme
    return color.get_color_list(filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/wpgtk/data/color.py", line 36, in get_color_list
    is_new = not os.path.isfile(files.get_cache_path(filename))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/wpgtk/data/files.py", line 58, in get_cache_path
    filename = cache_fname(filepath, backend, False, WPG_DIR)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cache_fname() missing 1 required positional argument: 'cache_dir'
```

**Comment by deviantfero** [comment]
what pywal version are you using? for now I only support `pywal 3.3.0`

**Comment by M3CHR0M4NC3R** [comment]
> what pywal version are you using? for now I only support `pywal 3.3.0`

I was using pywal-16, but I downgraded it to the 8 color version of pywal and wpgtk started working

**Comment by deviantfero** [comment]
you shouldn't need pywal-16 if you're using wpgtk anyway :) wpgtk should take care of the other 8 colors for you.
