### ISSUE TITLE
Attach a colorscheme to a image, without generating the _wal_sample.png

### ISSUE THREAD

**Issue by nimaaskarian** [deviantfero/wpgtk#286]
A way to avoid the generation of `<wallpaper name>_wal_sample.png` when attaching a (pywal or user) theme to a wallpaper. 
I just want the wpgtk to generate the flat color theme for me. I don't do anything fancy like chaning the saturation or brightness of the scheme.

**Comment by deviantfero** [comment]
sorry, can't really implement this, these images are used as a preview on the UI side

**Comment by nimaaskarian** [comment]
> sorry, can't really implement this, these images are used as a preview on the UI side

What about outputting them in another directory like `/tmp`?  
Or should I just delete them in my wal script if I don't use the UI side?
