### ISSUE TITLE
Aur Package break.

### ISSUE THREAD

**Issue by niksingh710** [deviantfero/wpgtk#287]
After commit 00af1c5115fc16c3f67a3b481b2c220c12766bb3 Aur update fails

**Comment by Soliprem** [comment]
+1 on this. 
```
/sbin/python: No module named build
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: wpgtk-git-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
wpgtk-git - exit status 4
```
This is the error code

**Comment by Soliprem** [comment]
update: adding the following packages as dependencies should fix the issue:
```
python-build
python-installer
```
(build and installer modules were missing)

**Comment by niksingh710** [comment]
> update: adding the following packages as dependencies should fix the issue:
> 
> ```
> python-build
> python-installer
> ```
> 
> (build and installer modules were missing)

yeah can ensure this fixes the issue

**Comment by deviantfero** [comment]
sorry about this everyone, fixing it now

**Comment by deviantfero** [comment]
Should be fixed now, thanks for letting me know, I won't close until I get confirmation from someone else that it works fine :+1:

**Comment by Soliprem** [comment]
Can confirm it works!
