### ISSUE TITLE
Base file does not exist?

### ISSUE THREAD

**Issue by rawsh** [deviantfero/wpgtk#29]
I installed the aur package. Adding and selecting a wallpaper works, and it changes the background. However, I get this output (tint2 running on openbox):

`CURRENT WALL: /home/robert/.wallpapers/2ofdvd00xog-samuel-scrimshaw.jpg`
`:: installed by AUR`
`:: Setting uoi3lg8fgl4-sam-ferrara.jpg as background`
`:: Done`
`FG: 52739f`
`BG: 2d3e56`
`FAILED TO CHANGE::OPENBOX - BASE FILE DOES NOT EXIST`
`FAILED TO CHANGE::TINT2 - BASE FILE DOES NOT EXIST`
`FAILED TO CHANGE::GTK2 - BASE FILE DOES NOT EXIST`
`FAILED TO CHANGE::GTK3 - BASE FILE DOES NOT EXIST`
`FAILED TO CHANGE::GTK3.20 - BASE FILE DOES NOT EXIST`
`CHANGED::ICONS`
`CURRENT GLYPH: 314954`
`NO OPTIONAL FILES DETECTED::NOT CHANGED`
`SUCCESS`

The file .config/openbox/menu.xml exists as does rc.xml and autostart.
Tint2 has a config. The icons work by selecting Flattr icons, but there are no entries for colorbamboo or Flatcolor.

BTW thank you for the project! Generating colorschemes is really cool.

**Comment by deviantfero** [comment]
Hi robert, thank you, it seems that the installer may have failed to copy
the .base files to their respective directories, please re-install and post
the output of the install please, maybe there's something wrong with the in
install script

**Comment by rawsh** [comment]
@deviantfero Thank you for your quick response! Here is what I got installing from the git repo:

http://dpaste.com/3P33XP4

The tint2 seems to work now.

**Comment by deviantfero** [comment]
could you show me output of the following commands?

`ls ~/.themes/FlatColor/gtk-3.20 | grep base`

`ls ~/.themes/colorbamboo/openbox-3 | grep base`

`ls ~/.config/tint2/ | grep base`

**Comment by rawsh** [comment]
I figured out the problem. If I delete .wallpapers .themes and .icons before installation, I get the gtk theme correctly. However, I still have the weird issue with tint2. (Its like its writing on top of another theme...)

Thank you for your help!

**Comment by deviantfero** [comment]
that's weird, maybe you have 2 tint2 instances running at the same time? maybe restart your computer, also about the deletion of the folders, it's not suposed to be like that, so i'll submit a fix in a few minutes.

**Comment by rawsh** [comment]
I've tried restarting, deleting the files ect it still does the same thing... weird. I'll try a blank file before I generate the theme.

**Comment by deviantfero** [comment]
Did it work?

**Comment by rawsh** [comment]
@deviantfero Nope... sorry for the late reply.

**Comment by deviantfero** [comment]
yeah, it seems like it, but what happens if you `killall tint2 && tint2` ?

**Comment by rawsh** [comment]
@deviantfero Tried that, no luck. I think I corrupted it somehow because I had a custom theme before.

**Comment by deviantfero** [comment]
try `sudo ps aux | grep tint2`, compare with mine:
```sh
λ ~ % sudo ps aux | grep tint2
fernando  1971  0.0  0.3 197488 14420 ?        S    15:38   0:01 tint2
```

**Comment by rawsh** [comment]
empty while its running... weird again.
But I think the issue is the taskbar. It looks normal without it.

**Comment by deviantfero** [comment]
yeah, I don't know what else to try, what i would do next is:
`sudo pacman -Rsn tint2 && rm -rf ~/.config/tint2` and reinstall tint2, if you find out how could wpgtk have caused this, please let me know.

**Comment by rawsh** [comment]
@deviantfero I found a (temporary) fix: It works with the panel on the side. Thats the way I like it anyway... I edited my tint2rc.base and it looks awesome. Thanks again for this code!

![2017-01-16-231821_1920x1080_scrot](https://cloud.githubusercontent.com/assets/7035671/22008579/1bffe9d0-dc42-11e6-959b-7d055a0a969e.png)

One quick question though... I don't really like Flattr icons. How did you change the colors there? I want to do something similar with the Paper icon pack.

**Comment by deviantfero** [comment]
Sorry for the late reply, but the Icons are the most complicated part of the whole theme, the use a script internally that uses the `sed` command to replace keywords inside certain .svg icons in the icon theme (such as folders), which in turn is altered by wpgtk to reflect the active and inactive colors, so basically, wpgtk alters the script that alters the icon's colors, playing with base files you might be able to reach something similar with another icon theme, but you would have to execute your script manually after it's been modified by wpgtk

**Comment by rawsh** [comment]
@deviantfero Thank you for your reply. I got something working with Paper that uses mogrify to hue the images. Its far from perfect but it matches it decently. I might try your method later.

![screenshot from 2017-01-17 22-20-15](https://cloud.githubusercontent.com/assets/7035671/22050758/323464b2-dd03-11e6-86f1-edace36b2ff1.png)

I'll check out the firefox theme, thanks!
