### ISSUE TITLE
wpg-install.sh missing from the AUR

### ISSUE THREAD

**Issue by chanhhanh** [deviantfero/wpgtk#297]
**Problem:** 
wpg-install.sh script is missing after installing from the AUR
**Steps to reproduce:**
install `wpgtk-git` or `wpgtk`  with `yay`
**Expected result:**
`wpg-install.sh` is found in when calling the script in the terminal
**Actual result:**
the script was not found

**Comment by deviantfero** [comment]
Thanks for the report, ill take care of this soon

**Comment by arg0x** [comment]
same issue

workaround:
the file is actually in `/usr/lib/python3.11/site-packages/wpgtk/misc/` by moving to `/usr/bin/`  it works

**Comment by deviantfero** [comment]
fixed!
