### ISSUE TITLE
wpg-install.sh lacking execute permission

### ISSUE THREAD

**Issue by chanhhanh** [deviantfero/wpgtk#299]
To follow up on the last issue: #297 
wpg-install.sh is lacking execution permission after installed from the AUR.

Expected behavior:
`wpg-install.sh -h` should run the script normally
Actual behavior:
wpg-install.sh is denied from executing

Also, after giving execution permission to wpg-install.sh, the script installs the template into `/root` instead of the user directory.

Expected behavior:
wpg-install.sh clones into the user dicrectory, and installs the template into the user directory
Actual behavior:
wpg-install.sh clones into the `/bin` directory, and installs the template into the `/root` directory

**Comment by gibranlp** [comment]
Having the same exact issue

**Comment by deviantfero** [comment]
Haven't gotten to fix it due to workday constraints. It should be a simple fix. I will get to it soon

**Comment by deviantfero** [comment]
fixed, sorry for the wait
