### ISSUE TITLE
Failing to generate i3 config

### ISSUE THREAD

**Issue by TheBlackParrot** [deviantfero/wpgtk#30]
Only output I'm getting is `FAILED TO CHANGE::OPTIONAL FILE -config` even with a brand new i3 config; it just generates a blank file. XFCE's terminalrc generates fine. Same exact setup works fine on another system.

Both systems are Arch / Python 3.6.0.

```
[theblackparrot@Arch-X220 .wallpapers]$ wpg
CURRENT WALL: /home/theblackparrot/.wallpapers/wallhaven-475416.jpg
[Errno 2] No such file or directory: '/home/theblackparrot/.wallpapers/wpg.conf'
(2, 'No such file or directory')
/home/theblackparrot/.wallpapers/wpg.conf
ERR:: Default Config Loaded
Adding...
ADD::config@/home/theblackparrot/.config/i3/config
::MAKING BACKUP CONFIG
::CREATING BASE
::CREATING SYMLINK
:: installed by AUR
:: Setting wallhaven-475416.jpg as background
:: Done
FG: 043b79
BG: 021a35
CHANGED::OPENBOX
NO OPENBOX INSTALL!
FAILED TO CHANGE::TINT2 - BASE FILE DOES NOT EXIST
CHANGED::GTK2
CHANGED::GTK3
CHANGED::GTK3.20
CHANGED::ICONS
CURRENT GLYPH: 010b17
FAILED TO CHANGE::OPTIONAL FILE -config
SUCCESS
xrdb: No such file or directory
xrdb: can't open file '/home/theblackparrot/.Xresources'
```

**Comment by deviantfero** [comment]
Could I see a screenshot of the `Optional Files` tab? also I would like to see the output for

```sh
ls -l $HOME/.themes/color_other
```

**Comment by TheBlackParrot** [comment]
```
[theblackparrot@Arch-X220 color_other]$ ls -l
total 24
-rw-r--r-- 1 theblackparrot users    0 Mar  7 16:45 config
-rw-r--r-- 1 theblackparrot users 5221 Mar  7 16:35 config.base
-rw-r--r-- 1 theblackparrot users  858 Mar  7 16:17 terminalrc
-rw-r--r-- 1 theblackparrot users  874 Mar  7 15:06 terminalrc.base
[theblackparrot@Arch-X220 color_other]$
```
Optional files tab:
http://i.imgur.com/7TKW7At.png

**Comment by deviantfero** [comment]
Can i ask you how did you add the config file to wpg? it seems that the config file in that folder is not pointed to by a symbolic link if you do `ls -l ~/.config/i3`, `config` should be a symbolic link to the `config` file in `color_other`

here is a screenshot of my I3 virtual machine for testing wpg, it displays a symbolic link to the original config file.
[Screenshot](http://i.imgur.com/OyfTt8G.png)

you could fix this by simply doing:
```sh
ln -s ~/.themes/color_other/config ~/.config/i3/config
```

but please try removing the file and readding it again to see if it works, that means, delete the base from `wpg`, then on your `.config/i3/` folder, rename `config.bak` to `config` on that same, and try again adding `.config/i3/config` to wpg, if that fails to create the symbolic link, let me know.
