### ISSUE TITLE
rofi

### ISSUE THREAD

**Issue by kleshas** [deviantfero/wpgtk#300]
Been fiddling around again, and have completely forgotten how to set up rofi.

I ran wpg-install -r.  It then tells me to add @theme "wpg" to my rofi config.  I assume I add this to the bottom of the config.rasi file in ~/.config/rofi.  (I assume that config.rasi cannot have colours defined in it, hence the need to point to a new file with the theme variables)

In my understanding, this will load wpg.rasi from that same folder.  However, that file has issues - highlight and scrollbar aren't defined, but are used, so there are errors when running rofi.
When I edit to this:
    background:					@color0;
    foreground:						@color15;
    highlight:						@color1;
    scrollbar:						@color7;
(ie added the last 2 lines)
it has the same error - highlight not resolved, scrollbar not resolved.  
Hmm, config_rofi_wpg.rasi.base isn't being updated.  Even when I manually add the template.

Am I missing something?

**Comment by kleshas** [comment]
OK, update.  most of the error I was seeing was user-error.  I'd managed to delete one of the {} pairs everywhere in the template.  So it wasn't updating the .rasi.
However, the highlight and scrollbar aren't defined in wpg.rasi.base, even in https://github.com/deviantfero/wpgtk-templates/blob/master/rofi/wpg.rasi.base

**Comment by deviantfero** [comment]
yay! thanks, if you can come up with a PR to fix that in the default template in that repo I would appreciate it
