### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by kleshas** [deviantfero/wpgtk#307]
I'm looking for an option to have one or two of the colours be a complementary to another specific one, without editing it manually.
At the moment, a lot of the colours are very similar, so there's no strong distinction between them when used in conky, for example.  I know wal is in charge of the colours, but I was wondering if there's a way to do this in wpgtk, as I don't see a way to do it in pywal.

As an example, it would be nice to have colours 12-15 complementary to colours 0-3

edit:  also, is it possible to get RGBA format for the colours?  and with no leading #. I know you can use {color1}ff to get close, but this still has a # at the start, which fuzzel doesn't recognize.

**Comment by deviantfero** [comment]
yes, I think you can use `{color1.strip)`, read this section of the wiki https://github.com/deviantfero/wpgtk/wiki/Templates#default-keywords
