### ISSUE TITLE
Can't use two config files with same filename

### ISSUE THREAD

**Issue by jollybard** [deviantfero/wpgtk#31]
For example both i3 and termite use config files named 'config'. Proposed solution would be to ask the user what to name the base file, or to concatenate with the folder it's in, so that it does not get mixed up and so they can be managed more easily. 

In this case i3's config file might be named 'i3config' and termite's 'termiteconfig'

**Comment by deviantfero** [comment]
I will leave this issue open as I might consider it for future releases, for now this is a quick fix:
* remove all `.base` files that conflict from `~/.themes/color_other/`
* re-add i3's config with wpg
* rename your `.base` file to the unique name
* make your `.config/i3/config` a link to the produced filed with that unique name after applying a colorscheme for the first time.

for example, for i3 and termite (assuming clean optional files), I would go about doing that like this:

after adding i3's config you should:

```sh
mv ~/.themes/color_other/config.base ~/.themes/color_other/i3config.base
ln -s ~/.config/i3/config ~/.themes/color_other/i3config
```

then add termite as usual, that should do it

**Comment by jollybard** [comment]
I just edited your script so that the `filename` becomes `folder.file` instead of just `file`. 

For example `~/.config/termite/config` becomes `termite.config` and `termite.config.base`. Seems to work.

**Comment by deviantfero** [comment]
Great, you could push the changes maybe? I would just test if it doesn't break compatibility with previous `.base` files which don't have that filename with the folder

**Comment by deviantfero** [comment]
Thanks, pull request has been merged.
