### ISSUE TITLE
ModuleNotFoundError: No module named 'gi'

### ISSUE THREAD

**Issue by tohd** [deviantfero/wpgtk#33]
I installed from the AUR. I don't know what happened.

`Traceback (most recent call last):
  File "/usr/local/bin/wpg", line 6, in <module>
    from wpgtk.wpg import *
  File "/usr/local/bin/wpgtk/wpg.py", line 2, in <module>
    from gi import require_version
ModuleNotFoundError: No module named 'gi'
`

**Comment by deviantfero** [comment]
do you have `python-gobject` installed? it should be included in the dependencies.

**Comment by tohd** [comment]
yes i do, thats the weird part

**Comment by tohd** [comment]
oops
