### ISSUE TITLE
Terminal background does not change color

### ISSUE THREAD

**Issue by tohd** [deviantfero/wpgtk#34]
When I run the program, the text changes color, but not the background. Any idea?

**Comment by deviantfero** [comment]
could you please provide the console output? do you have `feh` installed? or do you have any other wallpaper software besides `wpgtk` ?

**Comment by tohd** [comment]
`** (wpg:3702): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-JVXDevnruu: Connection refused
INF::CURRENT WALL: lamps.jpg
:: installed by AUR
:: Setting lamps.jpg as background
:: Done
INF::FG: 626262
INF::BG: 353535
OK::OPENBOX
ERR::NO OPENBOX INSTALL!
ERR::TINT2 - BASE FILE DOES NOT EXIST
OK::GTK2
OK::GTK3
OK::GTK3.20
OK::ICONS
INF::CURRENT GLYPH: 464646
OK::OPTIONAL FILES - i3.config
OK::FINISHED`

Yes I do.

Not to my knowlege (this is a fresh install)

**Comment by tohd** [comment]
Also, to avoid any confusion, I was talking about the background color of the terminal, the wallpaper is set fine.

**Comment by deviantfero** [comment]
oh, you should set your background color to 0 in your .Xresources like this: `*background: 0` if you're using urxvt or xterm.

**Comment by deviantfero** [comment]
fixed thanks to `wal` integration. Just run `(wpg -t &)` in any terminal and it will load the colors in the current colorscheme.
