### ISSUE TITLE
Cannot handle spaces in directory 

### ISSUE THREAD

**Issue by keptan** [deviantfero/wpgtk#4]
You forgot to escape spaces or something, you cannot open images from folders with spaces in them. 
Also can you use the gtk2 filepicker instead of the gtk3 one your using now, gtk3 is ugly.

**Comment by deviantfero** [comment]
thanks, now i'm aware and i'll close the issue as soon as I get to fix it!

**Comment by deviantfero** [comment]
Fixed now, tried with several spaces in one folder and it worked, had to hack my way around it but it's done

**Comment by keptan** [comment]
what about directories with foward slashes in the name?

**Comment by deviantfero** [comment]
now it works with directories wich have forward slashes too! thanks for your feedback!
