### ISSUE TITLE
wpgtk requires Python 3.5 or greater error

### ISSUE THREAD

**Issue by nobodyme** [deviantfero/wpgtk#53]
I use linux mint and the python version installed in my system is 3.6.2 still installing wpgtk says that it requires Python 3.5 or greater. So can you tell me how to solve this?
![screenshot here](https://user-images.githubusercontent.com/22789194/29295203-a969be72-8142-11e7-8598-b07cd906ffc3.png)

**Comment by dylanaraps** [comment]
Can you upload the contents of the `pip` debug log? It should tell us what went run in the install.

**Comment by deviantfero** [comment]
In debian based distros you should install with pip3 instead, the package
is called python3-pip

**Comment by dylanaraps** [comment]
`pip3` is the correct name for all installs of `Python 3+`. (*Every `Python 3` install should also install `pip` to `pip3` even if `Python 3` is installed as `Python`.*)

The `README` should be updated to say `pip3 install wpgtk`.

**Comment by deviantfero** [comment]
Will do when I get home.

**Comment by deviantfero** [comment]
done, will close this issue.
