### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by chancellorr** [deviantfero/wpgtk#54]
I'm sorry I'm a bit of a linux noob.
I try to run the wpg command after installing everything (which seemed to go smoothly)
I get this output

`
ERR:: Not a valid config file
INF:: Copying default config file
ERR:: Not in default prefix
ERR:: Attempting in /usr/local prefix
Traceback (most recent call last):
  File "/home/invadrr/.local/lib/python3.5/site-packages/wpgtk/data/config.py", line 93, in init
    shutil.copy(CONF_BACKUP, CONF_FILE)
  File "/usr/lib/python3.5/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.5/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/etc/wpgtk/wpg.conf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/wpg", line 11, in <module>
    load_entry_point('wpgtk==4.5.7', 'console_scripts', 'wpg')()
  File "/home/invadrr/.local/lib/python3.5/site-packages/wpgtk/__main__.py", line 54, in main
    config.init()
  File "/home/invadrr/.local/lib/python3.5/site-packages/wpgtk/data/config.py", line 99, in init
    'wpgtk/wpg.conf'), CONF_FILE)
  File "/usr/lib/python3.5/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.5/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/etc/wpgtk/wpg.conf' `

I'm probably missing something simple, but like I said, I'm new to this.

**Comment by deviantfero** [comment]
seems that you installed the package without root privileges, uninstall the package and then run
`sudo pip3 install wpgtk`, report back with results please!

**Comment by FlorianFranzen** [comment]
This seems to be a bug indeed, as wpgtk looks for the config in ```/usr/etc/wpgtk/wpg.conf``` and ```/usr/local/etc/wpgtk/wpg.conf```, which are both not the correct path.

**Comment by deviantfero** [comment]
has it happened to you too? it seems to be an issue with pip3 not using the correct user prefix, this is most likely the result of not executing pip3 as a super user or using the --user flag when doing a pip3 install.

wpgtk looks for both prefixes as `setuptools` isn't really clear on what the user prefix should be on different distributions of GNU/Linux.

` File "/home/invadrr/.local/lib/python3.5/site-packages/wpgtk/data/config.py", line 93, in init`
this path is why I suspect this is happening.

**Comment by FlorianFranzen** [comment]
Pip is using the right prefix, wpgtk is just not following conventions. Installing wpgtk as a user should be supported, else wpgtk is packaged incorrectly and should not be on PyPI. 

Why should the backup config be installed into that weird location anyway? Why not keep it in the package path and copy if from there? I proposed the needed changes for this approach in #55.

**Comment by deviantfero** [comment]
You're absolutely right @FlorianFranzen I'm about to merge your pull request and make a new release, so it's the version that pip installs from now on. (my connection is bad right now).

**Comment by chancellorr** [comment]
Welp, I believe that I am dumb. I installed it with root privileges and all is well. Thank you @deviantfero. Such a stupid mistake. Lol.

**Comment by deviantfero** [comment]
no, actually @FlorianFranzen is right, standard behaviour is that you should be able to install it that way too, anyway, thanks for bringing this up. I'll do some tests with the fix and close this issue afterwards

**Comment by chancellorr** [comment]
No problem. I have another question/problem. It's not setting the GTK or Openbox theme, nor is it setting the wallpaper. tint2 changes and all the terminal colors change, but that's it. I have all the dependencies installed. I'm sure it's probably something on my end. I just love this little program and would like to use every bit of  it. Sorry for asking another question.

**Comment by deviantfero** [comment]
don't worry about it, you can ask questions first off, do you have the themes installed?
I have a small script that installs with wpgtk which can download the themes for you, it's called `wpg-install.sh`.

read the help of that command with `wpg-install.sh -h` after you've done that, you need to apply the themes, a good program for doing that is `lxappearance` which let's you set your GTK theme and icons. (if you've installed the themes they should appear here `FlatColor` for GTK and `Flattrcolor` for icons), for openbox you have `obconf` which helps you set your wm-theme, you should also see wpgtk themes, namely `colorbamboo` and `colorbamboo-nb`.

about the wallpaper, you can either install `feh` or `nitrogen`, go to the README.md for more details.

**Comment by chancellorr** [comment]
Oh my gosh. I'm not a smart man. Lol. I glazed right over the names of the themes. They did install, I just didn't have them selected in either lxappearance or obconf. Thank you again for all your help. I really appreciate it @deviantfero! Keep up the good work.
