### ISSUE TITLE
wpg -t slow?

### ISSUE THREAD

**Issue by vsr625** [deviantfero/wpgtk#57]
I don't know if others are facing this issue or not, but I am facing this weird issue where in if I add (wpg -t) into my .zshrc as mentioned in the instructions, then next whenever I open a terminal( I use rxvt-unicode ), the terminal starts with the default colorscheme and it takes like one second to set the colorscheme to a proper one.

I wouldn't be posting an issue here if I was facing the same issue with wal script(wal -r), with just the wal script, it works just fine, meaning there isn't any visible lag that I can notice whenever I open a new terminal window.

And I also wanted to know how to set the gtk theme, I am not able to figure it out.

**Comment by deviantfero** [comment]
What terminal are you using? It's so i can test on the same terminal as
yours

**Comment by vsr625** [comment]
Package name for terminal is rxvt-unicode-patched and I am running the terminal in daemon mode.

**Comment by deviantfero** [comment]
The colors should be exported with with xrdb for those terminals, you
shouldn't need to put that in your .zshrc, but I'll check it out anyway

**Comment by vsr625** [comment]
Oh, then what am I doing wrong here? so it should work without adding wpg -t in .zshrc? I can post my .Xresources file if needed

**Comment by deviantfero** [comment]
no, what I'm saying is that if you're using a terminal that can make use of an .Xresources files, the color merging should be automatic, without the need for `(wpg -t)` in your `.zshrc`, could you remove that line and try to set a theme?

do you have `xrdb` installed?

**Comment by vsr625** [comment]
It doesn't work if I remove wpg-t from .zshrc, and yes I have xrdb installed. I have set zsh syntax highlight custom rules and use transparency through compton, does that matter?

**Comment by deviantfero** [comment]
If you have custom colors defined in your `.Xresources`, those will take precedence in `wpgtk` and it will not replace them, this is to allow some flexibility in console colorschemes (let's say you want a custom foreground color).

so if you comment the colors defined in your `.Xresources` it should work automatically without `wpg -t`, anyway, if AFTER doing that colors still don't apply, you can add `(wpg -r &)` to `.zshrc` instead and you should feel the speedup.

**Comment by vsr625** [comment]
Oh, thanks it works now, without using the wpg -t, I didn't expect such fast support. Thanks.

**Comment by vsr625** [comment]
Oh, I forgot to ask, how to set the gtk theme and icons?

**Comment by deviantfero** [comment]
If you already installed them using wpg-install -a, you should be able to
use a program like lxappereance to set your GTK theme and icons, the should
appear there once they're installed.

**Comment by vsr625** [comment]
For some reason the theme isn't being listed on lxappearance, you can tell me the exact name of the theme, I will change the values inside .gtkrc file

**Comment by deviantfero** [comment]
`FlatColor` for GTK and `FlattrColor` for Icons, check in your `~/.themes/` and `~/.icons` the themes and icons should be there after running `wpg-install.sh -a`, do not run that as root
