### ISSUE TITLE
Making colors persist in Termite

### ISSUE THREAD

**Issue by alizeegagnon** [deviantfero/wpgtk#59]
Hello, I am using termite and the colors would only appear when pressing "set" in the GUI. While running pipes.sh, the colors would reset each time the screen would reset. I saw in the readme that I should paste "wpg -V &" in my .bashrc, but I get an unrecognized argument error.

**Comment by deviantfero** [comment]
Use (wpg -t &) instead, I tried it yesterday and it worked -V has been
removed for the time being. Please let me know if it works.

**Comment by alizeegagnon** [comment]
It didn't work. I got the message "[1]+ Done wpg -t". Also, each time the color is set, a color code like "#291C11" is pasted into every open terminal.

**Comment by deviantfero** [comment]
I'll reincorporate -V into wpg and make a new release so you can update,
thanks for the heads up, it won't take long.

**Comment by deviantfero** [comment]
I'm sorry I just tried it out in my machine and it works on termite without an issue, can you tell me the output of doing `wpg -v`?

**Comment by alizeegagnon** [comment]
wpg -v: 
current version: 4.5.8

**Comment by deviantfero** [comment]
checkout [this gif](https://gfycat.com/DisguisedSpeedyAfricanclawedfrog) is there anything different about your setup? Thank you for your patience.

**Comment by alizeegagnon** [comment]
There was something different: I did not have the () around wpg -t &. However it doesn't solve the problem.

**Comment by deviantfero** [comment]
Could you try to generate a new colorscheme, try again and post results? also what distro are you running? did you install with `pip`? or via the `AUR` package? I'm not able to reproduce this issue, but I'll try my best to fix it, seems that vte support is enabled by default.

**Comment by alizeegagnon** [comment]
I am on Ubuntu 17.04 and installed with pip3. I use i3. The output of termite -v is "termite v12-28-gd87e7c8". 
I generated a new color scheme and it is the same.

**Comment by deviantfero** [comment]
You're lucky, I'm carrying a live cd with Ubuntu 17.04 I'll do some testing and I'll get back at you.

**Comment by alizeegagnon** [comment]
I just got an idea. I had another problem while adding optional config files to wpg. The GUI stalled when picking the config files for termite, which was at /etc/xdg/termite/config, and for i3status, which was at /etc/i3status.conf. I manually pasted the files into ~/.themes/color_other/ and created the .base file. It seems to work fine for i3status, but maybe it is a problem for termite.

**Comment by deviantfero** [comment]
No basefile is needed for terminals, which colors are restored usually with `wpg -t` or `.Xresources` if they support it, I've finished testing with `termite` on `ubuntu 17.04` and there seems to be no problem on any terminal.

you can run `pip install pywal wpgtk --upgrade` and see if that does the trick.

about the UI stalling, I'm working on fixing that in https://github.com/deviantfero/wpgtk/pull/58, you can follow progress on that there.

another thing, to add an optional config file, explicitly click on add or repeat the double click if the dialog does not close, this is another issue I'm going to address in https://github.com/deviantfero/wpgtk/pull/58. wpgtk does not simply copy the files to the `.colors_other` folder, they create a copy of the original and the original is replaced by a soft link to that copy in `.colors_other` so you don't have to move anything, it also creates a backup in the directory of the original.

as of right now, I'm not able to reproduce this issue, does it happen with every terminal?

**Comment by alizeegagnon** [comment]
I just tested with xterm and it does not happen. What does happen with xterm is that when pipes.sh resest the screen, it goes back to the last colorscheme, and I have to reopen it to apply the colorscheme. (Is my testing with pipes.sh ok ?)

**Comment by deviantfero** [comment]
can you post your `.bashrc` ? do you use another shell other than bash? I've tested with `pipes.sh` and i'm not getting the same result as you, everything seems to work fine.

**Comment by alizeegagnon** [comment]
here is my .bashrc

https://pastebin.com/772vhGBc

**Comment by deviantfero** [comment]
Have you resolved your issue? I could not find anything particularily weird about your .bashrc and I'm unable to reproduce, if anyone is having this issue, please let me know

**Comment by alizeegagnon** [comment]
The pipes.sh script still doesn't work, but the bug doesn't affect programs I actually use so I did not work on solving the issue.

**Comment by deviantfero** [comment]
you can now follow progress in #64
