### ISSUE TITLE
Can't predefine my background color anymore

### ISSUE THREAD

**Issue by jonathashenriques** [deviantfero/wpgtk#62]
After the lasts updates of `wpgtk`, i can not set an default background color to my terminal with the `.Xresources` anymore. This is how it looks now:

![2017-10-14-10-42-31](https://user-images.githubusercontent.com/21113681/31580812-2b67c0ea-b14a-11e7-9634-9a378348989f.png)

**Comment by deviantfero** [comment]
what terminal are you using?

**Comment by jonathashenriques** [comment]
I'm using `urxvt`

**Comment by deviantfero** [comment]
Hi, sorry for the late reply, please add this to your `.Xresources` or `.Xdefaults`

`URxvt*borderColor: #yourcolorhere`

**Comment by deviantfero** [comment]
this should've fixed your issue, I'm closing this.
