### ISSUE TITLE
adding autocomplete functionality

### ISSUE THREAD

**Issue by Risebell** [deviantfero/wpgtk#63]
First of all, thanks for the great project, really loving it so far!
That said, I'd like to see autocomplete functionality, especially for wallpapers and colorschemes for the '-s' option.
I already wrote a autocomplete function for zsh that kinda works, you can find it here:
[gist](https://gist.github.com/Risebell/529aaa75bcc0c0e71fd3a873a4b523b7)
I wonder if and how we could incorporate this into the project, and what shells (most likely bash) we should target aswell. Maybe there's also a much better/easier way to implement such functionality.
I'd like to hear opinions about this!

**Comment by deviantfero** [comment]
I love the idea, it's something I've always wanted to do but i had no time
to actually look into, at least at the moment, I think bash, zsh and fish
should be our first options, if there was a way to implement this
independently from the shell, as in, a python alternative, I'll take a look
later today at the code

**Comment by Risebell** [comment]
thanks for the feedback!
unfortunately there seems to be no way to implement this completely independent of the shell, but there are some tools to automatically create a complete function, atleast for bash and zsh.
[argcomplete](https://pypi.python.org/pypi/argcomplete)
[genzshcomp](https://pypi.python.org/pypi/genzshcomp)
Maybe those might help.

Also, zsh seems to have an option for backwards compatibility with bash completion, so we would only have to implement it for bash, maybe.

About fish, I actually have never used it and I have no clue about how completion works there; in fact, I'm quite new to this topic at all...

**Comment by deviantfero** [comment]
most shells should be backwards compatible with bash I think, argcomplete would be the sanest choice.

**Comment by Risebell** [comment]
So, I've tried to add argcomplete to the project and had atleast some success..
You can find my efforts here: [github](https://github.com/Risebell/wpgtk/tree/autocomplete)
Don't expect to much :P 
I have basically just done whats mentioned in the docs of argcomplete.
If I run `eval "$(register-python-argcomplete /full/path/to/__main__.py)"` `/full/path/to/__main__.py -<TAB>` shows all the different options and `-s <TAB>` lists all already added wallpapers.
That's about all thats working, one main issue I have is that after installing the project with the included setup.py and doing the same steps as above with the resulting wpg script, completion doesn't work anymore and in fact `/full/path/to/wpg -<TAB>` starts the wpgtk gui for some reason. I'm not quite sure why that happens.

Also, should I start a pull request for this?

**Comment by deviantfero** [comment]
please do, though I might be slow to review it since I really do not dispose of much time right now

**Comment by Risebell** [comment]
I'm sorry for responding so late, was kinda busy recently. I thought about this again and I'm still not sure if we should implement argcomplete. First of all, it couldn't make proper use of zsh's completion system, which would be a shame, and second I realized that it's kinda easy to implement those completion functions, especially since we are using argparse.
Both zsh (_gnu_generic) and bash (_parse_help and _parse_usage, provided by [bash-completion](https://github.com/scop/bash-completion)) have helper functions to create autocompletion by parsing `<command> --help` (needs output that's somewhat similar to GNU tools, argparse seems to do that), which would take away a lot of maintenance work, and works great as far as I can tell.
The only thing left to do then is to autocomplete wallpaper names.
I've implemented a function for [bash](https://gist.github.com/Risebell/b744eef645b9ed237103da149e804c6f) and an updated one for [zsh](https://gist.github.com/Risebell/529aaa75bcc0c0e71fd3a873a4b523b7); for bash you just need to source it and have bash-completion installed; for zsh you need to put it somewhere in $fpath, `autoload -Uz compinit` (might happen in .zshrc), `compinit` and `compdef _wpg wpg`.
I'll think about how those scripts could be added to the project and where we would need to put them on installation for everything to happen automagically, but in my opinion this is a superior solution to argcomplete.

**Comment by deviantfero** [comment]
I've merged #66.
