### ISSUE TITLE
Colorscheme inconsistent from vim to neovim

### ISSUE THREAD

**Issue by alizeegagnon** [deviantfero/wpgtk#67]
Hello, not sure if this is an issue or a simple question. I recently installed neovim and wpg does modify nvim's colors. However, it does not give the same color to the same syntax elements.
 For example, in vim, LaTeX comments are color 14, while in neovim they are color 04. Is this a vim/neovim compatibility problem, or something that can be solved by wpg ?

**Comment by deviantfero** [comment]
Hi, I have a custom theme for vim, I'm not sure about why you're seeing that difference, this should not happen, unless your t_Co or theme is different in vim than in neovim, you can find my custom theme over here: (btw, your t_Co should be 256 on both, not sure if nvim has this option though).

https://github.com/deviantfero/dotfiles/blob/master/vim/colors/wpgtk.vim

it is not a very complex theme, but it limits itself to using 16 colors that are provided by wpgtk, you can modify at your leisure, I update it regularly, I plan to make it part of the instalables of `wpg-install.sh` or setup a different repo so it's instalable via Plug or some other plugin manager

**Comment by deviantfero** [comment]
Did this solution work for you?
