### ISSUE TITLE
Error:: missing pygobject module, use cli

### ISSUE THREAD

**Issue by Waynekosimoto** [deviantfero/wpgtk#71]
I'm probably doing something really silly. Although I installed python-gobject I'm still getting errors that I'm missing the pygobject module. I installed all the dependencies, Pillow (4.3.0), python-gobject 3.22.0-2, python-imaging 4.0.04-4, xsltproc 1.1.29-2.1, pywal (0.7.5), feh 2.18-2, but i'm still getting an error. I'm running Debian.

**Comment by deviantfero** [comment]
Hi there, depends on the distro you're currently on, could you give me those details?

**Comment by Waynekosimoto** [comment]
I'm running crunchbang ++. The openbox distro.

**Comment by deviantfero** [comment]
Did you install python-gobject or python3-gobject?

**Comment by Waynekosimoto** [comment]
![2017-12-25--1514247255_674x475_scrot](https://user-images.githubusercontent.com/12769365/34343723-7675e340-e99f-11e7-912d-e97825127ccf.png)

**Comment by Waynekosimoto** [comment]
I can't find python3-gobject anywhere :/

**Comment by deviantfero** [comment]
your screenfetch looks really nice, anyway have you tried this package?
**https://packages.debian.org/sid/python3-gobject**

it's called `python3-gi` in debian sid, still #! is based on debian so it should be named similarly or the same

**Comment by Waynekosimoto** [comment]
I actually did but nothing changed. Also thanks
https://pkgs.org/download/python3-gobject
This is the best i found. But i'm running Debian 9

**Comment by Waynekosimoto** [comment]
![2017-12-25--1514248002_1805x859_scrot](https://user-images.githubusercontent.com/12769365/34343806-48a32c6e-e9a1-11e7-98cd-a5d8381c03a4.png)

**Comment by Waynekosimoto** [comment]
I think python3-gi is actually python3-gobject cause when I tried downloading it, it just downloaded python3-gi

**Comment by deviantfero** [comment]
So it's still not working?

**Comment by Waynekosimoto** [comment]
It's the same file as I had before so yep still not working :/

**Comment by deviantfero** [comment]
please confirm about dependencies being python3 versions, or about installing with pip3 or just pip

**Comment by Waynekosimoto** [comment]
![2017-12-25--1514249277_211x387_scrot](https://user-images.githubusercontent.com/12769365/34343921-303dfb74-e9a4-11e7-8567-f59982c6dd67.png)

**Comment by Waynekosimoto** [comment]
I'm actually using pip3.6 from python3.6

**Comment by deviantfero** [comment]
alright, I'll whip out a #!++ vm, I'll let you know what's going on

**Comment by Waynekosimoto** [comment]
The miles I'm making you go lol

**Comment by deviantfero** [comment]
Don't worry about it, I'll just test in a live environment, besides, if you're having this issue it is most likely that somebody else has, just that they didn't raise an issue, it's really helpful

**Comment by deviantfero** [comment]
Hi this image is from a live environment of the latest #!++ live image, the only thing I installed was `pip3` and `wpgtk`, it worked without issues, a difference I can see is that `pygobject` does not appear on your pip list, could you try running `sudo pip3.6 install pygobject` ?

**Comment by Waynekosimoto** [comment]
```
sudo pip3.6 install pygobject             
Collecting pygobject
  Using cached PyGObject-3.27.1.tar.gz
Requirement already satisfied: pycairo>=1.11.1 in /usr/local/lib/python3.6/site-packages (from pygobject)
Installing collected packages: pygobject
  Running setup.py install for pygobject ... error
    Complete output from command /usr/local/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_96uybds/pygobject/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-i326khgo-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/gi
    copying gi/_signalhelper.py -> build/lib.linux-x86_64-3.6/gi
    copying gi/types.py -> build/lib.linux-x86_64-3.6/gi
    copying gi/module.py -> build/lib.linux-x86_64-3.6/gi
    copying gi/__init__.py -> build/lib.linux-x86_64-3.6/gi
    copying gi/_constants.py -> build/lib.linux-x86_64-3.6/gi
    copying gi/_error.py -> build/lib.linux-x86_64-3.6/gi
    copying gi/docstring.py -> build/lib.linux-x86_64-3.6/gi
    copying gi/_propertyhelper.py -> build/lib.linux-x86_64-3.6/gi
    copying gi/pygtkcompat.py -> build/lib.linux-x86_64-3.6/gi
    copying gi/_ossighelper.py -> build/lib.linux-x86_64-3.6/gi
    copying gi/_option.py -> build/lib.linux-x86_64-3.6/gi
    copying gi/importer.py -> build/lib.linux-x86_64-3.6/gi
    creating build/lib.linux-x86_64-3.6/pygtkcompat
    copying pygtkcompat/__init__.py -> build/lib.linux-x86_64-3.6/pygtkcompat
    copying pygtkcompat/generictreemodel.py -> build/lib.linux-x86_64-3.6/pygtkcompat
    copying pygtkcompat/pygtkcompat.py -> build/lib.linux-x86_64-3.6/pygtkcompat
    creating build/lib.linux-x86_64-3.6/gi/overrides
    copying gi/overrides/Gdk.py -> build/lib.linux-x86_64-3.6/gi/overrides
    copying gi/overrides/Pango.py -> build/lib.linux-x86_64-3.6/gi/overrides
    copying gi/overrides/__init__.py -> build/lib.linux-x86_64-3.6/gi/overrides
    copying gi/overrides/Gio.py -> build/lib.linux-x86_64-3.6/gi/overrides
    copying gi/overrides/GObject.py -> build/lib.linux-x86_64-3.6/gi/overrides
    copying gi/overrides/GIMarshallingTests.py -> build/lib.linux-x86_64-3.6/gi/overrides
    copying gi/overrides/GLib.py -> build/lib.linux-x86_64-3.6/gi/overrides
    copying gi/overrides/keysyms.py -> build/lib.linux-x86_64-3.6/gi/overrides
    copying gi/overrides/Gtk.py -> build/lib.linux-x86_64-3.6/gi/overrides
    creating build/lib.linux-x86_64-3.6/gi/repository
    copying gi/repository/__init__.py -> build/lib.linux-x86_64-3.6/gi/repository
    running build_ext
    Package gobject-introspection-1.0 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `gobject-introspection-1.0.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'gobject-introspection-1.0' found
    Command '['pkg-config', '--print-errors', '--exists', 'gobject-introspection-1.0 >= 1.46.0']' returned non-zero exit status 1.
    
    ----------------------------------------
Command "/usr/local/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_96uybds/pygobject/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-i326khgo-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-_96uybds/pygobject/

```

**Comment by deviantfero** [comment]
try running `sudo apt-get install gobject-introspection` and then `sudo pip3.6 install pygobject` again, thanks for your patience

**Comment by Waynekosimoto** [comment]
God what is wrong with my machine. I did that and it's the same thing.

**Comment by Waynekosimoto** [comment]
`Sudo apt install libgirespository1.0-dev`

**Comment by Waynekosimoto** [comment]
thanks a lot for the help

**Comment by deviantfero** [comment]
Sorry I didn't hit the nail on this one, I'll try to add an entry to the README.md to avoid this in the future, hope you enjoy `wpgtk` try to play around with the themes and defaults it includes!

**Comment by Waynekosimoto** [comment]
Don't worry about it. I wouldn't have figured it out without you leading me
