### ISSUE TITLE
Terminal Colors are not working?

### ISSUE THREAD

**Issue by Waynekosimoto** [deviantfero/wpgtk#72]
Because of I somehow messed up my computer trying to install steam, I reinstalled everything and now terminal colors aren't working. This might be because pywal was recently updated. I was running 0.7.5 pywal before and now I have 1.0 and it's broken. Is it just me?

**Comment by Waynekosimoto** [comment]
Just downgraded to pywal 0.7.5 and it's working. Maybe you do have to change something :(

**Comment by dylanaraps** [comment]
For clarity:

- `pywal.reload.colors(vte, cache_dir)` was removed.
    - No more `wal -r` or `wpg -?`.
    - It is now recommended to `cat ~/.cache/wal/sequences` directly.
    - This makes restoring schemes instant and 300ms faster.
- The vte flag is no longer needed (`-t` in pywal `-?`) in wpgtk.

**Comment by deviantfero** [comment]
as of right now I'm talking with @dylanaraps to see if we fix it on `wpgtk` or if he will re-add the option to -r from `wal` with a simple syscall.

**Comment by dylanaraps** [comment]
See my response here: https://github.com/dylanaraps/pywal/issues/147

**Comment by deviantfero** [comment]
This issue has been taken care of in the latest version of `wpgtk`, please update via pip, thanks @dylanaraps
