### ISSUE TITLE
please move config to $XDG_CONFIG_HOME/wpg or similar.

### ISSUE THREAD

**Issue by ohnonot** [deviantfero/wpgtk#75]
hello, i just installed this on archlinux and i love it - esp. since i use openbox & tint2 myself.

but - i had a hard time finding out where wpg put its configuration, and was a little surprised to find it in `~/.wallpapers` - not so good imo, because
a) $HOME is cluttered already, therefore nowadays $XDG_CONFIG_HOME is used, and
b) the folder should reflect the application name
i hope you understand.
thanks.

**Comment by deviantfero** [comment]
I will take this into account in the next release, please keep tabs on this, thanks for the suggestion I'll keep this issue open.

**Comment by deviantfero** [comment]
please follow #76 for progress.
