### ISSUE TITLE
URXVT true transparency not working while using WPGTK

### ISSUE THREAD

**Issue by YOUR-WORST-TACO** [deviantfero/wpgtk#79]
I currently am trying to make urxvt transparent, but this is proving very difficult, I realize you can use phsudo transparency, however I want my compositor to handle transparency. I have narrowed this issue down to how wpgtk changes terminal color schemes.

For example in my .Xresources folder I set my background liks so
`URxvt.background: [80]#COLOR0`
`URxvt.depth: 32`
This works as long as I dont have
`(cat $HOME/.config/wpg/sequences &)`
in my bashrc, however on changing my colorscheme through WPG it removes the background transparency, not sure if this is something that can be worked around or fixed.

**Comment by deviantfero** [comment]
hi, duplicate of #77,  see that issue to get the desired result and an explanation on how to achieve it and why it is like that. Please let me know how that went

**Comment by YOUR-WORST-TACO** [comment]
Thank you for the quick response, I believe that should work for my purposes.
Keep up the good work!

**Comment by deviantfero** [comment]
great, thanks for stoping by!
