### ISSUE TITLE
Support for termite config

### ISSUE THREAD

**Issue by DerVerruckteFuchs** [deviantfero/wpgtk#8]
Termite comes with its own config, `~/.config/termite/config`, for colors and other options. It would be nice to have support for changing termite's colorscheme automatically. You could even throw in a `ctrl-shift-r` in a script somewhere when focused on a termite window to reload the changed config automatically.

**Comment by rscmbbng** [comment]
it is possible to edit multiple types of config files, for terminator I've done the following:

```
ls -l ~/.config/terminator 
total 0
lrwxrwxrwx 1 r r 45 Mar 21 19:14 config -> ~/.themes/color_other/config_terminator
```

Have a look at the examples in [README](https://github.com/deviantfero/wpgtk#version)

**Comment by deviantfero** [comment]
I think the problem here is that for now this config filed only support 2 colors, soon i will add support for those to colors "inactive and active" and the full 16 other colors it generates

**Comment by deviantfero** [comment]
Hi there, i know it's been a while, but i'm closing this issue as wpgtk 3.0 has now support for optional config files and 16 colors, it's all detailed in the readme, it creates the symbolic link automatically so you don't have to worry about a thing.
