### ISSUE TITLE
GTK themes not changing after first time

### ISSUE THREAD

**Issue by SanketDG** [deviantfero/wpgtk#87]
Pretty sure this is me doing something wrong, but after I do `wpg-install.sh -g` for the second time, the FlatColor theme doesn't change at all.

Some help would be appreciated

**Comment by deviantfero** [comment]
Hi, are you sure you've set your GTK theme to FlatColor using a utility like `lxappereance`? if you've already done that, I would like you to say what version of wpgtk you're coming from, you can get that info by doing `$ wpg --version` on the command line

**Comment by SanketDG** [comment]
Yup I used the `gnome-tweak-tool` for Gnome.

`wpg --version` is `4.9.3`

It looks like it updated itself after I restarted my machine, so I am not sure what happened.

**Comment by deviantfero** [comment]
Is it working now though?

**Comment by SanketDG** [comment]
Yup its working great! Thanks!

> It looks like it updated itself after I restarted my machine, so I am not sure what happened.

I see how this can be confusing. I meant the GTK theme updated itself after I restarted my machine.

I will look into this, and see if I can find anything not normal. Will keep you posted!

**Comment by deviantfero** [comment]
Thanks, I think is because I obsoleted the previous template format for version `4.9.2`, so they did not change until `wpgtk` was updated, I'll keep the issue open for the next two days, if you don't find any issues by then I'll close this issue.
