### ISSUE TITLE
 Error:: missing pygobject module, use cli

### ISSUE THREAD

**Issue by baconicsynergy** [deviantfero/wpgtk#90]
I'm running Trisquel 8 Flidas (Ubuntu 16.04), and am still receiving this dreaded error, even after following every instruction from https://github.com/deviantfero/wpgtk/issues/71.

Halp :( I love wpgtk and I desperately want it working on my machine

**Comment by baconicsynergy** [comment]
I've had the same issue with vanilla Ubuntu 16.04, so the issue is definitely not from Trisquel

**Comment by deviantfero** [comment]
Hi there, I'm sorry I took so long to answer you, have you install pygobject libraries for python3?

**Comment by baconicsynergy** [comment]
I'm having a difficult time finding the pygobject libraries via apt. Any idea what I should be looking for?

**Comment by baconicsynergy** [comment]
Found out an answer - installed the gir1.2-gtk-3.0 package and wpgtk seems to be working now. Strange!

**Comment by deviantfero** [comment]
Yep, it's an issue with most distros, hard to find package, idk why, glad you did though :+1:  I'll close this, enjoy the software!
