### ISSUE TITLE
typo in wpg-install.sh 

### ISSUE THREAD

**Issue by Risebell** [deviantfero/wpgtk#91]
There is a typo in wpg-install.sh line number 112.
`cp "${HOME}/.config/polyba/config" "${HOME}/.config/polybar/config.bak" 2>/dev/null;`
should probably be
`cp "${HOME}/.config/polybar/config" "${HOME}/.config/polybar/config.bak" 2>/dev/null;`

**Comment by deviantfero** [comment]
thanks! this has been fixed in the latest release!
