### ISSUE TITLE
How to install/where to find FlatColor and flattricon?

### ISSUE THREAD

**Issue by baconicsynergy** [deviantfero/wpgtk#92]
I'm sorry if this question doesn't belong here :/ I remember having the gtk theme and icon set in a previous installation on some other distro, but I can't seem to be able to find out how to install them on Trisquel 8 / Ubuntu 16.04

**Comment by deviantfero** [comment]
your question definetly belongs here, don't doubt to ask. I include an installer for those things with `wpgtk`, to install those 2 things, you would do:

```sh
wpg-install.sh -gi
```
This will install the GTK+ theme and the icon set, it will do so on your $HOME, under ~/.themes and ~/.icons respectively.

You can also do `wpg-install.sh -h` for more info on the default templates available, please check the wiki too, there's more info there, I'll leave this issue open, please confirm that the installer is working as intended.

**Comment by baconicsynergy** [comment]
Fantastic! My installation is looking absolutely gorgeous thanks to you. I would love to make a donation/buy you a cup of coffee for sure!
