### ISSUE TITLE
Feature request: Make the FlatColor gtk theme available as a separate install

### ISSUE THREAD

**Issue by EvilJimJafar** [deviantfero/wpgtk#94]
Hi @deviantfero :)

It would be great to have your FlatColor gtk theme available without wpgtk for people who want to roll their own color scheme theming without the link to background images.

**Comment by deviantfero** [comment]
Hi! that's pretty simple actually, just clone the [templates](https://github.com/deviantfero/wpgtk-templates) repository and copy the `FlatColor` folder to your `~/.themes/` folder, and there you have it.

of course, colors won't change dynamically, you'd have to make adjustments yourself, it is pretty simple compared to other themes though, all colors are defined in one file only.

**Comment by EvilJimJafar** [comment]
Thanks!
I was thinking it's useful enough to stand on it's own as a separate project and even go in the AUR.
I've never submitted a package to the AUR - I'd be glad to try and do it for you as a learning experience if you're cool with that?

**Comment by deviantfero** [comment]
Yep, go ahead, please let me know the name of the package when you get it
done.

-- att. Fernando Vasquez --

**Comment by EvilJimJafar** [comment]
Sweet, I'll try to figure it out this week

**Comment by EvilJimJafar** [comment]
OK, I'm pretty much ready to go. Can you come up with a better description than this?

> An easily customisable flat GTK theme. This is the theme used in wpgtk.

And would you like to be listed as a package maintainer? I'll use the same information as in the wpgtk-git PKGBUILD if so.

**Comment by deviantfero** [comment]
Yep, that'll be fine by me, add me as a mantainer, my username in the AUR
is also deviantfero

-- att. Fernando Vasquez --

**Comment by EvilJimJafar** [comment]
All done :)

```
➜ yaourt -Ss gtk-theme-flat-color
aur/gtk-theme-flat-color-git 20180507.ff68c61-1 (0) (0.00)
    A flat GTK theme designed to be easily re-colored. This is the theme used in wpgtk.
```
