### ISSUE TITLE
Unknown issue

### ISSUE THREAD

**Issue by Vortelf** [deviantfero/wpgtk#95]
For some reason, whenever I try to add this image, wpgtk crashes
```
[wrn] wal           Imagemagick couldn't generate a palette.
[wrn] wal           Trying a larger palette size 34
[err] wal           Imagemagick couldn't generate a suitable palette.
```
and it was working before I updated it to 5.x.x

https://imgur.com/AREZRoq

**Comment by deviantfero** [comment]
the issue might have to do with pywal rather than with wpgtk, you can always install another backend like `colorthief` and try your luck with that one, please let me know how it went with another backend.
