### ISSUE TITLE
Add multiple wallpapers at once

### ISSUE THREAD

**Issue by AUTplayed** [deviantfero/wpgtk#96]
Hi, I have a somewhat big wallpaper folder and I would love if you could just select multiple images at once, and add them as wallpapers. 

Thanks

edit: sure I could just use the command line, but hey

**Comment by deviantfero** [comment]
hi @AUTplayed, I finally got the chance to add multiple file support from GUI and star pattern support to `wpgtk`, please checkout #98.

**Comment by AUTplayed** [comment]
cool, I'll try it out later today 👍

**Comment by deviantfero** [comment]
please re-open the issue if it's not working as expected!

thanks for testing, I'll merge as soon as I hear back from you.

-- att. Fernando Vasquez --
