### ISSUE TITLE
Reddit followup: Help make generated color schemes adhere to readability rules

### ISSUE THREAD

**Issue by pascalwhoop** [deviantfero/wpgtk#99]
Hi,
you asked me to issue this here and who can say no to such a responsive dev.

[Solarized](http://ethanschoonover.com/solarized) is the godfather of custom terminal colors. It's following many rules that allow for readability and help developers to subconsciously work more efficiently. It also offers a dark and a light variant which barely change the colors. That's some serious craftmanship.

As a start, it would be great if wpgtk allows us to define a pattern that defines what colors are expected at which spot. If wpgtk generates 14 colors from the wallpaper, it would be nice to have it adhere to a ruleset where certain colors are always placed in certain spots. I believe going with solarized is a save bet here. 

[urxvt solarized] (https://gist.github.com/yevgenko/1167205) is probably a good guideline. Alternatively, the original [vim colors for solarized](https://github.com/altercation/vim-colors-solarized).

First idea: Take the generated colors and instead of sorting them from dark -> light or blue -> red or whatever ordering is followed, place each color in the spot that matches the solarized color in that spot the closest. So because

```
!! green dark/light
*color2: #859900
``` 
is set in solarized, the color that is closest to #859900 is defined as color2. This could be enabled with a `--solarizing` flag to not force everyone to use this.

**Comment by pascalwhoop** [comment]
https://stackoverflow.com/questions/14168456/python-how-to-sort-a-list-of-colors-based-on-a-colors-distance-from-a-sourc#14168486
color distances, in case you don't already know how to do it.

**Comment by deviantfero** [comment]
I can think of something like:

The color that is redisher goes in spot color1 and color9, where the red would normally go, and so on (with green, blue, cyan, etc). the thing is that when the colorscheme is to monocromatic, it would still be unreadable, but it would definetly be a nice start.

I'll keep this in mind for the next release.

in the mean time, you can use the "shuffle sort" in `wpgtk` to try and get some kind of logical order out of the colorscheme, that's what I currently do.

**Comment by deviantfero** [comment]
hey, you can check an update on this in #105

**Comment by deviantfero** [comment]
Hi, this PR has been merged and the functionality is out in version 5.7.0, if you feel this is somehow not enough please feel free to open a new issue!
